### ISSUE TITLE
[5.0.0-beta] first sync has no packageHash in query

### ISSUE THREAD

**Issue by lisong** [Microsoft/react-native-code-push#1000]
### Steps to Reproduce
1. install demo app
2. click sync
3. it's download full package in first sync, it should show "App up to date"

### Expected Behavior

```
/updateCheck?deploymentKey=BPPCDEeergFkpHur4YNXCjqXVjR6qLF160UDg&appVersion=2.0.0&packageHash=16bd9232a31ecdc4cfd01a660dbd81e28b3e5709a1505daf429028c5ec49fe9f&isCompanion=&label=&clientUniqueId=319708d364f191f1
```

### Actual Behavior
What actually happens?
```
/updateCheck?deploymentKey=BPPCDEeergFkpHur4YNXCjqXVjR6qLF160UDg&appVersion=2.0.0&packageHash=&isCompanion=&label=&clientUniqueId=319708d364f191f1
```

### Environment

* react-native-code-push version: 5.0.0-beta
* react-native version: 0.47.1
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build?  both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment]
Hi @lisong, thanks for reaching us. Yeah, that's known "issue" and we've tried to fix it but [reverted](https://github.com/Microsoft/react-native-code-push/commit/8d63d81bf380f1d34c580e9f81ee7c9405d864b0#diff-fdfb3b2552c5b0ea96bacdf49a2581c7) our changes due to the following issues: #906, #910

We've already deployed server-side changes needed to fix the issue, so you could try to perform [this changes](https://github.com/Microsoft/react-native-code-push/commit/a59e4cfabb105619ffff1a6999da064dc4213e9b#diff-fdfb3b2552c5b0ea96bacdf49a2581c7) and verify if it works for you. We also gonna test it and in case everything works well - we'll create PR.

**Comment by lisong** [comment]
OK

**Comment by lisong** [comment]
why v5.3.2 not fix
```js
  let queryPackage;
  if (localPackage) {
    queryPackage = localPackage;
  } else {
    queryPackage = { appVersion: config.appVersion };
    if (Platform.OS === "ios" && config.packageHash) {
      queryPackage.packageHash = config.packageHash;
    }
  }
```
