### ISSUE TITLE
Will using react-native-code-push lead to rejection of my app from app store?

### ISSUE THREAD

**Issue by jpahalwani** [Microsoft/react-native-code-push#1010]
I am using react-native-code-push version 3.0.0. I have read at several forums that app store rejects the app when code push is used. Will this lead to rejection of my app from app store?

**Comment by max-mironov** [comment]
Hello @jpahalwani, so we have several related threads regarding this, you can quickly observe them:

https://github.com/Microsoft/react-native-code-push/issues/748
https://github.com/Microsoft/react-native-code-push/issues/949
https://github.com/Microsoft/code-push/issues/415
https://github.com/Microsoft/code-push/issues/486

In short for today we are not aware if any apps were rejected due to code-push usage itself.
We are actively monitoring this and at that moment it turns our that none of these issues were really related to code-push plugin usage.
 
Also we do not recommend to use update dialog within your app, please take a look at [this section](https://github.com/Microsoft/react-native-code-push#store-guideline-compliance) for more details.

**Comment by max-mironov** [comment]
@jpahalwani I'm closing this issue currently if you have no more questions, feel free to reach us if any.
