### ISSUE TITLE
How do you guys handle prior mandatory updates

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/react-native-code-push#103]
Say the client has version 0.1

I push out 2 updates:
0.2 which is **mandatory**
0.3 which is **optional**

The client opens their app, they see that 0.3 is the latest and greatest... will they see it as mandatory or optional?

**Comment by lostintangent** [comment]
They would see it as optional. The latest release within a deployment always "shadows" any previous updates, including its metadata.

What would your desired behavior be in this scenario? Currently, from the service's perspective, there isn't necessarily a guarantee that 0.3 is actually an incremental change from 0.2 and therefore, carries the same mandatory requirements that it's predecessor did.

I agree that this is an interesting scenario, so I'd love to know more about what you have in mind :)

**Comment by JAStanton** [comment]
IMO if a prior version was mandatory that sets the floor as to the new minimum allowed version. I don't like having mandatory versions trumped by optional versions.

**Comment by nevir** [comment]
@lostintangent how do you envision the mandatory flag being used (in the current mode)?

**Comment by lostintangent** [comment]
We currently think of mandatory as a piece of metadata that we simply round trip to the client and allow the app to enforce that policy however it sees fit. Right now, the only "opinion" that we apply regarding the mandatory flag is that the sync function doesn't add an ignore button to the update prompt, when one is displayed. When using sync for silent updates, or calling checkForUpdate, nothing is done by default when an update is mandatory. The app however could easily choose to modify its behavior in the presence of a mandatory update (e.g. forcibly restart the app immediately, display an "Update required" UI when an otherwise silent update is flagged as mandatory). 

We are absolutely happy to introduce more policy here, we just haven't actually had any requests for it yet. I also fully agree with you that it's weird for an optional update to "neutralize" the mandatory nature of the previous release. I think it makes sense for the server to be smart enough to detect that even though the latest update isn't mandatory, there was a mandatory update that was released since the version you are running, and therefore, "convert" the update to mandatory.

Would that kind of behavior make sense? I wouldn't want to prevent you from releasing an update that isn't mandatory any time there was a previously mandatory one, since if users got all of the updates, it wouldn't make sense to have to keep enforcing mandatory. However, accommodating the non-sequential uodate acquisition scenario definitely deserves a special casing.

**Comment by lostintangent** [comment]
Hey @JAStanton, we discussed this earlier, and we'll plan to make the behavior change that you proposed above, since I agree it makes complete sense. We'll hopefully have it done and deployed next week. Let me know if that sounds good to me. Thanks again for the feedback!

**Comment by ajwhite** [comment]
+1 on this

**Comment by lostintangent** [comment]
This enhancement is now running in production and didn't require any CLI or plugin changes, so it's usable right now :) thanks for the feedback!

**Comment by JAStanton** [comment]
Awesome thanks so much!

**Comment by ajwhite** [comment]
Thanks, very helpful! Nice work
