### ISSUE TITLE
description is empty after patch

### ISSUE THREAD

**Issue by adambene** [Microsoft/react-native-code-push#1039]
### Steps to Reproduce
1. release a bundle (to staging) with no description
2. patch description to any non-empty string

### Expected Behavior
`await codePush.getUpdateMetadata()` returns an object that contains the new description.

### Actual Behavior
`await codePush.getUpdateMetadata()` returns an object with an empty description. The other properties look fine.

`code-push deployment ls MyApp -k` shows the new description. The object described above contains the correct label and deployment key.

### Environment

* react-native-code-push version: 5.1.3-beta
* react-native version: 0.43.2
* iOS/Android/Windows version: iOS 11
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? phisycal

**Comment by max-mironov** [comment]
Hi @adambene, could you please describe how you test this use case?
I've tried it on my own and it works. My workflow is as follows:
1) Release new code-push update with empty description
2) Verify it is empty by viewing release history
3) Patch update with new description
4) Verify it is not empty by viewing release history
5) Verify that description field is showing correctly on my device with `codePush.getUpdateMetadata()` method

So the main point here is that you should 1st patch, then do `getUpdateMeadata`. If you have already downloaded and installed update then you will not see updated description because it was empty at the time you was downloading it.

Please let me know if it helps or if you have any questions.

**Comment by adambene** [comment]
Hi @max-mironov, ah, so the metadata will not be updated on the device.

The update was already installed on the test device.
After making the device re-download the update, the description shows up.

Thanks!
