### ISSUE TITLE
Bad build crash not caught

### ISSUE THREAD

**Issue by monotkate** [Microsoft/react-native-code-push#1057]
I'm trying to test a new version of our update/launch flow and what happens when we have a failed build and how we handle it.  Testing it by pushing a build with an error thrown on initial render.  Expected it to be caught as part of the new build process and return a failed install.  Instead it crashes the app, and rolls back on restart.  Not sure if this is intended behavior, or if we have exception handling misconfigured somewhere.

### Steps to Reproduce
1. Push build to codepush that throws an error on initial render
2. When updating to the new bundle, the app crashes on error
3. After app is restart, it rolls back to the previous bundle

### Expected Behavior
Expected error to be recognized as being thrown inside a not yet fully installed version of the app and caught, returning a failed install.

### Actual Behavior
App crashes and rolls back on restart

### Environment

* react-native-code-push version: 2.1.1-beta
* react-native version: 0.44.3
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment]
Hi @monotkate, thanks for reaching us and sorry for the delayed response. 
The behavior you are experiencing is expected due to one of the following reasons:
1. App crashes after new updated has been applied, so rollback to the previous package is absolutely correct behavior here. 
2. The exception does not crash your app, but [codePush.notifyAppReady()](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushnotifyappready) method has not been called.

Another words, to prevent rollbacks `codePush.notifyAppReady()` method should be called each time after a new update is applied. 

I'm closing this issue for now, please feel free to reopen in case of any questions or issues!
