### ISSUE TITLE
Why android don't have `setDeploymentKey` method?

### ISSUE THREAD

**Issue by hwangjr** [Microsoft/react-native-code-push#1073]
I just found there is a method `setDeploymentKey` in javescript and ios method, but i can't found it in android. can you support it next version ?

>- __(void)setDeploymentKey:(NSString \*)deploymentKey__ - Sets the deployment key that the app should use when querying for updates. This is a dynamic alternative to setting the deployment key in your `Info.plist` and/or specifying a deployment key in JS when calling `checkForUpdate` or `sync`.

**Comment by hwangjr** [comment]
i want to change the deployment key fetched from server, so maybe i just change the `mDeploymentKey` value in [react-native-code-push/CodePush.java at master · Microsoft/react-native-code-push](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java)

**Comment by ruslan-bikkinin** [comment]
@hwangjr thanks for submitting the issue. 

> i want to change the deployment key fetched from server, so maybe i just change the mDeploymentKey value in react-native-code-push/CodePush.java at master · Microsoft/react-native-code-push

You can not do that because `mDeploymentKey` has private access. You can change deployment key on client side using `deploymentKey` option. Please refer to documentation [section](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions) for more information.

In general I think, yes, android SDK lacks of this method and it should be added for consistency purpose. But now we are highly backlogged and can't start working on it right now. We could pick it up when we'll got free time. So if you want this feature be shipped as soon as possible you could make contribution, we will appreciate your help.

**Comment by hwangjr** [comment]
i just recreate the CodePush while i found the code push key has changed.
