### ISSUE TITLE
How do I create two separate apps

### ISSUE THREAD

**Issue by rizwanahmed19** [Microsoft/react-native-code-push#1081]
So I was going through the getting started section and it says that I should create two separate CodePush applications if I wanna target both iOS and Android. What does that mean? How do I create a code push application for each platform?

Sorry for this naive question.

**Comment by Zakeelm** [comment]
It means that if you would like the application you're using CodePush with to target both iOS and Android, we recommend creating two "different" app instances for your app within CodePush. We say this because using the same app for both iOS and Android can cause installation exceptions. This is because CodePush's update packages for iOS and Android will contain different content. In order to create a CodePush app for each platform we recommend using the following commands:
```
code-push app add MyApp-Android android <platform>
code-push app add MyApp-iOS ios <platform>
```

**Comment by rizwanahmed19** [comment]
@Zakeelm Thanks a lot
