### ISSUE TITLE
Update on first download of the app?

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/react-native-code-push#112]
When there is no localpackage, say a fresh install from the app store, will I always download an update on first launch even if I the update would have no changes in it?

**Comment by geof90** [comment]
That will be true if you push the same version of the app both to the app store as well as CodePush. Right now we dont have a mechanism to compare the binary's jsbundle with the one on the CodePush server. However, is there a reason or scenario why someone would push the same version both to CodePush as well as to the app stores?

**Comment by lostintangent** [comment]
Currently, the recommendation is that you don't release to CodePush unless there are actually changes beyond what the associated App Store version already includes. That way, when you bump the version and release to the store, you're end-users won't get an update immediately, since there isn't a release on CodePush targeting the same app version (e.g. 1.0.3). However, if you do iterate beyond the App Store version, and you release to CodePush, your users would get an immediate update if they install it from the store after you released the CodePush update. 

We're discussing a few mechanisms to allow us to identify equivalence between a binary-bundled App Store version and a CodePush version, in the event that you published the same code to both. We just haven't prioritized it due to no one actually requesting it yet. In fact, most people we've talked to liked that they didn't need to release to CodePush in this scenario, since it would be superfluous.

That said, it would be awesome to know if there was a scenario we aren't thinking about (I'm sure there are tons!). Let us know if this is a blocking issue or not.

**Comment by JAStanton** [comment]
I guess I hadn't thought it all the way through, the approach you're suggesting sounds just fine. 

1) With the first build I will push to app store.
2) Then next time I have a hotfix I push a new build to code-push,
3) Once i've done that I bump the version of my app and push to app store w/ code fix in place.
4) While I wait a week for Apple to approve my latest build my users will get the Hotfix nearly immediately via code-push
5) when the next user comes along they will download a build from the app store with the hotfix and there will be no code-push updates waiting for them.

Neat :)

**Comment by lostintangent** [comment]
Exactly right!

**Comment by rhaker** [comment]
Hey, Jonathan.

A few comments/questions:

1) Just stumbled on this recommendation. It makes sense and would probably be an improvement over my setup (which currently has a restart flash for a clean app install). I guess the only thing that makes me hesitate is that when it comes time to do the first codepush, that something (inevitably) would go wrong and the app would crash - without having tested that the actual release works. Of course, I'm sure there are workarounds with setting up a mock codepush and then deleting it...

2)  I originally was looking for a .isFirstRun parameter for sync and couldn't find it. I saw something for .getCurrentPackage and thought I could invoke the client to ignore the update somehow (on the first run when I know the binary is equivalent to the codepush release). Did I miss something here?

3) Is there somewhere where you've got a list of these recommendations? I've seen at least 3 or 4 of these buried in the issues (e.g. rollbacks, android vs ios, first update, etc). And they are all really smart and insightful and time saving. It would be awesome to have these compiled in one place as your current "gold standard" best practices.

Thanks in advance.

**Comment by lostintangent** [comment]
I actually started working on a "release best practices" doc for the website and was planning on finishing/publishing it as soon as I get home from Hawaii :) Apologies for the random tips spread throughout various discussions. We've been trying to improve the docs incrementally along with improving the product, but I definitely have some work to do. I should be able to document all of our current guidance after Christmas when I'm home. 

Regarding your other two questions:

1. Are you using the staging deployment and then promoting successful releases to production? As you mentioned, the plugin does provide "rollback protection" in the event that a broken release goes out and you want to ensure that your end-users are never blocked, but we also always recommend testing each release on the staging deployment and then promoting the tested/successful release to production. That way, you get the high confidence of releasing anything to production, without needing to release directly to it for testing purposes. When you release a new update to the App Store however, you don't need to test that via CodePush, since you just simply rely on users getting that update from the store. 

2. Nope you didn't miss anything! We don't currently have such a mechanism with sync. The isFirstRun property on the LocalPackage object returned from getCurrentPackage simply indicates whether or not the current app session represents the first time the latest CodePush update has actually been run (after the restart applied it). We've discussed adding logic to sync to have it recognize that it's being called within the first run of a new update and short circuiting, but depending on when the update was installed, it's possible that another update has been released, and therefore, we took the conversative route and didn't bake this in.

If you have any feedback/suggestions on how we could make either of these better that would be super valuable. Also, I'd love to know what you're working on if you don't mind sharing :) you can ping me at joncart@microsoft.com anytime. Thanks dude!

**Comment by rhaker** [comment]
Ouch. My bad. Didn't mean to catch you on your break. Please don't read this until you're back...

-------------------------------------------------------------------------------------------------------------------

I'm currently using sync with the immediate install option and no dialog box to the user. Everything is operating as expected (and according to the docs). There are, however, two points that are probably worth providing you with additional feedback, if for no other reason than you asked.

1) Flash on (first) update. I previously submitted to the App Store and they approved the app, but I made some small changes and resubmitted. The current version being submitted has the flash restart on clean install described above. In the future, I can remedy it using your suggested approach.

When I do a future codepush, however, the flash restart will come back and without the dialog telling the user of the update, I'm concerned it will be viewed as a "crash" (even though it's the expected behavior). It's just the cost-benefit tradeoff of me preferring to force the latest version to be installed (with the flash restart) versus waiting until the app is restarted with the typical default behavior of a sync without the immediate install parameter. I'm completely aware that this is something you probably have already thought a lot about and it's probably as optimized as possible.

I haven't thought of how this could be remedied. Ideally there could be a splash screen or loading message or something shown instead of the flash - but I haven't investigated the technical feasibility of this (and it's probably difficult if I had to guess). Same thing with some sort of lazy loading of the bundle - where you essentially have 2 bundles for the app at one time.

Anyway, this is just feedback that's beyond the scope, because (as I said) I'm fully aware that it's the expected behavior. If Apple ever approves the app, I'll let you know so you can see how the flash looks in the actual context of a live install.

2) The second pain point is when the user has a prior app store binary and you essentially lose control of pushing releases. This was on a prior thread. I didn't like the idea of forked deployment. I decided it was just a little too messy for me. Instead, I built a side process that gives me some sort of control when this event occurs. You had mentioned something like this in the aforementioned thread. What I've done is build a check that allows me to (almost) force the user to the app store if I lose control and can't codepush them.  

So those are my 2 points. You guys have done a great job and this is more like how can you make something really good even better. All the basic stuff seems to be handled quite well.

Switching gears, now. I've just about finished with the Android version of the project and I still have some debugging to do with CodePush. If I do a clean init on a blank project, install CodePush, and run, everything works fine. But, if I install CodePush as the last piece to my working project, I'm getting a crash (a NullPointerException).

I need to investigate this further and isolate the exact issue, so I can provide further guidance. For android, I'm using 13 (non-core) modules. I had to write a bunch of custom features like the camera, sms, etc that just didn't exist yet while I was building the app. So my MainActivity is pretty busy and I'm guessing that one of the modules has a conflict somewhere. I just haven't had the chance to replicate the issue to provide you with better color.

Anyway, I hope you had a good break (now that you're back) and I'll let you know what happens with the various items I talked about.

All the best.

**Comment by geof90** [comment]
@rhaker those are definitely very useful feedback! To your point 2), I will be pushing a change that lets the client be notified of new app store versions pushed to CodePush, so that developers can handle the notification by forcing an app store update, for example.

And its a pity that your Android setup has not been smooth. Do provide us with more information when you get it, and we will fix it prompty!

**Comment by Andreyco** [comment]
How about specifying target binary version of pushed update?

1. release 1.0.0 to app store/play store
1. push several updates via code push
1. release 1.1.0 to app store/play store & **patch** latest pushed update to target binary <1.1.0
1. push several updates via code push which targets binary >=1.1.0
1. release 1.2.0 to app store/play store & **patch** latest pushed update to target binary ">=1.1.0 <1.2.0"

Repeat steps 2 and 3 as needed.

The point is to mark latest binary version (which is not known ahead) for already pushed update.

**Comment by karltaylor** [comment]
I just want to clarify the correct process here:

- If I upload a binary to the app store (`1.0.0`). This is what users will receive. And I **should not** push a bundle to codepush.
- Users will download the app and it will open as normal (and not download an update). (`1.0.0`)
- I push a hotfix / new feature to codepush deployment and test (`1.0.1-rc`)
- I promote this bundle to production (`1.0.1`)
- Existing users will receive the `1.0.1` codepush update and download.
- I release to app store (`1.0.1`)
- New users get that version. (`1.0.1`) But will this trigger a download?

**Comment by alexandergoncharov** [comment]
Hi @karltaylor ,

No, this will not trigger a download because all CodePush release have target-binary-version field which indicate binary version for current release. if `1.0.1` binary version try to check update(and you have release only for `1.0.0`) then your app will not be updated.
For more info please check 2 item from this doc:  https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-react-native

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander
