### ISSUE TITLE
Old pendingUpdate with new updated binary

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/react-native-code-push#114]
This might be an edge case but It's worth bringing up. What would happen if I download an app from the app store lets call build A. then I open build A and sometime later I have an update from code-push. the user syncs w/ an install mode of next time the app is opened. I close the app. some time passes before I re-open the app, a new build from the app store is automatically synced from the app store to my phone from apple, this is build B. if I open that app again w/ build b installed. Will that pending update for build A apply to my shiny new build B?

The reason why I ask is because I ran into this while trying to test code-push w/ Fabric / Crashlytics.
I pushed Build A, it opened, downloaded a pending update. I closed the app, without deleting the app I pushed a new build to Fabric, Build B, opened the build and the pending update overwrote my build A.

**Comment by lostintangent** [comment]
I would expect Build B's JS bundle to take effect since the [CodePush bundleURL] method would give it precedence over any previously downloaded CodePush updates. That said, as you mentioned, we aren't clearing out the previous pending update currently, and so there may be some unexpected behavior in this scenario specifically.

This is a good bug report, and it would be pretty straight forward to fix, since we already have logic to detect an App Store update having occurred. Thanks for reporting this!

**Comment by geof90** [comment]
I agree that we should definitely clear older updates and I am working towards a fix for that, but can I confirm that either of you were seeing a bundle downloaded in an older store version being loaded in a new store version? Because that should definitely not happen. Not clearing pendingUpdate information should not lead to this happening either.

**Comment by lostintangent** [comment]
Nope, I wasn't able to repro this issue. I just agreed that we should clean this old state out :)

**Comment by geof90** [comment]
Should we do a check in [CodePush bundleURL] on the saved package appVersion instead of just the date, just to further iron clad ourselves from this issue?

**Comment by lostintangent** [comment]
That sounds good to me. That way the date check helps in scenarios where the version doesn't have to be bumped (e.g. development, Fabric), and the appVersion would be primarily for production scenarios
