### ISSUE TITLE
The unzip process seem has ZipperDown Vulnerability

### ISSUE THREAD

**Issue by shawnXiao** [Microsoft/react-native-code-push#1283]
Security researchers from Pangu Lab, a well-known company that provides iOS jailbreaks, said on Monday that they have found a vulnerability that they believe affects around 10% of all iOS apps.

https://www.bleepingcomputer.com/news/apple/zipperdown-vulnerability-may-impact-10-percent-of-all-ios-apps/

Have a look of Code Push unzip process, it seems have no validate about the folder of the zip file. So the unzip folder may unzip to another folder if the user trust the another HTTPS certificate and then download a third zip file.

### Environment

* react-native-code-push version: 5.3.2

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @shawnXiao ,
Sorry for long delay and yhanks for reporting!

I investigated list of apps which have this vulnerability: https://zipperdown.org/ and I haven't found us there.
So, could you please clarify with more details in which place we have this vulnerability and what is exactly in our module?

Thanks,
Alexander

**Comment by Zakeelm** [comment]
Hey @shawnXiao I'm going to close this for now, but this is something we will definitely keep an eye on going forward. As @alexandergoncharov mentioned, we don't seem to be on that list. Feel free to message back in this thread and we can re-open this accordingly!

**Comment by ejc3** [comment]
We had this show up on a scan from www.securetheorem.com across Verizon Media's codebase. Looking through the code, it doesn't seem to prevent path traversal:
https://github.com/Microsoft/react-native-code-push/blob/3144c916018fab077231e88d8718ad3a1cb0a7d8/android/app/src/main/java/com/microsoft/codepush/react/FileUtils.java#L126

Here's the report:
`Description
Android provides the java.util.zip package, which contains classes such as ZipInputStream that enable an App to read, create and modify ZIP archives. When using this API to unzip an archive, it does not protect against file names in the archive that trigger a path traversal (such as ../..). This allows a malicious archive to overwrite files within the App's container when the archive gets unzipped.
The Zipperdown exploit leverages this issue to potentially allow a remote attacker who has the ability to inject a malicious archive into the App (for example because of unencrypted connections initiated by the App) to overwrite files. Depending on the App's functionality and how the API is being used, it may allow the attacker to perform a remote code execution attack against the App, and thereby get full access to the App's data.
Security concerns regarding the ZipInputStream API have been extensively discussed before, but the Zipperdown research team has released a search engine to expose Apps that are using the ZipInputStream API at https://zipperdown.appscan.io/.
Recommendation
When unzipping an archive, always validate the compressed files' paths and reject any path that has a path traversal (such as ../..). Simply looking for .. characters in the compressed file's path may not be enough to prevent path traversal issues, and a more robust approach is described in the "Secure Code" section below.
Secure Code
The below code snippet shows how to validate an archive to ensure files will not be written outside of the output folder, when unzipping the archive.
static final int BUFFER = 512;
static final long TOOBIG = 0x6400000; // Max size of unzipped data, 100MB
static final int TOOMANY = 1024;      // Max number of files
 
private String validateFilename(String filename, String intendedDir)
      throws java.io.IOException {
  File f = new File(filename);
  String canonicalPath = f.getCanonicalPath();
 
  File iD = new File(intendedDir);
  String canonicalID = iD.getCanonicalPath();
   
  if (canonicalPath.startsWith(canonicalID)) {
    return canonicalPath;
  } else {
    throw new IllegalStateException("File is outside extraction target directory.");
  }
}
 
public final void unzip(String filename) throws java.io.IOException {
  FileInputStream fis = new FileInputStream(filename);
  ZipInputStream zis = new ZipInputStream(new BufferedInputStream(fis));
  ZipEntry entry;
  int entries = 0;
  long total = 0;
  try {
    while ((entry = zis.getNextEntry()) != null) {
      Log.d(LOG_TAG, "Extracting: " + entry);
      int count;
      byte data[] = new byte[BUFFER];
      // Write the files to the disk, but ensure that the filename is valid,
      // and that the file is not insanely big
      String name = validateFilename(entry.getName(), ".");
      if (entry.isDirectory()) {
        Log.d(LOG_TAG, "Creating directory " + name);
        new File(name).mkdir();
        continue;
      }
      FileOutputStream fos = new FileOutputStream(name);
      BufferedOutputStream dest = new BufferedOutputStream(fos, BUFFER);
      while (total + BUFFER <= TOOBIG && (count = zis.read(data, 0, BUFFER)) != -1) {
        dest.write(data, 0, count);
        total += count;
      }
      dest.flush();
      dest.close();
      zis.closeEntry();
      entries++;
      if (entries > TOOMANY) {
        throw new IllegalStateException("Too many files to unzip.");
      }
      if (total + BUFFER > TOOBIG) {
        throw new IllegalStateException("File being unzipped is too big.");
      }
    }
  } finally {
    zis.close();
  }
}
This code snippet is referenced from the CERT Secure Coding Standards.
`

**Comment by Krasavinigor** [comment]
Hi @shawnXiao, @ejc3!

I opened PR for fixing Vulnerability. Could you please take a look if you have time? 
PR link: https://github.com/microsoft/react-native-code-push/pull/1881
