### ISSUE TITLE
Compliance with Google Play policy

### ISSUE THREAD

**Issue by filbertteo** [Microsoft/react-native-code-push#1364]
This project's README states that "Google Play and internally distributed apps (e.g. Enterprise, Fabric, HockeyApp) have no limitations over how to publish updates using CodePush". However, the Google Play Developer Policy Center has the following stated at https://play.google.com/about/privacy-security-deception/malicious-behavior/:

"An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play’s update mechanism. Likewise, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play. This restriction does not apply to code that runs in a virtual machine and has limited access to Android APIs (such as JavaScript in a webview or browser)."

So I would like to check if it is indeed alright to use CodePush for app updates, or is it considered a violation of Google Play's policy, and may result in the app being suspended? Thanks for any insights.

**Comment by filbertteo** [comment]
@alexandergoncharov Thanks! I just wanted to clarify because the statement was kind of ambiguous, as I wasn't sure if the JS V8 engine used by RN is considered a virtual machine. And it sort of has unlimited access Android APIs via the bridge (although said functionality will require native code that accesses the underlying APIs to be present already). Thanks again for your clarification. I will close this issue.

**Comment by phsantiago** [comment]
Guys, take care. Google play removed my app.

Hi Developers at `COMPANY NAME`,

After review, `COMPANY NAME`, `com.company.name`, has been suspended and removed from Google Play as a policy strike because it violates the malicious behavior policy.

An app downloaded from Google Play may not modify, replace or update its own APK binary code using any method other than Google Play's update mechanism.

Next Steps

Read through the Malicious Behavior policy for more details and examples of policy violations.

If possible, make changes to bring your app into compliance. Remember your app must comply with all policies listed in the Developer Program Policies and additional enforcement could occur if there are further policy issues with your apps.
Sign in to your Play Console and submit the policy compliant app using a new package name and a new app name.

Additional suspensions of any nature may result in the termination of your developer account, and investigation and possible termination of related Google accounts. If your account is terminated, payments will cease and Google may recover the proceeds of any past sales and/or the cost of any associated fees (such as chargebacks and transaction fees) from you.

If you’ve reviewed the policy and feel this suspension may have been in error, please reach out to our policy support team. One of my colleagues will get back to you within 2 business days.

Regards,

The Google Play Review Team.

---

They are really ambiguous as @filbertteo said. But one of the firsts sentence of malicious behavior it's:
> An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism.

**Comment by Andriiklymiuk** [comment]
So, as i understand we cannot use codepush on production apps in play market, right?

**Comment by kristijantomic** [comment]
@Andriiklymiuk, is that something new or you have hard time to set it up to run in production?

**Comment by Andriiklymiuk** [comment]
@kristijantomic it is more like play market team suspended app, but it was working properly for long time. Seems play market review issue

**Comment by Andriiklymiuk** [comment]
Seems solved it: if your app is suspended and you upload new version number, make sure to remove old apk from Play store. 
Sorry for disturbing you) 
Great library btw!
