### ISSUE TITLE
The app version format

### ISSUE THREAD

**Issue by gokhanamal** [Microsoft/react-native-code-push#1435]
It is not an issue, it is a feature request. 

I've changed my app version format. I am using version format like yyyy.mm.dd (2018.10.13). The version format easier than major and minor version format to follow the app versions. I am sure a lot of developer use that version format. The app store and google play store are not making any trouble to publish the app with the version format. But when I try to code push with a specific binary version with the version format like 2018.10.13, the codepush returns an error. Is it possible for codepush to support this version format? It is an important feature for my apps because I always use the version format. 

ERROR MESSAGE
Error: Command 'codepush release-react -a ****/***-iOS -m --description Last Release Bug Fix' failed with exception "The "CFBundleShortVersionString" key in the "ios/***/Info.plist" file needs to specify a valid semver string, containing both a major and minor version (e.g. 1.3.2, 1.1).

**Comment by iremlaya** [comment]
+1

**Comment by yuri-kulikov** [comment]
Hi @gokhanamal!
This is a really good approach for naming versions.

I've tested this scenario and found out that versions like `2018.10.10` works properly, but there is a problem when we try to use `2018.10.09`, it's because of leading zero. It's just not valid `semver` version format for and as far we are using `semver` we need to fallow this standard.

There are still ways to use this approach:
- `2018.10.9`
- `20181009`

**Comment by gokhanamal** [comment]
> * 2018.10.9

Thanks! It works 💯

**Comment by yuri-kulikov** [comment]
@gokhanamal Great, you are welcome!
I'll close the issue for now, but if you have any other questions feel free to reopen this issue or open another.

Thank you for using code-push!

**Comment by tdinckaya** [comment]
adding -t <version>
