### ISSUE TITLE
Do not update in ios simulator?

### ISSUE THREAD

**Issue by deju** [Microsoft/react-native-code-push#148]
I added a button in HomeView, and the handler is checking app version.

Just like this:

     CodePush.checkForUpdate()
        .then((update) => {
            if (!update) {
                console.log("The app is up to date!"); 
                that.setState({appinfo: 'up to date'});
            } else {
                console.log("An update is available! Should we download it?");
                that.setState({appinfo: 'an update is available'});
            }
        });

When i release a new app, click the button, the state show "up to date". I tried more then 5 times.

CMD:
    
    react-native bundle --platform ios --entry-file index.ios.js  --bundle-output ./release/main.jsbundle --assets-dest ./release --dev false
    code-push release MyDemo ./release/main.jsbundle 1.0.27

I am confusing.

**Comment by lostintangent** [comment]
Hey @deju, is 1.0.27 the version number that is set in your app's Info.plist file? You need to make sure that the version number you pass to the release command is the exact same version number of the binary you are deploying to. Otherwise, the call to sync won't see the update available.

Additionally, you should be passing "./release" as your update contents when calling the release command since you want to be able to update your assets as well. This wouldn't impact whether your app sees the update or not, but it will be helpful for you moving forward.

**Comment by deju** [comment]
@lostintangent The version in the Info.plist is 1.0.0. Am i change the version to 1.0.27? Are there need i rebuild the app and resubmit to appstore?

**Comment by lostintangent** [comment]
Nope you don't need to change the version in your Info.plist to 1.0.27. You need to run "code-push release MyDemo ./release 1.0.0" instead. As I mentioned, the release command expects you to tell it which **binary** version the CodePush update is for. Since you want it to update 1.0.0, then you need to specify 1.0.0. 

Check out the docs for more detail: http://microsoft.github.io/code-push//docs/cli.html#app-store-version-parameter

**Comment by deju** [comment]
@lostintangent  Ok, it is all right. Thanks.

**Comment by lostintangent** [comment]
Ok cool. I'll close this issue then. Thanks again for trying out the service!
