### ISSUE TITLE
Flow of deployment

### ISSUE THREAD

**Issue by isaaclem** [Microsoft/react-native-code-push#1509]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Create a screen with background red. And push it to production
```
appcenter codepush release-react -a <owner>/<app> -d Production
```

2. Install it in device and made sure it's showing background red.
3. Update codebase to change background to green color. Run the command to push it to production
4. Restart App and making sure it's showing green color.
5. Change the background color back to red. Run command push it to production

> Error: The uploaded package was not released because it is identical to the contents of the specified deployment's current release.

### Environment

* react-native-code-push version: ^5.5.2
* react-native version: 0.57.8
* iOS/Android/Windows version: iOS 12
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device?

**Comment by yuri-kulikov** [comment]
Hi @isaaclem 
Thanks for reporting!

I've tried to reproduce the issue, but everything works as intended. I've recorded the process and you can check it [here](https://msit.microsoftstream.com/video/7e207bad-2851-48da-826f-9a120d238583).

In a few words, `appcenter codepush release-react` command generates a "bundle + assets" package and if this package is the same as the previous CodePush release you will get this error:
```
Error: The uploaded package was not released because it is identical to the contents of the specified deployment's current release.
```
But since we changed our `js` code, the bundle will be different and we shouldn't get this error.

Please let me know if it was helpful for you and ask me if you have any questions!

**Comment by yuri-kulikov** [comment]
Hey @isaaclem,
Sorry for the delay.

> Whether I execute the command appcenter codepush release-react -a <owner>/<app> -d Production before deploying to appstore or after, does it make any changes?

No, it doesn't matter, the app will still try to download the latest version of CodePush update.

**Comment by isaaclem** [comment]
It seems to be working fine. Thanks for your support @yuri-kulikov 

```
const codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESUME
};
```

**Comment by yuri-kulikov** [comment]
Glad to help, thanks for using CodePush!
