### ISSUE TITLE
Second install cannot sync code after the first time choosed install.

### ISSUE THREAD

**Issue by fakefish** [Microsoft/react-native-code-push#152]
I got a problem which is the first time of installed to my phone, it showed install alert and I selected install by using `installMode: codePush.InstallMode.IMMEDIATE` , but I reinstalled it from xcode(it use old code not the released version), it didn't show install alert and the console of xcode shows `[CodePush] App is up to date.`

BTW, this project is awsome!

**Comment by lostintangent** [comment]
This is the expected behavior during debug mode, since the CodePush plugin isn't clearing out old updates on disk, and therefore, the server sees that you already have the latest update. If we cleared the updates in debug mode, without requiring you to also bump the version of the binary every time you ran from Xcode, you would continue to get the same CodePush update prompt every time you ran the app. This would be a pretty bad experience.

If you run the app in release mode, the CodePush updates on disk will be cleared when the plugin discovers a new binary, and you'll get the update again. If this is the behavior you want while debugging, you can change the Xcode scheme to use the release config when you run the app.

This behavior is usually what is most convenience and intuitive for devs, so I'd love to understand what your expected behavior was here. Did you want to keep getting the same CodePush update while debugging? Did you release changes to CodePush that you didn't also make to the JS bundle in your Xcode project?

**Comment by fakefish** [comment]
Thanks for your explain.

For the question, I think it should be getting the same CodePush update while debugging.

**Comment by lostintangent** [comment]
Could you explain why you'd like this behavior? Would it be reasonable for your workflow to just create release builds while debugging to work around this?

**Comment by fakefish** [comment]
I want to see if my app version is older then release version, what the operate flow is.

**Comment by lostintangent** [comment]
Besides running your app using the release config, you can also uninstall the app from the device or simulator, and see the update flow again for debugging purposes. I'd prefer not to change any existing bundle resolution logic unless there is an end-user behavior needed.

In a production app, you would have to bump the app version in order to release a new binary to the store, and therefore, any existing CodePush releases wouldn't be available unless you released a new update that targeted the new binary version. The scenario you're mentioning would only happen during debugging, so I'd love to see whether the existing workarounds I mentioned above would satisfy your diagnostic needs without us needing to change any production behavior.

**Comment by fakefish** [comment]
Thanks, I have already do in this way.
