### ISSUE TITLE
RnKeyChain Error

### ISSUE THREAD

**Issue by rohit95kumar** [Microsoft/react-native-code-push#1532]
Hi,
I am having problem when running RN app in my device.
MY env is: android studio 3.2
RN-0.55
Keychainmanager-3.0

i am building my app and everything is fine. but when i am logging in m y application by entering username and password i am getting the following error:
<img width="280" alt="screen shot 2019-02-26 at 1 16 09 pm" src="https://user-images.githubusercontent.com/48009151/53395914-1d0b4b80-39c9-11e9-9660-92689a1119f1.png">

please help me out on this one ASAP

**Comment by alexandergoncharov** [comment]
Hi @rohit95kumar,
Thanks for reporting!

Could you please ensure that this issue is from CodePush plugin? You can just remove this plugin and try to run your app again.

**Comment by rohit95kumar** [comment]
hi alexander,
i tried your suggestion but it does not seems  to work. Also i need code-push so i cannot proceed without codepush if it had worked.  i cannot resolve this issue as i am unable to figure out where the issue is.

**Comment by alexandergoncharov** [comment]
@rohit95kumar, yeah, I understand it. I mean that we should to ensure that this issue is not from CodePush plugin. Possible there is some other issue as I don't see any CodePush files in logs.
If you remove CodePush plugin and successfully log in without issue I think in this case CodePush affect some parts. But at first we should ensure it.

**Comment by rohit95kumar** [comment]
changing the port number under edit  run configuration  to 9090 seems to solve this issue. i simply did npm run build after  changing the port number and replicated the scenario. it worked.
