### ISSUE TITLE
No property named "" exists in the "android/gradle.properties" file

### ISSUE THREAD

**Issue by DavideValdo** [Microsoft/react-native-code-push#1559]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Expected Behavior
Release is completed as always 
### Actual Behavior
See screenshot

<img width="1012" alt="Screenshot 2019-04-04 at 21 09 47" src="https://user-images.githubusercontent.com/26572302/55581846-2e5d1b80-571e-11e9-9984-afbb6802cf34.png">

**Comment by DavideValdo** [comment]
I had to set `versionName`  that was previously `""` inside `app/build.gradle`
```
defaultConfig {
    applicationId "com.happyin.original"
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
    versionCode 17
    versionName "1.1"
```

**Comment by alexandergoncharov** [comment]
Hi @DavideValdo ,
Thanks for reporting!

Yeah, That's because `realease-react` uses `versionName` for setting `--target-binary-version` field. So, for fixing this issue you should just add correct `versionName`(as you did) or just provide `--target-binary-version` manually. All CodePush releases should have `target-binary-version`

Please let me know if it was helpful and feel free to ask any questions.

**Comment by alexandergoncharov** [comment]
Hi @DavideValdo ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
