### ISSUE TITLE
After CodePush update, Even when user installs older build from app store he is getting latest version of code which provided earlier through codepush.

### ISSUE THREAD

**Issue by ashokrse2020** [microsoft/react-native-code-push#1575]
### Steps to Reproduce
1. we have given native build and published to app-store say the version is v1.0
2. now codepush build is published v1.1
3. user installed codepush build and he is using v1.1.
4. now he wants older build v1.0 so without deleting app from mobile device he will go to app-store and install the older version of app which is v1.0
5. But he still gets v1.1

### Expected Behavior
1. we have given native build and published to app-store say the version is v1.0
2. now codepush build is published v1.1
3. user installed codepush build and he is using v1.1.
4. now he wants older build v1.0 so without deleting app from mobile device he will go to app-store and install the older version of app which is v1.0
5. But he still gets v1.1

is this expected?

### Environment

* react-native-code-push version:
```"react-native-code-push": "5.5.2"```
* react-native version:
```0.57.8```
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?
```tested only on device```

(The more info the faster we will be able to address it!)

**Comment by AshokICreate** [comment]
```since codepush binary version is locally available is it taking local binary version of the app.```

**Comment by yuri-kulikov** [comment]
Hi @AshokICreate,
Thanks for asking!

There's a difference between the application version and react-native bundle version.

### For example:
1. The user downloads some app from the app-store, its version (**v1.0** for example) is the application version. And it has built-in js code (react-native bundle), we can call it a **"binary bundle"**.
2. The user then downloads a CodePush update. Version of the app and its native part is still **v1.0**, the app will just use this **CodePush js bundle** instead of **binary bundle**.
3. If user reinstalls the app, he will lose this downloaded CodePush bundle and app will use inbuilt js code (**binary bundle**) until application downloads and installs the CodePush update again.

**Comment by AshokICreate** [comment]
sorry for late reply i was sick and out of office for few days. @yuri-kulikov thanks for the nice explanation. The issue is after update from app-store it still uses **CodePush js bundle** instead of **binary bundle** .

**Comment by yuri-kulikov** [comment]
@AshokICreate sure, don't worry 🙂
Please let us know when you recheck this.

**Comment by yuri-kulikov** [comment]
@ashokrse2020 Just a friendly ping 🙂

**Comment by yuri-kulikov** [comment]
@ashokrse2020 We haven't heard from you in a while, unfortunately. I'm going to close this issue for now but please let us know if you still need our help, feel free to reopen the issue if needed!

**Comment by pianoman730** [comment]
I want to actually clarify for anyone else that may be coming here with a similar question. So the expected behavior is this:
1. App is uploaded to the app store/play store codepushified 
2. User downloads the app that doesn't have the codepushed updates
3. On first launch, the app downloads said updates
4. On next launch, those updates are applied

So no matter what, the version that you codepush to will always download the updates immediately after the user downloads that version from the app store/play store. Correct?
