### ISSUE TITLE
CodePush Sync Error in React Native Android

### ISSUE THREAD

**Issue by arjunkomath** [Microsoft/react-native-code-push#160]
On component mount I have given the following command:

react-native: 0.17.0
Android 6.0.1

```
CodePush.sync({ updateDialog: true, installMode: CodePush.InstallMode.IMMEDIATE });
```
It throws an error:
```
Unable to show dialog, main activity is not a FragmentActivity
```

**Comment by lostintangent** [comment]
Hey @arjunkomath! On Android, we use to require that your main Activity class inherit from FragmentActivity in order to display the update dialog. To fix this, you can do one of two things:

1. Upgrade your RN plugin to the latest release (1.6.0-beta), which removes this restriction

2. Make your MainActivity class inherit from FragmentActivity. Our docs explain how to do this in the Android setup section.

Let me know how it goes!

**Comment by arjunkomath** [comment]
@lostintangent It worked :) I went with first method and updated to 1.6.0-beta. Thank you!

It would be great if you could mention this in the documentation for ```codepush.sync()``` https://github.com/Microsoft/react-native-code-push#codepushsync

**Comment by lostintangent** [comment]
Yay! Thanks for pushing through this issue. I'll update the docs per your suggestion. Let us know if you hit any other issues!
