### ISSUE TITLE
react-native 0.60.3 hermes support for android

### ISSUE THREAD

**Issue by xDAnkit** [microsoft/react-native-code-push#1626]
react-native introduced **hermes** for **android** . When you guys are planning for supporting **RN 0.60.3**. Since as per Team FB they have migrated the JavaScript engine to **hermes** and mentioned that the code generation and compilation is being done at build side.

**Comment by jstheoriginal** [comment]
Does CodePush still work if you enable Hermes? I would expect there’s still a jsbundle with Hermes...it’s just not optimized if a CodePush jsbundle were to be installed afterwards, correct?

Is this ticket just asking for CodePush to optimize the CodePush jsbundles with the Hermes engine?

**Comment by usrbowe** [comment]
I guess the end goal of "supporting Hermes" is to introduce bytecode compilation option for Android codepushes and server that file OTA.
But I assume, current jsbundle will work, but just not gonna benefit from. I'll test this assumption soon.

**Comment by xDAnkit** [comment]
> Does CodePush still work if you enable Hermes? I would expect there’s still a jsbundle with Hermes...it’s just not optimized if a CodePush jsbundle were to be installed afterwards, correct?
> 
> Is this ticket just asking for CodePush to optimize the CodePush jsbundles with the Hermes engine?

Yes, Wanted to know that whether do we need to wait for new updates on codepush to support hermes.  Or the current version will support it.

Since as i read hermes docs the whole engine is getting replaced it. and instead of packaging bundle the android code will push optimized bundle.

**Comment by iit2008047** [comment]
would really love the  hermes support!

**Comment by eggli** [comment]
Hey folks, I've just opened a PR to support Hermes form the CLI level, no code has to be modified from the client side to support Hermes, feel free to comment on my PR, thanks.

**Comment by eggli** [comment]
The PR to support Hermes from CLI level got merged, I think we can close this issue for now.

**Comment by jstheoriginal** [comment]
Greatly appreciate your contribution to get this in, @eggli!

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue for now as PR was merged. Thanks @eggli !
Please feel free to reopen it if you have any questions.

**Comment by luatnd** [comment]
Which cli version contain above merge request?
I cannot see any log relate to hermes.

My cmd:
```
appcenter codepush release-react -a <my_app> -d Production  -t 3.0.0 -x
```

My system:
```
npmPackages:
  react: 16.9.0 => 16.9.0 
  react-native: 0.61.5 => 0.61.5 
 npmGlobalPackages:
  create-react-native-app: 3.2.4
  react-native-cli: 2.0.1
  react-native-create-library: 3.1.2
```

**Comment by kaushikwavhal** [comment]
> Hi all,
> 
> I'm going to close this issue for now as PR was merged. Thanks @eggli !
> Please feel free to reopen it if you have any questions.

Can anyone please share the link to the PR which was merged? i am unable to find anything related to hermes in the documentation of codePush. The bundles being uploaded to appcenter are still plaintext JS bundles.

**Comment by rocwind** [comment]
> > Hi all,
> > I'm going to close this issue for now as PR was merged. Thanks @eggli !
> > Please feel free to reopen it if you have any questions.
> 
> Can anyone please share the link to the PR which was merged? i am unable to find anything related to hermes in the documentation of codePush. The bundles being uploaded to appcenter are still plaintext JS bundles.
> Is there a secret flag to enable hermes compilation before upload?

https://github.com/microsoft/appcenter-cli/pull/627

**Comment by yaronlevi** [comment]
@rocwind 

We are at the same problem here

react-native @ 0.63.3
react-native-code-push @ 6.4.0

How can we tell the Codepush CLI to produce a JS bundle that is compatible with Hermes?

**Comment by rocwind** [comment]
> @rocwind
> 
> We are at the same problem here
> 
> react-native @ 0.63.3
> react-native-code-push @ 6.4.0
> 
> How can we tell the Codepush CLI to produce a JS bundle that is compatible with Hermes?
@yaronlevi 

I think It's the code-push-cli version matters:
- if you are using the latest version of appcenter-cli, [it should be able to check about the Hermes enabled or not (from gradle or pod file) and compile the bundle to Hermes binary accordingly without additional setup](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/codepush/lib/react-native-utils.ts#L486)
- if the gradle/pod file is not at their defaullt location - `android/app/build.gradle`/`ios/Podfile` - in you RN project, you may need to add extra args to the e cli command: [`--gradle-file`/`--pod-file`](https://github.com/microsoft/appcenter-cli/blob/master/src/commands/codepush/release-react.ts#L48)
- if you are looking for [legacy code-push-cli package](https://www.npmjs.com/package/code-push-cli), it doesn't support Hermes since it's deprecated before Hermes landed at RN. To work with a self host server, we have a fork [`@shm-open/code-push-cli`](https://www.npmjs.com/package/@shm-open/code-push-cli) with Hermes support back ported from `appcenter-cli` may help.

**Comment by yaronlevi** [comment]
@rocwind Thanks for the help! We will try to make it work...
