### ISSUE TITLE
Android: Codepush pending in State [CodePush] Downloading update 

### ISSUE THREAD

**Issue by digital-tcbs** [microsoft/react-native-code-push#1707]
Hi, i have issue on android when user download update. Codepush pending very long time before start download update. This pending in state: [CodePush] Downloading update. It take 5 min to start download.
In IOS it very fast, take 30s to start.
Pls help. Thank

**Comment by alexandergoncharov** [comment]
Hi @daniel-beard,
Thanks for reporting!

Possible this issue is occured because we were updating server side of CodePush. Sorry for that 😞 
It works correctly now for my test project.

I'm going to close this issue for now. Please feel free to reopen it if you any questions or if you faced this issue again.
