### ISSUE TITLE
XCode11 can not find "Build Location -> Per-configuration Build Products Path -> Staging "

### ISSUE THREAD

**Issue by whereiscode** [microsoft/react-native-code-push#1782]
XCode11 can not find "Build Location -> Per-configuration Build Products Path -> Staging "

### Environment

* react-native-code-push version:6.0.0
* react-native version:0.61.5
* iOS/Android/Windows version:IOS
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by hemith** [comment]
me too. "Build Location -> Per-configuration Build Products Path" is not exist...

**Comment by hemith** [comment]
It works.

Basically, follow this doc.
https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md
1.
2.
3.
4.
5.
6.
7. Add **CONFIGURATION_BUILD_DIR** using "Add User-Defined Setting" in Build Settings
instead of **Per-configuration Build Products Path**
8.
9.
10.
11. pod install
12. set post install - https://github.com/Microsoft/react-native-code-push/issues/426

in Xcode Help Document (Xcode Help in xcode menu) 

> Per-configuration Build Products Path (CONFIGURATION_BUILD_DIR)
> The base path where build products will be placed during a build for a given configuration. By default, this is set to $(BUILD_DIR)/$(CONFIGURATION).

**Comment by yuri-kulikov** [comment]
Hey @whereiscode,
Sorry for the delay.

I hope @hemith answere helped you, so I'll close the issue for now, but if you still have any questions, feel free to reopen it.

**Comment by 3DEsprit** [comment]
Are there plans to revise the [multi-deployment documentation](https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md) to mention this update for XCode 11?

**Comment by sinn1** [comment]
Had to add the values for Debug, Release and Staging before setting the name to 'CONFIGURATION_BUILD_DIR' otherwise XCode would crash. I think it didn't like empty values.

Debug + Release: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)

As per docs:
Staging: $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)

**Comment by natuanorg** [comment]
@sinn1 thank you

**Comment by erez-guesty** [comment]
@hemith 
About step 12. set post install - #426
inside this PR (#426 ) they instruct to add a snippet to Podfile
with the config key `CONFIGURATION_TEMP_DIR`
But i don't see any related to this key in the `Build Settings`...
Should it be added??

**Comment by hemith** [comment]
@erez-guesty 
Skip Step 12. It is not necessary.

**Comment by walterwing** [comment]
For people who also need to update Pod dependencies but couldn't use `pod install` for whatever reason, have a try to update `PODS_CONFIGURATION_BUILD_DIR` under "Build Settings" -> "User-Defined".

Similar like what you did for `CONFIGURATION_BUILD_DIR `, update the value for your new config as: `${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)`

**Comment by MyrkaLarios** [comment]
> Had to add the values for Debug, Release and Staging before setting the name to 'CONFIGURATION_BUILD_DIR' otherwise XCode would crash. I think it didn't like empty values.
> 
> Debug + Release: $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
> 
> As per docs:
> Staging: $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)

Our project didn't crash, but it was having some build issues. Specifically this error: `Library not found for -lPods-App`, this fixed it.
