### ISSUE TITLE
Android code push successful  for release package(production  environment)is not dialog show, but debugger show

### ISSUE THREAD

**Issue by maoyuhu** [microsoft/react-native-code-push#1919]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

When I released the online version of the production of hot update, the app does not pop-up prompt to upgrade, but when I connect phone to PC in debugging, I posted online hot update tip plays the window, I checked the configuration of the I have no problem, we are your build server, I cheked my deployment key,it is all right, what should I do?

### Environment

* react-native-code-push version-6.2.1
* react-native version-0.62.1
* iOS/Android/Windows version-android-9
* Does this reproduce on a debug build or release build?---release build
* Does this reproduce on a simulator, or only on a physical device? ---physical device

**Comment by andreidubov** [comment]
Hi @maoyuhu 
Thanks for the reporting.

Unfortunately, I don't have enough information to reproduce the issue, I tested the standard case for react-native-code-puhs with a dialog example from the documentation and it works as expected in both release and debug.

Could you please provide more information so that I can reproduce this issue locally such as:
* How did you set up react-native-code-puhs in your project?
* Steps to reproduce the issue, or what steps do you take to run the application.
* Logs of your device (it will be marked as [CodePush]).

If possible could you please provide a test project with the issue.

**Comment by maoyuhu** [comment]
Hello, the author
I've already solved the problem
It's because I'm using android version 9.0
The server was built by ourselves, it was the HTTP protocol, and I didn't pay attention to this at first, but finally I added a configuration that supported the HTTP protocol to the configuration and it was fine. Thank you very much
