### ISSUE TITLE
"Error -- "Deployment "Staging" does not exist."

### ISSUE THREAD

**Issue by Yandamuri** [microsoft/react-native-code-push#1969]
I ran following command without specifying the deployment environment

     appcenter codepush release-react -a syam-growsmartsmb.com/smartfsm-android

then i got following error

     Command 'codepush release-react -a syam-growsmartsmb.com/smartfsm-android' failed with exception "Error "Unexpected token D in JSON at position 0" occurred in deserializing the responseBody - "Deployment "Staging" does not exist." for the default response."

### Steps to Reproduce
1. Please run above command in project folder

if we don't specify the deployment environment, will it point to staging environment by default?

**Comment by andreidubov** [comment]
Hi @Yandamuri 
Thanks for your reporting!

According to the documentation [here](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#deployment-name-parameter):

`This parameter specifies which deployment you want to release the update to. It defaults to Staging, but when you're ready to deploy to Production or one of your own custom deployments, just explicitly set this argument.`

You can create a deployment named Staging, in this case, you don't need to specify the deployment name at release. Otherwise, add the -d <deploymentName> flag to the command.

I'm going to close this issue, for now, please feel free to reopen it if you have any questions.

**Comment by brkylmz7** [comment]
running the command "appcenter login"  and try again

**Comment by mujehoxe** [comment]
Tried adding -d with no hope

**Comment by DmitriyKirakosyan** [comment]
Hi @mujehoxe , make sure the deployment exists on App Center, the user you log in with has required permissions. Try using full argument name `--deployment-name`.
