### ISSUE TITLE
Deployment scenario and version mismatch

### ISSUE THREAD

**Issue by nicinabox** [Microsoft/react-native-code-push#201]
Hey folks, can you help me understand this better?

Scenario:

2.0.0+110 latest available on code push
2.0.0+111 latest available on hockeyapp

After installing the 2.0.0+111 binary the app reports 2.0.0+110 is installed (double checked the binary, it's bundled with the right code/version). I have code push configured to install on resume.

---

It looks like code push works strictly off of `CFBundleShortVersionString`. I believe hockeyapp looks at the build number to determine if an update is available.

Is there some way to configure this behavior to have a standardization between deployment services? What's the best way to handle this?

**Comment by lostintangent** [comment]
Hey @nicinabox! When you say that the binary reports that 2.0.0+110 is installed, do you mean that it discovers that update on the server and downloads/installs it? Despite the fact that in your case, that isn't desired?

As you mentioned, this behavior would be currently expected based on the fact that CodePush is seeing that there is an update available for the running binary version. If you had changed the version to 2.0.1 then you wouldn't have seen that behavior. 

We're actually in the process of trying to improve the integration between CodePush and HockeyApp, and this is one area where it's less than ideal. There isn't really a great workaround for now other than to bump the CFBundleShortVersionString when you release an update to HockeyApp.

In non-production scenarios (as well as with TestFlight), this version strong has to be bumped, so this issue only ends up happening with "beta stores" like HockeyApp or Fabric.

One possible solution would be to allow specifying the build code/number when releasing an update via the CodePush CLI, which we could use to further determine whether there is an update or not.

Thoughts?

**Comment by nicinabox** [comment]
> When you say that the binary reports that 2.0.0+110 is installed, do you mean that it discovers that update on the server and downloads/installs it? Despite the fact that in your case, that isn't desired?

That's correct.

> If you had changed the version to 2.0.1 then you wouldn't have seen that behavior.

That was my conclusion as well. The awkward thing that that we're actually "targeting" 2.0.0 as this release. It's a rewrite with many pre-2.0.0 builds. Even after we start doing semver bumps there might be situations we're it's ideal to only bump the build and not the version (eg, we add someone to the provisioning profile and release the binary again)

> One possible solution would be to allow specifying the build code/number when releasing an update via the CodePush CLI

This could work. I'd be happy to more specifically qualify my version with build info.

**Comment by lostintangent** [comment]
Totally understood. From that perspective, we absolutely need to lift the requirement for bumping the semver string to better enable using CodePush during beta testing. Here is a little more detail around what we could do to accommodate this scenario:

1. Update the CodePush plugin to begin sending the build number to the server (in addition to the semver string) whenever it does an update check. This way, the server knows the exact binary that the client is running, and can make a more informed decision about whether it needs an update or not.

1. Update the CodePush CLI's `release` command to allow optionally specifying a build number to associate with a release (e.g. `code-push release Foo ./release 2.0.0 --build 45`). This would allow targeting a CodePush release at a specific binary version, when using the build number as the level of granularity instead of the semver string.

1. Update the CodePush server to look for the presence of a build number on a release, and use it to inform whether the inquiring client should receive the update or not. If a release doesn't have a build number, or the client doesn't send one, then the existing behavior will kick in. If the release and client have a build number, then the client will only receive the update if they are running the exact same combination of semver and build code (e.g. `2.0.0 (45)`). Otherwise, they will not receive the update, assuming that a newer build code has newer bits, and an older build code wouldn't be compatible.

1. Update the CodePush CLI's `deployment h` and `deployment ls` commands to display the build number value for releases that included one (e.g. the `App Version` column would display the value `2.0.0 (45)`).

1. Update the CodePush CLI's newly create `release-react` command (not shipped yet) to infer the build code automatically and supply it as part of the release. This way, you don't have to actually do anything extra to ensure this scenario works.

Thoughts? There may be some details missing here, but in general, this direction seems reasonable.

**Comment by lostintangent** [comment]
@nicinabox I actually realized there is another solution that you could use. You can bump the version of your app by appending a pre-release tag, and then using that to target your CodePush releases. So for example, if you update your `Info.plist` file to be `2.0.0-1`, and call `code-push release APP CONTENT 2.0.0-1`, that would work, without requiring you to touch the major/minor/patch version. This is effectively performing the same function as the build number proposal above, but this would actually work right now to unblock you.

What do you think?

**Comment by nicinabox** [comment]
Actually that might work. I'll have to make some adjustments in our build system to make sure tags and changelog happen correctly, but this might be viable. I'll see if I can try it before the end of the week. :+1:

**Comment by lostintangent** [comment]
OK cool. Let us know :) Thanks!

**Comment by jeanregisser** [comment]
@lostintangent interesting workaround indeed!
One drawback though is we lose the ability to promote versions between Staging and Production. The promoted versions wouldn't be picked up by the Production build since its version wouldn't match, am I correct?

**Comment by nicinabox** [comment]
Ah good point. That's probably not a dealbreaker for us since our Staging builds use a different api endpoint and may have some prerelease features enabled that we don't want in our production build.

**Comment by geof90** [comment]
It would be pretty simple for us to make a mechanism that allows users to change the app metadata during a promote. e.g.

`code-push promote sourceDeployment targetDeployment --targetBinaryVersion 2.0.0 --description --mandatory false`

**Comment by lostintangent** [comment]
@geof90 Yeah I definitely think we should expand he promote command to allow modifying metadata along with the release copy

**Comment by lostintangent** [comment]
@nicinabox Did this solution end up working out as a workaround for you?

**Comment by nicinabox** [comment]
I've been pretty heads down shipping this week (and with code-push!). Right now I've talked with the people who had issues with the version mismatch and got folks up to speed with the right binaries. It hasn't been an issue again (we had very few binary builds though), but I think I'll start adding the build number as a pre-release number until something more official or configurable is available.

Thanks @lostintangent and @geof90 for your support!

**Comment by lostintangent** [comment]
Thanks for the confirmation @nicinabox! Let us know if you hit anything else :)
