### ISSUE TITLE
Apple's review was rejected

### ISSUE THREAD

**Issue by leejnull** [microsoft/react-native-code-push#2013]
Hello, 

Thank you for your reply. 

We continue to find that your app contains hidden features or functionality that can change the behavior of the app after review. To resolve this issue, it would be appropriate to ensure that all features and functions in the app are visible and fully accessible during review.

**Comment by caolong0204** [comment]
so luck i has passed review

**Comment by dylan-westbury** [comment]
I have just read the App Store Guidelines, I wonder if this means we can't add codepush to apps from now? It doesn't mention bug fixes though. 

2.5.2 Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps. Educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code provided that such code is not used for other purposes. Such apps must make the source code provided by the Application completely viewable and editable by the user.

**Comment by ktomi42** [comment]
@dylan-westbury it would be strange because there a tone of react native apps that uses "update over the air" to fix bugs. 
As the docs say:  "nor may they download, install, or execute code which introduces or changes features or functionality of the app". We should only fix bugs and submit them to the store for review as soon as possible. Also, there is the possibility to make an expedited review request if they see feet to approve it :)

**Comment by dylan-westbury** [comment]
Yeah I agree @ktomi42, I am assuming OP may have hidden featured that Apple wasn't able to review hence the rejection, not appcentre code push.

**Comment by leejnull** [comment]
I removed the code push, but it was still rejected. I think it might be caused by the computer review of Apple, so I lodged an appeal and I was approved.

I'll try again next time
