### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by tristangodfrey** [Microsoft/react-native-code-push#206]
Took me a little while to figure out how to find my deployment keys, turns out that I need to add the `--displayKeys` flag to the `code-push deployment ls` command. Maybe this should be added in the readme?

**Comment by lostintangent** [comment]
Ah yeah good catch. We recently made the change to hide the key by default since it took up a lot of screen real estate and isn't needed frequently. I just updated the readme to include the "-k" flag within the instructions on how to retrieve the key. Let me know if you think that is sufficient or if we need to add more detail. Thanks!

**Comment by tristangodfrey** [comment]
Perfect! 👍
