### ISSUE TITLE
Only the first check and update successfully execute

### ISSUE THREAD

**Issue by raen79** [microsoft/react-native-code-push#2061]
Hey everyone,

We are running into an issue that we cannot solve. After installing our app that has codepush installed on an iOS device, the first update happens perfectly. However, if we push another update to codepush, and restart the app, we get the data integrity check error. We have no `.DS_Store` files or file names with foreign characters in them. So we don't really know what else we can look at to solve this.

### Steps to Reproduce
1. Install an app with codepush set up.
2. Push an update to codepush.
3. Open the app
4. Restart the app and allow the codepush update to install
5. Push a new update to codepush
6. Restart the app

### Expected Behavior
What you expected to happen?

Codepush downloads the update and installs it

### Actual Behavior
What actually happens?

[javascript] [CodePush] Checking for update.
2021-04-01 18:07:27.985351+0200 paters_rn[62827:6524162] [javascript] [CodePush] Downloading package.
2021-04-01 18:07:28.384039+0200 paters_rn[62827:6534108] [native] Sending `CodePushDownloadProgress` with no listeners registered.
[CodePush] Applying diff update.
[CodePush] Verifying hash for folder path: /Users/eranpeer/Library/Developer/CoreSimulator/Devices/206E0D93-38F4-4273-A468-D05FC0D84BDE/data/Containers/Data/Application/BD5B1BAE-7B46-488D-AFF8-003FB6EE10CA/Library/Application Support/CodePush/401429e0ef823eb3ef4f091553ade7fce228120ac195ddc3dcfd18ca4e99e2d9
[CodePush] Manifest string: (
    "CodePush/main.jsbundle:e2abe4e022d9699100ad1322a9792e47984c3a66e9cecbc9ad2c7da8c5acde54",
    "CodePush/assets/locales/en.json:7f9e37482cecda411947d763d2486775b6fb0e590770469207a672a787123db3",
    "CodePush/assets/app.json:590f86d6cd11f7aadcbbbd3b368307878c420dc609ed10f0350a70ec82721d0e",
    "CodePush/assets/node_modules/react-native/package.json:0087a3a7be0dd03690b6c32626875ac2db1b5b19f4fa2e78f35e15bcb1e92057",
    "CodePush/assets/node_modules/css-color-keywords/colors.json:354f1816e82e3aa407d5493a59ff75f6d073d18e39db48e792b3bde951419ff5",
    "CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@3x.png:3ddd0773ed27e23d25789f301731b3ac455ad8be5aa27a0a1b838f89c6d27225",
    "CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@2x.png:2b7443a9a58e92ca11a575bdc11598615a57dde305cd8ce70d602606b302cd98",
    "CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon.png:2cdfeb8e5ccde7976f7012fb8cce73
[CodePush] Expected hash: 401429e0ef823eb3ef4f091553ade7fce228120ac195ddc3dcfd18ca4e99e2d9, actual hash: ac957e370d67678f22e843ccd046f1bed67ebe100e62ae56844d8a77822048b6
[CodePush] The update contents failed the data integrity check.
2021-04-01 18:07:28.963611+0200 paters_rn[62827:6524162] [javascript] [CodePush] An unknown error occurred.
2021-04-01 18:07:28.963829+0200 paters_rn[62827:6524162] [javascript] [CodePush] The update contents failed the data integrity check.

### Environment

* react-native-code-push version: 7.0.0.0
* react-native version: 0.63.3
* iOS/Android/Windows version: iOS 14.4
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by raen79** [comment]
This PR fixes the problem for me: https://github.com/microsoft/react-native-code-push/pull/2078

**Comment by AndriyZahura** [comment]
In case someone is still having the same issue:

I had it on android after messing with gradle/modules/caches etc.

The flow was the following:
Install the binary;
Get ANY update;
Try to get another update;
The `The update contents failed the data integrity check` error in logcat appears.

What helped me is simply adding this before my sync:

   `if (Platform.OS === 'android') { CodePush.clearUpdates(); }`

Before that, I checked if there is an available update. So whole code looks like this

`
updateApp = () => {
this.props.setCodePushUpdateAvailable(false);
if (this.props.codePushUpdateInstalled) {
CodePush.restartApp();
return;
}

//Need to clear previous cache because android may rollback.
//TODO: Test if we need this on the next binary release
if (Platform.OS === 'android') {
  CodePush.clearUpdates();
}
const installMode = CodePush.InstallMode.IMMEDIATE;
CodePush.sync(
  {
    installMode,
  },
  this.codePushStatusDidChange.bind(this),
  this.codePushDownloadDidProgress.bind(this),
);
};
`
updateApp is called manually by user
