### ISSUE TITLE
[CodePush] Error in getting binary resources modified time

### ISSUE THREAD

**Issue by duduccosta** [microsoft/react-native-code-push#2116]
### Environment

* react-native-code-push version: ^7.0.1
* react-native version: 0.63.4
* iOS/Android/Windows version: android
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? physical

I'm using the manual codepush feature.
When I use codepish.sync and debug the update status, i'm getting, in this order:

5 - CHECKING_FOR_UPDATE
7 - DOWNLOADING_PACKAGE
3 - UNKNOWN_ERROR

And codepush write a log as: [CodePush] Error in getting binary resources modified time.
I've done everything correctly.
I already done: 'apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"'

My App function export is:

```
export default codePush({
  checkFrequency: codePush.CheckFrequency.MANUAL,
})(App);
```

The JSON return from codePush.checkForUpdate() is:

```
{"appVersion": "1.9.7", "deploymentKey": "kfdrypCpPM2Fwrxxxxxxxxxxxxxxxxxxx", "description": undefined, "download": [Function download], "downloadUrl": "https://codepushupdates.azureedge.net/storagev2/o18eq876vfGurGa9Cvw-y9UyJ63c16557b36-3083-4e3a-beb9-e72966af037a", "failedInstall": false, "isMandatory": false, "isPending": false, "label": "v1", "packageHash": "87275c31db786998be820b006acaadfae9ddb6ced6d4f14bab734c397295643a", "packageSize": 2945614}
```

Need help, please.

**Comment by adsalihac** [comment]
same issue existing my project

**Comment by olbesp** [comment]
@duduccosta, @adsalihac have you already fixed your issues?

I had the same issue. In my case, the reason was that the AppCenter somehow cached the wrong (outdated) config. I changed CodePush deployment keys and reuse the same public/private `.pem` code signing keys for a different project.

Then I checked both platforms and the Android issue was exactly this one:
`[CodePush] Error in getting binary resources modified time`

But I had a different issue on iOS:
`[CodePush] The operation couldn’t be completed. (OSStatus error -67808 - RSA signature verification failed, no match)`

Then I regenerate my `.pem` signing keys (in my case it's the new project, so I don't care about supporting some versions with existing keys and code signing) and "Save" branch configuration one more time and build it.

Now everything is OK with code signing, deployment keys, and CodePush bundles.

**Comment by 0x0a0d** [comment]
bump. same here

**Comment by gax97** [comment]
Experiencing this issue as well.

**Comment by mattwoberts** [comment]
I'm also seeing this... For me it's working in IOS but I'm seeing the exact same issue in Android, and the same sequence of logs as originally reported

**Comment by Cado21** [comment]
where's the discussion on this problem?

**Comment by lelukas** [comment]
I'm getting the same error. @hiunguyn workaround worked for me.

**Comment by lelukas** [comment]
By the way @hiunguyn, why don't you want to use this anyway? Is there a downside or limitation this resValue introduces?

**Comment by mateusdegobi** [comment]
> @duduccosta adicione isso em android -> defaultConfig `resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())` o problema resolvido, mas não quero usar isso , preciso de outra maneira :(

That's soluction by [PR #1961](https://github.com/microsoft/react-native-code-push/issues/1961#issuecomment-710698621).
Between, this is worked for me. 🚀 



I got the error by creating "another" application and used the same CodePush key in the "new" application. (They have the same src/)

Old app: RN 0.66.1
New app: RN 0.70.5
On both: react-native-code-push@^7.0.4

I use CodePush CLI and it's at v3.0.0.

**Comment by chamaldesilva** [comment]
> [Android] Fix issue where CODE_PUSH_APK_BUILD_TIME resource was not generating w/ AGP 4.2+ #2337

Works for me! Thanks!

**Comment by chamaldesilva** [comment]
> @duduccosta add this under android -> defaultConfig `resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())` the issue resolved, but I don't wanna use this I need another way :(

Thank you so much @hiunguyn !

**Comment by EdgarJMesquita** [comment]
well i got the same error and solved by commiting the string resources
