### ISSUE TITLE
Skip requirement that user hit "mandatoryContinueButton" when a mandatory update is available

### ISSUE THREAD

**Issue by euwyn** [Microsoft/react-native-code-push#224]
re: "mandatoryContinueButtonLabel" of "UpdateDialogOptions" - is it possible to require no user click when a mandatory update is available? i realize there's a separate "silent" mode, but that only works on restart. i'd like the loading dialog to pop up when the app is first installed/run and the update applied.

**Comment by lostintangent** [comment]
We recently added a new option to the `sync` method called `mandatoryInstallMode`, which by default is `InstallMode.IMMEDIATE`. What that means if that when you call `sync()`, if it discovers an update that is optional, it will wait until the next restart to apply it (fully silent), but if it discovers an update that is mandatory, it will apply it immediately. This way, you don't need to rely on the update prompt to drive immediate installs. 

Additionally, if you want to display a loading screen when an update is available and being downloaded, you can do that by using the sync status changed callback parameter of sync.

```javascript
codePush.sync(null, (status) => {
   // Check the status parameter and show/hide the loading dialog as applicable
});
```

If you want the behavior that I mentioned above, you can NPM-install the bits from this GitHub repo. Otherwise, we'll be publishing it to NPM this afternoon.

Let me know if that will work for you. Thanks!

**Comment by lostintangent** [comment]
I'm going to close this for now since we spoke on Discord, and I believe you were unblocked. Please re-open this if you're still hitting an issue or you wanted to discuss this feedback further. Thanks so much!
