### ISSUE TITLE
[iOS] Every codepush update release on RN 0.69 crashes throwing Fatal Exception: RCTFatalException: Compiling JS failed: Wrong bytecode version

### ISSUE THREAD

**Issue by marf** [microsoft/react-native-code-push#2302]
Hello,
everytime I try to release an update using codepush on iOS (but probably happens in Android too) after I update to RN 0.69 I get this crash:

```
Fatal Exception: RCTFatalException: Compiling JS failed: Wrong bytecode version. Expected 85 but got 84 Buffer size 10440312 starts with: c61fbc03c103191f540000008377d303
Compiling JS failed: Wrong bytecode version. Expected 85 but got 84 Buffer size 10440312 starts with: c61fbc03c103191f540000008377d303
```

I do not know if now RN controls some bytecode version number and if it sees a different version number it deliberately crashes.

I have Hermes enable in my project too.

Any solutions?

Thanks!

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.69
* iOS/Android/Windows version: All iOS verions
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by jedashford** [comment]
Here are the install instructions for our team:
`npm install -g https://github.com/microsoft/appcenter-cli.git // codepush android fix for RN 0.69 in master but not released yet - https://github.com/microsoft/appcenter-cli/issues/1987`

Unfortunately we can't find a way to use a local CLI and use the appcenter.js file directly, so we all need to install appcenter from main instead of the latest april release. The above command should get you going.

**Comment by jedashford** [comment]
> I can see they made a fix here: [microsoft/appcenter-cli#1987](https://github.com/microsoft/appcenter-cli/issues/1987) But there's still no new version of react-native-code-push.

Here are the install instructions for our team:
npm install -g https://github.com/microsoft/appcenter-cli.git
// codepush android fix for RN 0.69 in master but not released yet - https://github.com/microsoft/appcenter-cli/issues/1987

Unfortunately we can't find a way to use a local CLI and use the appcenter.js file directly, so we all need to install appcenter from main instead of the latest april release. The above command should get you going.

**Comment by geekyoperand** [comment]
Hi @jedashford , @RominHalltari , @marf , Does code push supports react native version 0.68.1. Because as per the documentation only these versions are mentioned

![image](https://user-images.githubusercontent.com/52500177/181120977-a8642b3a-0ebb-4954-afc1-af75a2df5934.png)

**Comment by jedashford** [comment]
> Hi @jedashford , @RominHalltari , @marf , Does code push supports react native version 0.68.1. Because as per the documentation only these versions are mentioned
> 
> ![image](https://user-images.githubusercontent.com/52500177/181120977-a8642b3a-0ebb-4954-afc1-af75a2df5934.png)
> 

We have used it in 68.2 and now in 69.1 in production without any issue. We do need to have the team and CD use main branch install of the appcenter cli as 69+ codepush deploy is broken in the appcenter cli latest release.

**Comment by amhinson** [comment]
This has been fixed in https://github.com/microsoft/appcenter-cli/releases/tag/v2.11.0, so the latest version of the CLI should compile correctly. I think this issue can be closed now.
