### ISSUE TITLE
how about diff main.jsbundle 

### ISSUE THREAD

**Issue by 91jason** [Microsoft/react-native-code-push#232]
how about diff main.jsbundle  and just download the diff code ??

**Comment by lostintangent** [comment]
This is definitely on our radar as something we would be interested in doing. Are you finding that the JS bundle represents the majority of your app size, and therefore, having to download the entire thing when you can it is costly? We already perform file-level diff updates so that only changed files will be downloaded. This can eliminate the need to download lots of image assets, which for many apps, represents the bulk of their size.

**Comment by 91jason** [comment]
thanks~

**Comment by mvayngrib** [comment]
something like https://github.com/mafintosh/browser-sync-stream could really minimize the update size
