### ISSUE TITLE
react-native code-push not working in  react-native@0.70.0

### ISSUE THREAD

**Issue by ko-devHong** [microsoft/react-native-code-push#2356]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. react-native upgrade 0.70.0
2.  react-native-code-push install 7.0.4
3. appcenter codepush  // success

### Expected Behavior
What you expected to happen?
-  I thought the app would be updated because of the code push.

### Actual Behavior
What actually happens?
-  The code push has been uploaded successfully, but the bundle of the code push is not downloaded even if it is the same version.
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/45538347/197704281-b9ce8bfe-7832-4dda-8786-17a4a1e0e4f2.png)

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.70.0
* iOS/Android/Windows version: monterey 12.6
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by architect-aimonkey** [comment]
We are algo having this problem after migrating to RN 0.70.4 from RN 0.68.4 where it was working properly.
The message is that the codepush failed. It is not being downloaded even if it was properly uploaded pointing to the respective build version.
We use codepush on a daily basis about 20 times per day, so we know how it works very well.
We are using react-native-code-push version: 7.0.5

**Comment by Abbondanzo** [comment]
Give the fix listed in this PR a try:
https://github.com/microsoft/react-native-code-push/pull/2337

**Comment by architect-aimonkey** [comment]
> Give the fix listed in this PR a try. The cause was a bump to AGP, more info in the actual PR descripton #2337

Thanks but I didn't understand a single thing from that PR description. Where and what do we need to fix?, can't find anything related to these comments on my build.gradle or other wrapping files.

**Comment by Abbondanzo** [comment]
> > Give the fix listed in this PR a try. The cause was a bump to AGP, more info in the actual PR descripton #2337
> 
> Thanks but I didn't understand a single thing from that PR description. Where and what do we need to fix?, can't find anything related to these comments on my build.gradle or other wrapping files.

In your **app's** `build.gradle` file (the one located in `your-project/android/app/build.gradle`), add these lines in:
```gradle
android.buildTypes.each { buildType ->
    // to prevent incorrect long value restoration from strings.xml we need to wrap it with double quotes
    // https://github.com/microsoft/cordova-plugin-code-push/issues/264
    buildType.resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
}
```

**Comment by yahorsi** [comment]
When this can be fixed?

**Comment by JamesGs1994** [comment]
I added as same below in android/app/buildgradle but for me its not updating
`plugins {
  id 'com.android.application'
  id 'com.google.gms.google-services'
}

import com.android.build.OutputFile
import org.apache.tools.ant.taskdefs.condition.Os


/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
    bundleInRelease: false
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and that value will be read here. If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

/**
 * Architectures to build native code for.
 */
def reactNativeArchitectures() {
    def value = project.getProperties().get("reactNativeArchitectures")
    return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

android {

     aaptOptions.cruncherEnabled = false
    aaptOptions.useNewCruncher = false 
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.tbotapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
        multiDexEnabled true
        resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())

        if (isNewArchitectureEnabled()) {
            // We configure the CMake build only if you decide to opt-in for the New Architecture.
            externalNativeBuild {
                cmake {
                    arguments "-DPROJECT_BUILD_DIR=$buildDir",
                        "-DREACT_ANDROID_DIR=$rootDir/../node_modules/react-native/ReactAndroid",
                        "-DREACT_ANDROID_BUILD_DIR=$rootDir/../node_modules/react-native/ReactAndroid/build",
                        "-DNODE_MODULES_DIR=$rootDir/../node_modules",
                        "-DANDROID_STL=c++_shared"
                }
            }
            if (!enableSeparateBuildPerCPUArchitecture) {
                ndk {
                    abiFilters (*reactNativeArchitectures())
                }
            }
        }
    }

    if (isNewArchitectureEnabled()) {
        // We configure the NDK build only if you decide to opt-in for the New Architecture.
        externalNativeBuild {
            cmake {
                path "$projectDir/src/main/jni/CMakeLists.txt"
            }
        }
        def reactAndroidProjectDir = project(':ReactAndroid').projectDir
        def packageReactNdkDebugLibs = tasks.register("packageReactNdkDebugLibs", Copy) {
            dependsOn(":ReactAndroid:packageReactNdkDebugLibsForBuck")
            from("$reactAndroidProjectDir/src/main/jni/prebuilt/lib")
            into("$buildDir/react-ndk/exported")
        }
        def packageReactNdkReleaseLibs = tasks.register("packageReactNdkReleaseLibs", Copy) {
            dependsOn(":ReactAndroid:packageReactNdkReleaseLibsForBuck")
            from("$reactAndroidProjectDir/src/main/jni/prebuilt/lib")
            into("$buildDir/react-ndk/exported")
        }
        afterEvaluate {
            // If you wish to add a custom TurboModule or component locally,
            // you should uncomment this line.
            // preBuild.dependsOn("generateCodegenArtifactsFromSchema")
            preDebugBuild.dependsOn(packageReactNdkDebugLibs)
            preReleaseBuild.dependsOn(packageReactNdkReleaseLibs)

            // Due to a bug inside AGP, we have to explicitly set a dependency
            // between configureCMakeDebug* tasks and the preBuild tasks.
            // This can be removed once this is solved: https://issuetracker.google.com/issues/207403732
            configureCMakeRelWithDebInfo.dependsOn(preReleaseBuild)
            configureCMakeDebug.dependsOn(preDebugBuild)
            reactNativeArchitectures().each { architecture ->
                tasks.findByName("configureCMakeDebug[${architecture}]")?.configure {
                    dependsOn("preDebugBuild")
                }
                tasks.findByName("configureCMakeRelWithDebInfo[${architecture}]")?.configure {
                    dependsOn("preReleaseBuild")
                }
            }
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk true  // If true, also generate a universal APK
            include (*reactNativeArchitectures())
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            debuggable true
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }

    // dexOptions {
    //     incremental true
    //     javaMaxHeapSize "4g"
    // }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])

    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.facebook.fresco:animated-gif:2.5.0'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    implementation 'com.google.firebase:firebase-analytics'
    implementation platform('com.google.firebase:firebase-bom:31.0.1')
    implementation 'androidx.multidex:multidex:2.0.1'

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        //noinspection GradleDynamicVersion
        implementation("com.facebook.react:hermes-engine:+") { // From node_modules
            exclude group:'com.facebook.fbjni'
        }
    } else {
        implementation jscFlavor
    }
}

if (isNewArchitectureEnabled()) {
    // If new architecture is enabled, we let you build RN from source
    // Otherwise we fallback to a prebuilt .aar bundled in the NPM package.
    // This will be applied to all the imported transtitive dependency.
    configurations.all {
        resolutionStrategy.dependencySubstitution {
            substitute(module("com.facebook.react:react-native"))
                    .using(project(":ReactAndroid"))
                    .because("On New Architecture we're building React Native from source")
            substitute(module("com.facebook.react:hermes-engine"))
                    .using(project(":ReactAndroid:hermes-engine"))
                    .because("On New Architecture we're building Hermes from source")
        }
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

def isNewArchitectureEnabled() {
    // To opt-in for the New Architecture, you can either:
    // - Set `newArchEnabled` to true inside the `gradle.properties` file
    // - Invoke gradle with `-newArchEnabled=true`
    // - Set an environment variable `ORG_GRADLE_PROJECT_newArchEnabled=true`
    return project.hasProperty("newArchEnabled") && project.newArchEnabled == "true"
}
`

**Comment by JamesGs1994** [comment]
> Thank you very much @Abbondanzo It works!!!
Can you please share your bulid gradle, how its inserted that lines

**Comment by JamesGs1994** [comment]
I am Using React native version 0.70.5 and Code Push Version 7.4 and also Added some build Types also but for me it not working

`

defaultConfig {
........
resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format(""%d"", System.currentTimeMillis())
}
"react": "18.1.0",
"react-native": "0.70.5",
"react-native-code-push": "7.0.4",
"react-native-config": "^1.4.11",
"react-native-countdown-circle-timer": "^3.0.9",
"react-native-device-info": "^10.3.0",
"react-native-vision-camera": "2.14.1",
"redux-saga": "^1.2.1",
"redux-saga-firebase": "^0.15.0",
"vision-camera-code-scanner": "0.2.0",
"vision-camera-face-detector": "0.1.8",
},``

**Comment by Abbondanzo** [comment]
@JamesGs1994 
> I added as same below in android/app/buildgradle but for me its not updating

The setup you've provided should work fine. The `resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())` can also be added within a `defaultConfig` block as you have it. If you run a full build, you should find generated resource file inside of `android/app/build/generated/res/resValues/(debug or release)/values/gradleResValues.xml`. It'll look something line this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Automatically generated file. DO NOT MODIFY -->

    <!-- Value from build type: debug -->
    <integer name="react_native_dev_server_port">8081</integer>
    <!-- Value from build type: debug -->
    <integer name="react_native_inspector_proxy_port">8081</integer>
    <!-- Value from default config. -->
    <string name="CODE_PUSH_APK_BUILD_TIME" translatable="false">"1670509050553"</string>

</resources>
```

If that string isn't present, there may be another issue but it's tough to say why your updates aren't working without taking a closer look at the update failures

**Comment by JamesGs1994** [comment]
After build I can see same  

> android/app/build/generated/res/resValues/(debug or release)/values/gradleResValues.xml.

`<?xml version="1.0" encoding="utf-8"?>
<resources>

    

    
    <integer name="react_native_dev_server_port">8081</integer>
    
    <integer name="react_native_inspector_proxy_port">8081</integer>
    
    <string name="CODE_PUSH_APK_BUILD_TIME" translatable="false">"1670517781999"</string>

</resources>
`

**Comment by JamesGs1994** [comment]
My LOGS after I run APP 


 LOG  [CodePush] Sync already in progress.
 LOG  [CodePush] Checking for update.
 LOG  [CodePush] Reporting binary update (1.0)
 LOG  [CodePush] Downloading package.

**Comment by Abbondanzo** [comment]
> My LOGS after I run APP
> 
> LOG [CodePush] Sync already in progress. LOG [CodePush] Checking for update. LOG [CodePush] Reporting binary update (1.0) LOG [CodePush] Downloading package.
> 
> [https://github.com/microsoft/react-native-code-push/issues/2085](url) Here they mentioned some Gradle version mismatch also will not update I am not sure for RN 0.70.5 what gradle version would be matching GradlePropertie wrapper version distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip Build gradle classpath("com.android.tools.build:gradle:7.2.1")

After the binary downloads, what other logs do you see? The error would occur just after the download

**Comment by JamesGs1994** [comment]
Yes I a getting this Error...!
 LOG  [CodePush] An unknown error occurred.
 LOG  [CodePush] Read error: ssl=0x6e51a20e48: I/O error during system call, Connection reset by peer

**Comment by JamesGs1994** [comment]
Again I tried with good network speed I got below LOGS but its not updating the app

 LOG  [CodePush] Downloading package.
 LOG  [CodePush] Installing update.
 LOG  [CodePush] Update is installed and will be run on the next app restart.

**Comment by JamesGs1994** [comment]
Hai Sir ...!
Its upadting the App 
Issues is not there because My APP size is 200mb. When ever I do Code Push It takes more time to Update nearly 1hr

**Comment by JamesGs1994** [comment]
> Codepush is slow now, I don't know why
> 
> need to wait at least 30m-1h for it to apply, on some devices it pushes immediately

This can happen because of 

1. App size (MB)
2. Network speed 
3. Reloading app after update (Rendering the app)

**Comment by NgocLe1001** [comment]
same issue
