### ISSUE TITLE
Code Push Update is very slow on Android and iOS

### ISSUE THREAD

**Issue by agrawalsurabhi89** [microsoft/react-native-code-push#2372]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. On Load of the app, we are calling checkforUpdate() to check if there is an update present or not.
2. if user clicks on Update will download the bundle and we are showing the loader by the time bundle is download in the device. 
3. Once its downloaded the updated we are showing that its update

### Expected Behavior
The update should happen very quickly, sometime it get stuck in the update and takes very long to update which is very frustating to the user.

### Actual Behavior
It should run very fast while updating
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by zeusstl** [comment]
This is a perpetual issue for me as well. I'm shocked there aren't more people complaining about this, which makes me wonder if checkForUpdate is the wrong way to do be setting this up.

It seems like codepush is doing an entire comparison rather than a quick simple check. Or maybe caching isn't working right on the codepush end. I'm going to test more.

This issue is making the tool virtually unusable as it needs to wait between 3 and 20 seconds each time the app is reopened. If we can't find a solution, we may try to implement a local solution to only check once a week or so to try to avoid this issue. Or we may need to switch to a different service.

**Comment by abhijeet-sqh** [comment]
We have been facing this issue while checking for CodePush updates today as well for both Android and iOS. Seems to be random around 3PM UK time. Service was kind of completely blocked for more than an hour. Occurring randomly even now.

**Comment by abhijeettpt** [comment]
We have been facing similar slowness while checking for updates today as well. Seems to be random and roughly lasted for 2 hours around 3 PM UK time. Speed seems to drop randomly every now and then.
