### ISSUE TITLE
Android - Error: Duplicate resources

### ISSUE THREAD

**Issue by MobileMon-Majestic** [microsoft/react-native-code-push#2442]
When I add code push and try to build for Android, I get this error:

Execution failed for task ':app:mergeMyAppeReleaseResources'

Error: Duplicate resources

I think it's similar to what people talk about here:
https://stackoverflow.com/questions/53239705/react-native-error-duplicate-resources-android

I tried all of those solutions and none work

iOS works for me fine, its only Android thats the problem

When I remove code push package, the problem goes away. So I know the error is specific to code push

**Comment by MobileMon-Majestic** [comment]
i think the issue goes away if I remove 

apply from: "../../node_modules/react-native/react.gradle"

from app build.gradle

not sure why the documentation says to have that line

but now I run into a new issue:

https://github.com/microsoft/react-native-code-push/issues/2418#issuecomment-1381463162

**Comment by hk-skit** [comment]
@MobileMon-Majestic Did you find any workaround for this?

**Comment by mynameisliuyurong** [comment]
If you set CodePushDeploymentKey in build.gradle, remove CodePushDeploymentKey from strings

**Comment by BarbieriMatheus** [comment]
My first suggestion is to clean the gradle in the Android folder:
`./gradlew clean`

If won't fix you can try add a prefix "app:" in your command build:
`./gradlew app:bundleRelease`

**Comment by ReactNativ** [comment]
`cd android $ ./gradlew clean`

**Comment by cam-shaw** [comment]
If you are getting duplicate resources on the file, `CodePushHash`, read the following.

Instead of running gradle clean each build as that'll cause your next build to take longer, I've been doing this for a little bit and it seems to be fine

**Important** - Below is just my path to the file. You will need to update the part `createBundleStgDebugJsAndAssets` depending on names of your flavours etc.. You can look at the path of the duplicated file and it'll tell you what to put here.

```bash
rm ./android/app/build/generated/assets/createBundleStgDebugJsAndAssets/CodePushHash
```

**Comment by garmoshka-mo** [comment]
full cleaning will increase next build time significanlty.
instead, it's better to only clean codepush bugs files before build, in my case they are here:
`rm -rf android/app/build/ASSETS`
