### ISSUE TITLE
CodePush server is down ?

### ISSUE THREAD

**Issue by QuangBinhDinh** [microsoft/react-native-code-push#2458]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Push my code like usual, using `appcenter codepush release-react` command. Got this error `Command 'codepush release-react -a username/project -d Staging -t *' failed with exception "internal error"`
2. Using `--debug` mode, got this error message: `Getting CodePush deployments...Response status code: 500
Body: {"message":"internal error","err_message":"read ECONNRESET"}`

### Expected Behavior
Code is pushed normally

### Actual Behavior
Code cannot be pushed , appear log "Internal Server Error". 
Two hour ago I still can push my code but now I can't.

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.66.4

I already check the server status in https://status.appcenter.ms/  but no one report this error yet.

**Comment by alexkuk44** [comment]
Same problem. And all my app settings and codepush history became empty

**Comment by eddietex** [comment]
I was also seeing this issue all day on March 16th, and did not see anything on that status page.
However, that has changed. The status page has been updated with an incident that affected codepush on March 16th.

So, that probably explains the issue we are referring to.

That said, since late March 16th, the number of errors in the application I use codepush has been significant lower, but still existent.
