### ISSUE TITLE
[Android] Rnpm link and Manual code in README doesn't match.

### ISSUE THREAD

**Issue by BilalBudhani** [Microsoft/react-native-code-push#247]
Code generated by `rnpm link` and the code provided for manually linking the library in README doesn't match for Android platform.

**Comment by lostintangent** [comment]
@BilalBudhani Yeah that's why we don't currently document the use of RNPM for Android, since our plugin isn't particularly compatible with the expectations that it has. iOS works perfectly, but Android has some snags.

You should be able to fix it though if you perform the manual steps, and do the following additional items that back out of some changes that RNPM made:

1. Renove the import statement for "com.microsoft.codepush.react.CodePushReactPackage".

3. Remove the "new CodePushReactPackage()" expression that RNPM added to the getPackages method. 

And you

**Comment by lostintangent** [comment]
@BilalBudhani Any luck? :)

**Comment by lostintangent** [comment]
We just updated the docs to call out these changes for RNPM. I'll close this for now but please re-open this if this workaround didn't work for you. Thanks for reporting it!

**Comment by BilalBudhani** [comment]
@lostintangent Sorry for replying late I was traveling for last couple of days. 

I did get the plugin setup done manually on Android and it works perfectly fine. Thanks for guiding me out there. I went through the doc changes in regards to `rnpm` for Android as well. It sounds good to me. :+1:

**Comment by lostintangent** [comment]
Awesome! Thanks for confirming :)
