### ISSUE TITLE
Internal Server Error when promoting

### ISSUE THREAD

**Issue by nicinabox** [Microsoft/react-native-code-push#248]
<img width="618" alt="screen shot 2016-03-16 at 9 39 18 am" src="https://cloud.githubusercontent.com/assets/246280/13816111/176f5442-eb5b-11e5-8a2d-551f27cf2974.png">

Following the [instructions in the docs](http://microsoft.github.io/code-push/docs/cli.html#link-9). I think I did everything right?

**Comment by lostintangent** [comment]
Hmm, yeah that looks like an issue on our end. Could you check the history of your production deployment to see if the promote went through: "code-push deployment history CrimsonConnect Production"?

If not, could you try running the promote one more time? I'm investigating the issue here in parallel, I'm just curious if it's a temporal problem. Thanks!

**Comment by nicinabox** [comment]
No worries! Here's some more output:

![screen shot 2016-03-16 at 10 30 49 am](https://cloud.githubusercontent.com/assets/246280/13817971/383dcd6e-eb62-11e5-8d55-eb49c6d4e9c7.png)

**Comment by dtivel** [comment]
Hi, nicinabox.

We found a bug and fixed it.  The fix is live.  Can you please try again and let me know the result?

I apologize for the inconvenience to you.  We'll add test coverage for this issue to make sure it doesn't happen again.

Thanks,

Damon

**Comment by nicinabox** [comment]
:+1: Thanks guys, you're doing great!

![screen shot 2016-03-16 at 12 59 17 pm](https://cloud.githubusercontent.com/assets/246280/13823287/eaeb018e-eb76-11e5-9044-655a362ea020.png)

**Comment by dtivel** [comment]
Thanks, nicinabox.  And sorry again for the issue.

**Comment by xwartz** [comment]
I'm getting the same issue now.
