### ISSUE TITLE
[Question] Run Appcenter codepush in China

### ISSUE THREAD

**Issue by nolife08021** [microsoft/react-native-code-push#2534]
Hi, thanks for this library, may i know is it able to run Codepush checkForUpdate/download update features in China? Will the Appcenter Codepush domain blocked or not allowed to access in specific area?

**Comment by DmitriyKirakosyan** [comment]
Hi @nolife08021, we regret to inform you that the performance and stability of App Center may vary in different countries due to specific laws and regulations in certain regions. For more information regarding this matter, you can refer to the section on "Data Residency and Sovereignty" in the [App Center Security documentation](https://learn.microsoft.com/en-us/appcenter/general/app-center-security#data-residency-and-sovereignty).

Similar issue: #1949.

Closing.
