### ISSUE TITLE
RN 0.72 support and AppDelegate.swift

### ISSUE THREAD

**Issue by justinchan23** [microsoft/react-native-code-push#2588]
when will support for RN 0.72 be released? 

also is there an example of how to integrate it when using an AppDelegate.swift file instead of an obj-c file?

**Comment by justinchan23** [comment]
done

**Comment by dusanristic** [comment]
Does 8.1.0 supports RN0.72? As per their documentation, the latest RN version that is supported is 0.71.

**Comment by DmitriyKirakosyan** [comment]
@dusanristic , it should work with RN v0.72. Please let us know if you encounter any issues.

**Comment by djindal61** [comment]
We migrated the RN from 0.70.7bto 0.72.7

This is old version:
 "react-native-code-push": "^7.0.4",
"react-native": "0.70.7",

This is new version:
"react-native": "0.72.4",
"react-native-code-push": "^8.2.0",

We are not able to push the code  changes . New changes are not reflected ion android & iOS.


Please help us to clear out 


Error: The uploaded package was not released because it is identical to the contents of the specified deployment's current release.

**Comment by dusanristic** [comment]
As for `Error: The uploaded package was not released because it is identical to the contents of the specified deployment's current release.`

You have already uploaded an identical bundle on CodePush, so AppCentre doesn't let you upload it once again. If you try to change something in your code and deploy a new CodePush, this error will disappear.

**Comment by djindal61** [comment]
Hi @dusanristic 

We deployed the version on app center. After that We changed the UI in one file and trying to do hot code push. We are getting the above error.

Error: The uploaded package was not released because it is identical to the contents of the specified deployment's current release.
