### ISSUE TITLE
[Android] Requirement of Additional Steps

### ISSUE THREAD

**Issue by ricku44** [microsoft/react-native-code-push#2589]
I'm seeking clarification on why the following additional steps are needed for Android integration with react-native-code-push:

In your android/settings.gradle file, please add the following lines to the end of the file:
```
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```

I've noticed that these steps are required, unlike some other React Native libraries that integrate automatically. Could someone please explain why this manual configuration is necessary for react-native-code-push on Android?"

**Comment by DmitriyKirakosyan** [comment]
Hi @ricku44 , thanks for reaching out!

This code is introduced to manually link the react-native-code-push library because autolinking might not work seamlessly for every scenario. This specific change was made to cater to React Native version 0.62 and above. If you find that removing these lines doesn't affect your project and everything operates as intended, then you can opt to omit them. If that's the case, I'd appreciate it if you could inform me of the React Native version you're using.

**Comment by ricku44** [comment]
@DmitriyKirakosyan With directory changes mentioned [PR-2613](https://github.com/microsoft/react-native-code-push/pull/2613), React Native will enable autolinking for react-native-code-push.
