### ISSUE TITLE
downloaded package in wifi or 4G/3G condition issue

### ISSUE THREAD

**Issue by jxintang** [Microsoft/react-native-code-push#259]
is code-push providing a config to confirm that the package is downloaded only in a wifi condition?
otherwise,the end-user has to download the package in other network condition,and maybe they don't konw about it.

**Comment by lostintangent** [comment]
@jxintang We don't currently provide a way to prevent downloading updates on cellular networks, but since your app is simply calling `sync` (or `checkForUpdate`), you could use the [NetInfo](http://facebook.github.io/react-native/docs/netinfo.html#content) API to determine if the end user is on wi-fi before calling `codePush.sync`.

We have it on our backlog to add a new option to `sync` that could handle this automatically, but it hasn't been high priority since there's a straight forward solution already.

Would this be something you'd like us to add? If so, I'd love to get your thoughts on a few design questions:

1. Would you want to prevent just the download on cellular networks, or would you want to prevent the update check as well? Even though the later wouldn't eat much data, it would still have a batter impact.

2. What about mandatory updates? Would you want them to be treated special, so that you could ensure critical fixes went out even for users on cellular networks, or would you simply want to prevent all updates from occurring unless the user was on wi-fi?

Thanks for reporting this!

**Comment by lostintangent** [comment]
@jxintang I'm going to close this since per my previous comment, this is easily achievable today using the `NetInfo` API. If you would like to request that we add this logic directly to CodePush, please re-open this bug and we can discuss what that enhancement would look like. Thanks!
