### ISSUE TITLE
unable to link app after installing w/ npm and cocoapods

### ISSUE THREAD

**Issue by charlieschwabacher** [Microsoft/react-native-code-push#273]
Hi - appreciate all your work on code-push!  I ran into an issue when installing into my react-native app.  Starting from a working project, I added `"react-native-code-push": "^1.9.0-beta"` to `package.json`, and `pod 'CodePush', :path => '../node_modules/react-native-code-push'` to `Podfile`, and then ran `npm install` and `pod install`.  After making only these changes, the project fails to link w/ the following error:

```
duplicate symbol _main in:
    /Users/username/Library/Developer/Xcode/DerivedData/MyProject-aqrwunwlhomiwrdpixfnqxvvzbwt/Build/Intermediates/MyProject.build/Test-iphonesimulator/MyProject.build/Objects-normal/x86_64/main.o
    /Users/username/Library/Developer/Xcode/DerivedData/MyProject-aqrwunwlhomiwrdpixfnqxvvzbwt/Build/Products/Test-iphonesimulator/libCodePush.a(pwd2key.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Have you heard of anything like this before?  Or is there a step that I am missing?

**Comment by geof90** [comment]
`pwd2key` belongs to the SSZipArchive library that we are shipping together with this plugin. My guess is that one of your other plugins in the project are also using the SSZipArchive library, resulting in a duplicate symbol. 

There used to be a similar issue https://github.com/Microsoft/react-native-code-push/issues/241 reported here previously, except that user was linking the project manually (not using CocoaPods).

If you followed the workaround in that issue, and manually linked our plugin instead of using CocoaPods, you should be able to get this to work. I am not too sure about the best workaround from a CocoaPods workflow, but I will be happy to investigate this more tomorrow if you are still blocked. My guess is that if you removed the SSZipArchive files from our plugin in the node_modules folder, you should also be able to get this to just work, with some additional effort.

**Comment by charlieschwabacher** [comment]
Hey - thanks for the quick response.  I realized my issue was related to running in 'Test' scheme, and it looks the culprit is some test code at the end of pwd2key.c including a `main` function.  I was able to fix by commenting out lines 165-187 here https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/SSZipArchive/aes/pwd2key.c#L165 .  If you guys aren't using the test code in this file, I think it could make sense to lose everything after line 105.  Please let me know if a pull would be helpful.

**Comment by lostintangent** [comment]
@charlieschwabacher Thanks for tracking down the issue here! We're definitely not using these, so I agree it makes sense to remove it. If you are down to send a PR, that would be much appreciated :)

**Comment by lostintangent** [comment]
Closing via your PR. Thanks again @charlieschwabacher!

**Comment by charlieschwabacher** [comment]
Thank you for pointing me in the right direction, and for merging!
