### ISSUE TITLE
[iOS] Apps crashes after second update

### ISSUE THREAD

**Issue by xiaobuu** [Microsoft/react-native-code-push#276]
I'm new to iOS development. An app I published with RN 0.22.2 and code-push 1.10.0 seems to crash after users receiving a second update.
I'm not sure what cause the problem, but right after I push a second update, I got several feedbacks from my friends, the app crashed in several seconds to several minutes after the user opened the app in the foreground ( maybe the app has just finish downloading the latest bundle).
I'm using sync() and InstallMode.ON_NEXT_RESUME with a custom duration. 
But more strangely after rolling back my latest update, some users report their app doesn't crash and some others' app still crash after being opened for some time. But after reinstalling the app from appstore again, there is no more crashes.

**Comment by lostintangent** [comment]
@xiaobuu I'm so sorry to hear this! We haven't seen an issue with this behavior before, so I'd love to try to get to the bottom of it.

Stupid question: is it possible that the second update you released was generated after you updated React Native and/or any plugins (including CodePush)? The crash could have happened because of an incompatibility between the binary and the bundle.

Also, just to make sure, after the users experience the app crashing, when they re-opened the app, did it successfully roll back to the previous update? Does the CLI display the presence of rollbacks for the release when you run "code-push deployment history APP DEPLOYMENT"?

**Comment by xiaobuu** [comment]
@lostintangent Thank you for the hint. I just recalled that I might have upgraded the CodePush from 1.9.0 to 1.10.0, maybe that's what makes the app crash!  I'm going to close the issue. I'll check if the app crash in next release, thank you again!
