### ISSUE TITLE
I don't know how to upload assets(IOS)

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/react-native-code-push#277]
there is my Project folder tree

Project
---assets
----items
-----image1.png
---src
----index.js

in the index.js I using 
```javascript
var icon = require('..assets/items/image1.png');
...
```

now I need release a new version with image1.png
then I try use these cmd

```
rm -rf ./code-push-release
mkdir code-push-release
cp -rf assets/ code-push-release/assets/
react-native bundle --platform ios --entry-file index.ios.js --bundle-output ./code-push-release/main.jsbundle --assets-dest ./code-push-release --dev false
code-push release time_castle_client main.jsbundle 1.0.0 --deploymentName "Staging" --description "inventory" --mandatory true
```

But I got this

``
Upload progress:[=================================================] 100% 0.0s
[Error]  The uploaded package is identical to the contents of the specified deployment's current release.
``

**Comment by lostintangent** [comment]
The error you're getting it because the update you are releasing isn't different than the current release. We raise this error to prevent users from accidentally releasing the same update multiple times. There's a few things I noticed:

1. Shouldn't your image path be "../assets/items/item1.png"' instead of "..assets/items/image1.png"
2. Why are you copying the assets folder into the code-push-release/assets folder? The "react-native bundle" command will do this properly for you
3. When calling "react-native bundle" you are using an entry file of index.ios.js, but your app seems to be using index.js. Which one is correct?

BTW, I would recommend using the new "release-react" command in the CLI. It will take care of much of this work for you and will make the release less error prone. Simple run "code-push release-react time_castle_client ios". It will handle bundling your app, inferring the app version and releasing it to CodePush.

**Comment by dtivel** [comment]
The command that you're calling:

    code-push release time_castle_client main.jsbundle 1.0.0 --deploymentName "Staging" --description "inventory" --mandatory true

...is attempting to release only main.jsbundle.  It sounds like this file was already released, which would lead to the error you see.

I think you need to release the directory which contains both the newly built main.jsbundle and /assets folder.  Does this work?  Note this uses the ./code-push-release directory instead of main.jsbundle.

    code-push release time_castle_client ./code-push-release 1.0.0 --deploymentName "Staging" --description "inventory" --mandatory true

**Comment by xhacker5000** [comment]
sorry, it's index.ios.js
I am not sure about 
``
Shouldn't your image path be "../assets/items/item1.png"' instead of "..assets/items/image1.png"
``

I just try the code-push release-react time_castle_client ios, it's seem very nice

**Comment by xhacker5000** [comment]
Thank you very much for povide  release-react cli , it's very great!

**Comment by lostintangent** [comment]
Awesome! We put out the release-react command to simplify this whole process, since we recognized it was error prone. Thanks for confirming! BTW, I would be very interested in knowing what time castle is, since we've been chatting for a while. Is this a public app? :)

**Comment by xhacker5000** [comment]
not finish yet .
it's a game app with real life , I mean your body in the reality.
when you enter a room(what I prepare for you) , then you open the time-castle app 
then you will enjoy everything.

time-castle will using ibeacon tech , in the room , ibeacon check your postion ,and turn on some hardware , you can recv message on time-castle-client app , and it's adventure game . 

if you interesting ,  welcome to Beijing  I will show you , that's is amazing game

**Comment by xhacker5000** [comment]
could I have your email address :D , I can make an ad-hoc version for you :)

**Comment by lostintangent** [comment]
That sounds awesome! You can email me at joncart@microsoft.com :D

**Comment by xhacker5000** [comment]
hm...could you have any code-push downloadProgressCallback e.g.
```javascript
    codePush.sync({
          updateDialog: {
          appendReleaseDescription: true,
          descriptionPrefix: "\n\更新信息:\n",
          downloadProgressCallback:function(recv,total){
            console.log(recv,total);
          }
         },
          installMode: codePush.InstallMode.IMMEDIATE
        })
```

I wanna make download progress, but there is no log at downloadProgressCallback function
