### ISSUE TITLE
There is Error 3 times...Still trying

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/react-native-code-push#293]
1:
``
Upload progress:[==================================================] 100% 0.0s
[Error]  write EPIPE
``

2:
``
Upload progress:[======================                            ] 45% 251.3s[Error]  write EPIPE
``

3:
``
Upload progress:[===========                                       ] 23% 0.0s[Error]  connect ETIMEDOUT 23.101.203.117:443
``

I am very very hurry  up for release my project :(
what can I do now

**Comment by dtivel** [comment]
Which app is this for?  The time castle app?  I want to see what information is logged on our end.

**Comment by xhacker5000** [comment]
no it's zxlorderclient

**Comment by silhouettes** [comment]
Looking at our server logs, it looks like your releases are timing out on our server. We've definitely had issues connecting with users specifically in China and are looking at geo-distribution options over the next few weeks.

As you're in a hurry, I will increase our timeout threshold to 2 hours so that you're unblocked for now, at least until we have a permanent fix. Thanks so much for being patient, and I will get back to you as soon as this change is deployed!

**Comment by silhouettes** [comment]
Hi @xhacker5000, we've deployed that change for you. Can you confirm that you're unblocked for now? We will continue looking at a long-term fix in the meantime.

**Comment by kiliwalk** [comment]
sometimes i was facing the same problem. you may need to use proxy to push the update.
i'd changed the local code-push-cli script, to add superagent-proxy package which read the system-wide proxy setting.

**Comment by lostintangent** [comment]
@kiliwalk Would you be able/willing to submit a PR with that change? Anything we could do to improve the CLI would be hugely appreciated! Otherwise, I will take a look at the superagent-proxy agent this weekend.

**Comment by kiliwalk** [comment]
i've tried, but you know, i have to add superagent-proxy's typescript definition first. it's a little time-consuming work, so i changed the local js script directly. 
but i'll try that again, as you wish:)

**Comment by xhacker5000** [comment]
I am already release , thanks for your help.

there are some issue for time-castle project,  as you know time-castle is game like app , so there is always have a lots of assets , like image, music ,or something like this. 

I want to know if  file [a.png] I already release it , when I release the next version , the [a.png] still be upload again or not?

**Comment by silhouettes** [comment]
The whole package, including [a.png], will be uploaded from the CLI, but when the client receives the update, they will download only the files that have changed. Out of curiosity, how big is your package?

Generating the diff from the CLI rather than the server is certainly an option for speeding up the upload! It would mean we'd have to download the metadata for the previous package(s) that we'd like to diff against though. We'll have to think about the pros and cons of this approach, tagging @shishirx34 as he is working in this area.

**Comment by shishirx34** [comment]
@xhacker5000, Like @silhouettes said, we do upload the entire package(including a.png) to the CLI(lets call this v5). The server will calculate diff for the previously released package(say v4) with the current one that you are releasing and if say a.png already existed it won't be added to the diff package which will be served to the apps requesting an updateCheck which has package v4. So we take care of saving time/bandwidth on serving updates to the apps. We are improving the diffing logic to so that we can improve the performance and bandwidth for multiple packages(v3, v2...). However to generate diffs we do need to upload the entire package to the server to calculate diff.

Like @silhouettes said, generating diff from the CLI is one option, however that would require downloading the contents and doing the diff work on CLI which could entail its own set of problems. I think there could be another approach that we can partially merge work to be done between CLI and server which could potentially improve the workflow.

Main reason that we need to have entire contents for every release on server is so that no matter which app(with any package and appropriate binary version) runs a updateCheck will get the correct content and not break the app.

That said, we are always working on improving the user experience for our customers and we will try our best to make uploads work better for you.

**Comment by lostintangent** [comment]
I'm going to close this issue for now since @kiliwalk's proxy contribution was just merged. Moving forward, we're going to be investigating distributing our servers to China and possibly optimizing the client-side upload process. Let us know if you run into any problems in the meantime. Thanks!
