### ISSUE TITLE
Current package targeting older app version prevents update

### ISSUE THREAD

**Issue by johnwayner** [Microsoft/react-native-code-push#297]
I think that perhaps [this change](https://github.com/Microsoft/react-native-code-push/commit/89d0ffaeb88e609671e83ab4acb0d47a77122289#diff-fdfb3b2552c5b0ea96bacdf49a2581c7L43) may have caused a bug.

If the application is currently using a package targeting an earlier version of the application, any updates that target the application's real version are ignored.

This happens because the update check will use the current package's target app version (localPackage.appVersion) instead of the real app version (config.appVersion).

**Comment by geof90** [comment]
@johnwayner thanks for reporting!

If the package targets an earlier version of the application, it should not be run and be deleted due to [this change](https://github.com/Microsoft/react-native-code-push/commit/89d0ffaeb88e609671e83ab4acb0d47a77122289#diff-7a4664ad8b157a07a7a6cf0a7de26861R165). Have you actually encountered this problem yourself?

**Comment by johnwayner** [comment]
I think I may have had this issue because I was calling sync even in my development environment (using the simulator).  When I updated the app version it would continue to use the downloaded package for the previous version.

I also misused the app version specification for the deployments.  I was thinking I was specifying a minimum version rather than a npm-style version specification.

I'm fine with closing this out as user error.  It just seemed a bit suspicious to request updates using the previous package's appVersion, so I thought I'd bring it up.

**Comment by geof90** [comment]
No worries, it's a perfectly legitimate scenario to be calling sync and testing CodePush with the simulator. 

The fact that updates stick around when you deploy a new binary to the simulator is by design, because we think it is a bad experience for users to keep having to re-download the same update every time a new binary is deployed. Does this behaviour make sense to you?

Also, if you deploy a new binary to the simulator **with a newer/different appVersion**, the original CodePush updates on disk should be cleared. The SDK would not re-download the CodePush updates because they would be targeting an older version of the binary. I will be double-testing this to ensure that this indeed the behaviour, but I just want to ensure that you are indeed seeing this behaviour, or are you seeing something different?

> When I updated the app version it would continue to use the downloaded package for the previous version.

This doesn't sound right. If you updated the app version and deployed a new binary to the simulator, it should ignore the updates present on disk and load the one in the binary.

**Comment by lostintangent** [comment]
I just confirmed that the logic to clear CodePush updates on disk (in debug mode) when the app version is changed works correctly on both iOS and Android, so I'm not entirely sure how you would have got into this situation when deploying your app to the simulator.

@johnwayner Out of curiosity, could you provide an example of the versions you were specifying before when releasing an app update to CodePush? I'd like to make sure we try to repro your exact situation, since I'd love to track down an issue if one exists :)

Thanks so much!

**Comment by kiliwalk** [comment]
I don't know whether my situation is same as @johnwayner . 
Environment: 
* "react-native": "^0.25.0-rc",
* "react-native-code-push": "^1.10.2-beta"
* the client app version 1.6.0

Problem:
* After i release an update which targetBinaryVersion is '>=1.6.0 <1.6.2', the client's checkForUpdate method returns null, and a debug log `[CodePush] An update is available but it is targeting a newer binary version than you are currently running.` displayed.
* Then i release another update which targetBinaryVersion is '>=1.0.0 <1.6.2', the client can get this update right 

The problem is occurred after upgrade react-native(from 0.23) and react-native-code-push(from 1.10.0).

**Comment by geof90** [comment]
@kiliwalk That sounds like a different problem. In this case, you are not getting an update which targets your binary version within the range. I will take a look into this.

**Comment by geof90** [comment]
@kiliwalk Are you able to reproduce this error at all? During the time when your app version is 1.6.0 and your update's targetBinary version is '>=1.6.0 <1.6.2', if you ran the following code:

```
  const config = await getConfiguration();
  const localPackage = await module.exports.getCurrentPackage();
  console.log("config appVersion is: " + config.appVersion);
  console.log("localPackage appVersion is: " + localPackage.appVersion);
```

What do you get?

**Comment by johnwayner** [comment]
The key to my issues seems to stem from not using `jsCodeLocation = [CodePush bundleURL];` on the simulator.  Because of this the application is running from code served via the react native on-the-fly http-based code deployment process.

I have a screen in the application that reports the current version as queried via CodePush's getCurrentPackage method.  This method will return package information if it is present -- even if not running.  There is code to handle this by including an additional `_isDebugOnly` field on the package result.  Unfortunately this flag is not set because `isRunningBinaryVersion` defaults to `NO` and is never set otherwise b/c of the lack of call to `[CodePush bundleURL]` (I'm guessing on this bit. I haven't actually traced the initialization back to that call).

This lack of bundleURL call is also the reason the out dated package is not removed.

The bundle was installed via calling `download` and then `install` from the remote package object returned by `checkForUpdate`.  But all that is silly if not using `[CodePush bundleURL]`.

So I think this is mostly user error with a dash of confusing results due to `isRunningBinaryVersion` defaulting to `NO`.

And since you asked, I'll include the specific version information, although I doubt it's useful at this point.
If I start the application with the appVersion set to '0.1.4' and call `checkForUpdate` I correctly get the last updated that has targetBinaryVersion='0.1.4' which in my case is v32.  If I then change the appVersion to '0.1.5' (in xcode) and re-run the app, `getCurrentPackage` still returns v32 (although I now know it's not actually running that code).  And the the `checkForUpdate` call returns v32 as well because that call uses my v32 package's appVersion (0.1.4) in that request instead of the app's actual version (0.1.5).

**Comment by geof90** [comment]
@johnwayner thanks for all that information! I can confirm that what you are seeing is a legitimate bug. The old updates should indeed be cleared or at least not used when checking for updates if u deploy a new binary, even if it doesnt call [CodePush bundleURL]. I'm sorry that you had to go through all that investigation. We will be submitting a fix soon.

**Comment by johnwayner** [comment]
No problem.  Happy to be able to help.

**Comment by kiliwalk** [comment]
@geof90 It's my fault, sorry

**Comment by lostintangent** [comment]
@johnwayner Thanks again for this feedback! We just published the fix to NPM. Please re-open this issue if you continue to experience this problem after upgrading, and let us know if you run into any other problems. Thanks!
