### ISSUE TITLE
image assets seems always fully downloaded in android

### ISSUE THREAD

**Issue by kiliwalk** [Microsoft/react-native-code-push#302]
My image assets are located in `<project dir>/app/asset/img/`. When I just changed some js scripts, released an update and checked update in app, the remote package was so huge(about 4M). And after downloaded, I checked the data directory and saw the all images here.
Is there something I'd missed?

**Comment by geof90** [comment]
Is this the first CodePush update that the app installs? Unfortunately, we are unable to do a diff update for the first update in Android. Subsequent updates after the first one will be diff-ed as expected. Unfortunately we have not found a workaround for this yet.

Refer to this PR for more details! https://github.com/Microsoft/react-native-code-push/pull/211

**Comment by lostintangent** [comment]
@kiliwalk One other thing to note is that when we download a partial update, we merge it with the content of the previous one locally, so when you look at the data directory and see all of the images there, that's why. All of those files weren't necessarily downloaded.

If you want, we could help verify that the server is generating diff updates for you if you'd like. Let us know!

**Comment by kiliwalk** [comment]
thanks @geof90 and @lostintangent .
@lostintangent , What I checked is the `unzipped` directory(I commented the delete statement in .java file). 
Things run as @geof90 said, the subsequent updates after the first update will not contain all images.
I will do more check to my current staging environment app.
Thanks your help again!
