### ISSUE TITLE
Downloading in the mainThread

### ISSUE THREAD

**Issue by CaoLiang1991** [Microsoft/react-native-code-push#303]
When I want to the second page，why do I have to wait for the download is complete。It is not asynchronous ？

**Comment by geof90** [comment]
[It should be asynchronous](https://github.com/Microsoft/react-native-code-push/blob/25f313a7ed2e73e6e38d4bd27a302a1a7cfe71f5/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L439). How are you calling the download function? Are you using the `[codePush.sync()](https://github.com/Microsoft/react-native-code-push#codepushsync)` API?

**Comment by CaoLiang1991** [comment]
codePush.sync({
                updateDialog: false,
                installMode: codePush.InstallMode.ON_NEXT_RESTART
              }
            );

First page  is LoginPage，after  login success，it is not to second page。 It is waiting for the download.

**Comment by lostintangent** [comment]
@CaoLiang1991 Coyld you let us know which component you're using for navigation? That way we can try to repro this exact issue.

As an aside, in your case, you could simply call sync(), since the uodateDialog parameter is false by default, and the installMode pla eager defaults to ON_NEXT_RESTART.

**Comment by CaoLiang1991** [comment]
render() {
    if (this.state.isLogin === true) {
      return <Router
        firstRoute={{name: '爱油口袋', component: MainPage}}
        headerStyle={{ backgroundColor: '#ff4400' }}
        backButtonComponent={ BackButton }
        />;
    } else if (this.state.isLogin === null) {
      return <View />
    } else {
      if (React.Platform.OS == 'ios') {
        StatusBarIOS.setStyle(0);
      }
      return <LoginPage />;
    }
  },

import Router from 'react-native-router-fix';

**Comment by lostintangent** [comment]
@CaoLing1991 I believe this issue may be related to the download progress events that we fire from our native plugin to JS. As @geof90 mentioned, the download itself happens on a background thread, but the download progress events that we fire to JS could potentially interrupt your app while it's trying to navigate.

Since your app isn't even listening to download progress events when you call sync, it doesn't make any sense for these events to even be firing in the first place, so we're going to submit a fix this week to disable these events when an update is being downloaded which didn't request progress events. I'm hoping this should fix your situation.

Thanks for reporting this. Stay tuned!

**Comment by geof90** [comment]
@CaoLiang1991 We just merged #316 which should address this issue, we will be publishing the update to NPM, so feel free to reopen this issue if the problem still persists after the update.
