### ISSUE TITLE
RNPM incorrectly patches the build.gradle file when it contains a buildscript.dependencies block

### ISSUE THREAD

**Issue by ScandyMark** [Microsoft/react-native-code-push#310]
not sure if this a react-native-code-push issue or a rnpm link issue
    compile project(':react-native-code-push') was placed inside "dependencies {  ... }", unfortunately there is was another object with dependencies at top of file, and it was placed in the wrong place.

buildscript {
  repositories { ... 
  }

  dependencies { ... 
    < ended up here>
  }
}
dependencies { ...
 <should have been here>
}

**Comment by lostintangent** [comment]
@ScandyMark If you're using RNPM to install CodePush, then we aren't involved in the `build.gradle` modification at all. I'm happy to help drive this issue getting resolved, but it would definitely be a bug with `rpm-plugin-link`.

Out of curiosity, is this an existing native Android app which you're embedding React Native views into?

**Comment by ScandyMark** [comment]
not a native Android app.  buildscript came about from crashlytics install
https://fabric.io/kits/android/crashlytics/install

**Comment by lostintangent** [comment]
Makes sense. Thanks for clarifying!

You can see the issue with `rnpm-plugin-link` [here](https://github.com/rnpm/rnpm-plugin-link/blob/master/src/android/patches/makeBuildPatch.js#L8), since they simply look for the first `dependencies {` statement in the `build.gradle` file, and attempt to add the linked module to it.

**Comment by lostintangent** [comment]
@ScandyMark I just filed an [issue](https://github.com/rnpm/rnpm-plugin-link/issues/75) with RNPM and am going to drive the fix from there. I'm going to close this issue from our repo, since it isn't a bug with our plugin. Let me know if you think that makes sense, and if not, feel free to re-open it :) Thanks for letting us know!

**Comment by ScandyMark** [comment]
Closing make sense.  Concern would be that folks often look at open issue when they run into an error, so might over look.  But my experience is RNPM folks fixes usually come in a day or two.

**Comment by lostintangent** [comment]
That's a completely fair point. I'll re-open it for now then, since I would prefer viability for our users over cleaning out bugs :)

**Comment by lostintangent** [comment]
@ScandyMark This has be resolved in RNPM [1.7.0](https://github.com/rnpm/rnpm/releases/tag/v1.7.0). Thanks again for reporting this!
