### ISSUE TITLE
code push always rollbacks after install new version

### ISSUE THREAD

**Issue by L-Jovi** [Microsoft/react-native-code-push#323]
I always find that when I push new package by `code-push release-react [MyApp] ios -m`, after device successfully update this new version, then when I close the app and reopen again, version will always rollback.

my first release bundle use `react-native bundle --platfrom ios --dev false --entry-file index.ios.js --bundle-output ./bundles/main.jsbundle`, I'm not sure why always back to this local bundle on device, what should I do?

thanks for your time.

**Comment by lostintangent** [comment]
The two most common reasons this can happen are:

1. Your app isn't calling `sync` on startup (e.g. you're calling it in a button click or on resume), and you're also not calling `notifyApplicationReady` on startup. The CodePush runtime needs to be told that the update was considered successful in order to prevent it from rolling back. The sync method calls notifyApplicationReady, so as long as you're calling it on app start, then you're fine, but otherwise, you need to make sure you're calling notifyApplicationReady somewhere in your startup process (e.g. the conponentDidMount of your root component).

2. Your `AppDelegate.m` file is configured to get the JS bundle location from the binary instead of from CodePush. This prevents CodePush from choosing which update to run on app start.

Do any of those match your app? If not, could you look at the console logs of your app? The sync method logs a bunch of diagnostic messages and it may help indicate what the issue is.

**Comment by lostintangent** [comment]
@L-Jovi Any luck trying either of those workarounds?

**Comment by L-Jovi** [comment]
@lostintangent   thanks for your reply!  I follow that calling `notifyApplicationReady ` in `componentDidMount ` and it works fine now :)

**Comment by lostintangent** [comment]
Awesome! Thanks for confirming.

**Comment by mvayngrib** [comment]
@lostintangent when does Code Push decide that an update was unsuccessful? For example, if I call sync() a minute after the app loads, is that too late?

**Comment by silhouettes** [comment]
@mvayngrib - `notifyAppReady()` (or `sync()`, which calls it internally), need to be called *at some point* in the first run of the update to mark it as successful. The second time the app is booted, it will check if the update was marked as successful. If not, it will be rolled back.

We recommend making one of these calls immediately in your root `componentDidMount()` (and in fact if you [wrap your root component](https://github.com/Microsoft/react-native-code-push#plugin-usage) we do this for you), because the user could quit the app at any moment, including immediately after it loads. So, if you only have a single call to `sync()` a minute after the app loads, and a user quits the app 30 seconds into the first run of the update, it will be rolled back the next time the app is booted.

Note that the intent of the rollback feature is to ensure that your update is well formed and loads successfully, not that it is free of errors during the whole lifecycle of its execution. I hope this makes sense!

**Comment by mvayngrib** [comment]
@silhouettes cool, that's more or less what I figured, but thanks for the in-depth answer!
