### ISSUE TITLE
More than one CodePush instance Error 

### ISSUE THREAD

**Issue by ACCTFORGH** [Microsoft/react-native-code-push#335]
I was testing CodePush under bad network condition in my app. When the download got stuck, I minimized the app and when I click on the App icon again to open it, I saw the error message below.

**Error Message:**
 D/ReactNative( 1428): [CodePush] More than one CodePush instance has been initialized. Please use the instance method codePush.getBundleUrlInternal() to get the correct bundleURL for a particular instance.
D/ReactNative( 1428): [CodePush] Loading JS bundle from "/data/data/com.golorry/files/CodePush/51febf286bed5defb9314cc4e2c95b91a1a33aa96ca511637940a73d187ef4e7/CodePush/index.android.bundle"

The code snippet in my app is as below.

**Javascript:**
codePush.sync(null,null,this.onCodePushDownloadProgress,this.onCodePushError);

**Download Progress**
I/ReactNativeJS( 1434): [CodePush] Downloading package.
I/ReactNativeJS( 1434): Code Push Downloading 15920 of 401488
I/ReactNativeJS( 1434): Code Push Downloading 32304 of 401488
I/ReactNativeJS( 1434): Code Push Downloading 48688 of 401488
I/ReactNativeJS( 1434): Code Push Downloading 65072 of 401488
I/ReactNativeJS( 1434): Code Push Downloading 81456 of 401488
I/ReactNativeJS( 1434): Code Push Downloading 97840 of 401488

Another instance, stuck in 
I/ReactNativeJS( 1434): [CodePush] Downloading package.

Restarting of the emulator (Genymotion Android 4.4.2) gets around the error.

There is one rolled-back update available locally but I've seen message in previous successful updates that it's been ignored. Code Push has been working fine under good network condition.

Environment
RN 0.24 Android
CodePush ^1.10.6-beta
Tested with RN dev/debug pkg

**Comment by geof90** [comment]
Hi @ACCTFORGH, did you see the app crash at all, or are these just from the debug logs? If the app did not crash, the download could have simply timed out due to poor network conditions, and reverted to the previous version, which is fine and expected behaviour.

From my experience, the `[CodePush] More than one CodePush instance has been initialized. Please use the instance method codePush.getBundleUrlInternal() to get the correct bundleURL for a particular instance.` log is very much benign. The issue is that occasionally, the Android OS kills the currently running Activity and restarts it when the app goes into the background, just to free up resources. Because we [cached the earlier constructed CodePush instance statically](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L84), the log will show up, but it is fine because the previous instance has already been destroyed anyway. I will think of a better way to handle this so that that misleading log doesn't show up.

**Comment by lostintangent** [comment]
We just removed this log message since it was falsely reporting an error. Apologies for the confusion!
