### ISSUE TITLE
Usage within RN & CI workflow?

### ISSUE THREAD

**Issue by LeBlaaanc** [Microsoft/react-native-code-push#338]
I'm trying to wrap my head around when to use CP within my CI workflow. 

What we do is commit to an "in-house" git branch and a CI build is triggered. The build leaves the version the same but bumps the build number and sends it to Hockeyapp. I then manually run CP release because I'm experimenting but it could run with the build. 

As it stands it seems like my apps unecessarily update the jsbundle each time a Hockeyapp update is installed on a user's phone even though the jsbundle might be identical in both CP and the compiled app. 

Any thoughts on how to use CP effectively in this environment or what I might modify in my workflow for it to be more effective? Thanks so much!

**Comment by LeBlaaanc** [comment]
Probably a dupe of #112 but I'd still be curious thoughts in an in-house environment that gets updates immediately.

**Comment by rub8n** [comment]
Hi @LeBlaaanc, is great to see your question as I just started working on a tutorial to cover CI & CD scenarios with CodePush and VSTS.

A few clarification questions:

- Is this a fair representation of the workflow you describe above - Build app > Release and install via HA > Release manual update via CP without changing any part of the jsbundle > bundle update happens on app installed via HA?
- When you say “in-house environment that get updates immediately”, do you refer to solutions for immediately sending jsbundle updates, full binary updates or both?
- Have you looked into our [CodePush VSTS extension]( https://github.com/Microsoft/code-push-vsts-extension)?

**Comment by LeBlaaanc** [comment]
Hi @rub8n,

1. Yes, this seems to reflect our current in-house workflow.
2. When I say immediately I just am referring to not going through any App Store review.
3. We use a very similar tool, bitrise which contains a workflow to build the app.

**Comment by rub8n** [comment]
If that's the workflow, then in theory you should not get a bundle update as we verify the local jsbundle contents against those in the server and only updated when they are different.

Are you able to constantly repro this issue? Also, are you hitting this on Android or iOS?

**Comment by lostintangent** [comment]
@LeBlaaanc It's possible that this is related to issue #345. Could you let us know which version of React Native you're currently using? It seems like the bundler broke our current heuristic for detecting if the binary-contained contents are the same as an update in CodePush. Thanks!

**Comment by LeBlaaanc** [comment]
@lostintangent R `0.14.8` RN `0.25.1` however my results are due to my workflow I think, @rub8n did you ever write anything up, anything I can help with?

**Comment by LeBlaaanc** [comment]
@lostintangent @rub8n on a related note, if I target a `2.7.x` on my "Production" deployment and then later on target `2.8.x`, what happens to the `2.7.x` release, does it keep updating?

**Comment by geof90** [comment]
@LeBlaaanc to your last question, clients on running `2.7.x` of the binary would still get the `2.7.x` release.

**Comment by lostintangent** [comment]
@LeBlaaanc When an app calls `sync`, the server will attempt to find the latest update that the client is eligible for, and it isn't already running. Therefore, when you release a new update that targets a newer binary version, users on older versions will continue to get updates they hadn't already synchronized with. Additionally, you could even release a new CodePush update that targets the older binary version, and that wouldn't impact the users on the newer binary version, since the server would "skip" over that release for clients that weren't eligible for it.

**Comment by lostintangent** [comment]
@LeBlaaanc Is the outstanding issue here that your users are getting the app from HockeyApp and then downloading a CodePush update that is already equivalent to what they have in the binary? If so, I think this issue is potentially a dupe of either #352 and/or #345, since we now know that React Native broke our plugin's ability to hash the binary contents and determine equivalence with the CodePush server, and that it's possible for two difference machines (e.g. multiple CI builds) to release the exact same update to CodePush without them being treated equivalentely.

I just want to make sure we're investigating this issue if it's outstanding, or if we can close it in favor of one of the other two and focus on fixing those core issues. Thanks!

**Comment by LeBlaaanc** [comment]
@lostintangent I can't confirm that the client side has this issue as we switched off mandatory updates so it's hard to notice. I'm okay with closing this issue and I can comment on one of those if I have client side jsbundle compare problems. I do know the release command is certainly creating duplicate releases even running RN `0.25`. I'll be sure to update the other issues with this info.

**Comment by lostintangent** [comment]
@LeBlaaanc Perfect, thanks so much!
