### ISSUE TITLE
Should code-push dependency in package.json be updated?

### ISSUE THREAD

**Issue by chetstone** [Microsoft/react-native-code-push#359]
In the CLI docs it says that the `rollout` parameter of the react-release command will won't work unless the code-push plugin version is > 1.9.0.beta. However, this component depends on code-push 1.8.0. Is it time to update this dependency?

**Comment by lostintangent** [comment]
That is referring to the version of this plugin ("react-native-code-push"), not the "code-push" NPM package. If you check out the release notes for [v1.9.0](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.9.0-beta), you'll see that it includes the client side support for rollout.

**Comment by lostintangent** [comment]
I'm going to close this issue, but if you're experiencing an issue with rollout, and/or you think we can make our docs more clear, please re-open it and let us know. Thanks!

**Comment by chetstone** [comment]
The terminology is a little confusing with so many components with similar names. But the [warning in the documentation](https://github.com/Microsoft/code-push/tree/master/cli#rollout-parameter) does specifically say the `CodePush SDK`, not react-native-code-push.

I came to this because I was trying to test my first push to Production by limiting it to myself. After pushing with a rollout parameter of 20, I tried to load the update on my device right away and it wouldn't load. I used react-native-code-push 1.10.3-beta in my production build, so it should have worked. I suspect the problem was some kind of edge case due to it being my first push (v1) in that deployment, or the small number of users I have so far (low single digits :-) I patched the update to increase the rollout to 100 and then I was able to load the update.

**Comment by lostintangent** [comment]
I can update the docs to be more clear, apologies about that. In general, we use the term "CodePush SDK" to refer to the platform-specific client plugin. The "code-push" NPM package is referred to as our "Management SDK" and unless you're scripting a Node build script, isn't directly relevant to most users.

With rollout, it's important to keep in mind that it works by breaking up all possible devices into groups (aka "cohorts") and then only allowing users in the specified percentage group to get it. Specifying a 20% rollout isn't saying that 1 in 5 users will necessarily get it. It's saying that users whose device ID falls within the 20% range will get it, and no one else will. Therefore, when testing it with single digits, the results could have a decent degree of error. As opposed to having 50+ users, where it becomes more accurate due to the randomness of the user's device IDs.

**Comment by chetstone** [comment]
Thanks for the explanation.

**Comment by lostintangent** [comment]
Anytime! I also tweaked our docs to remove the term "CodePush SDK", that way it hopefully doesn't seem overly confusing. Let me know if you think it could be clearer, and feel free to send a PR if you have any suggestions. Thanks again!
