### ISSUE TITLE
Getting undefined when importing in javascript file

### ISSUE THREAD

**Issue by steezeburger** [Microsoft/react-native-code-push#372]
```
import codePush from 'react-native-code-push';
console.warn(codePush);
```
Logs as undefined

<img width="786" alt="screen shot 2016-06-10 at 12 06 52 pm" src="https://cloud.githubusercontent.com/assets/5599073/15974083/e146eb54-2f03-11e6-9fc3-9950438ce738.png">

output of `npm ls --depth=0`
<img width="280" alt="screen shot 2016-06-10 at 12 07 46 pm" src="https://cloud.githubusercontent.com/assets/5599073/15974093/f8d4b99a-2f03-11e6-86c0-88908c09d450.png">

Edit: does the same w/ `require` syntax.

**Comment by geof90** [comment]
Hi @steezeburger, this behaviour you are seeing happens when the [native side of the `react-native-code-push` plugin was not linked properly](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L404). Did you follow all of the plugin installation and plugin configuration steps in our [README](https://github.com/Microsoft/react-native-code-push/blob/master/README.md)?

**Comment by steezeburger** [comment]
I did. Let me run through them again. I may have missed something.

**Comment by steezeburger** [comment]
For some reason it didn't link libCodePush.a properly the first time. I must have done something silly. Thanks for the quick reply! Sorry to take your time.

**Comment by geof90** [comment]
No problem at all!
