### ISSUE TITLE
Custom metadata on packages

### ISSUE THREAD

**Issue by nevir** [Microsoft/react-native-code-push#375]
So, we're going to start tracking a bit of additional metadata with each release (mostly for analytics reasons).  Would be handy to be able to tack additional metadata onto each release

My current approach is to JSON-encode the package's `description` w/ all the info that I want (which isn't bad, either)

**Comment by lostintangent** [comment]
This is definitely something we want to enable very soon. Thanks for filing this, since we'll use it to track the feature and increase the priority :) The `description` solution would be my recommendation in the meantime as well, but I'd like to make this scenario a little more first-class.

**Comment by nevir** [comment]
Awesome.  I'd say it's not very high priority, at least for us - the `description` approach isn't all that bad

**Comment by lostintangent** [comment]
@nevir OK great, thanks for letting us know that. That's really helpful for prioritization.

**Comment by panarasi** [comment]
@sergey-akhalkov I think we should look at how this can be done.

**Comment by sergey-akhalkov** [comment]
@panarasi, I've investigated the ways we could implement this and I suppose we could use the same approach and just implement another one property (called `customMetadata` as example) that users would be able to use instead of `description`.

I also think it would be convenient to implement 2 ways users would be able to specify `customMetadata` - as plain value or as a path to some `.json` file like this:
1. `code-push release-react myapp ios --customUpdateMetadata="myvalue"`
2. `code-push release-react myapp ios --customUpdateMetadata=./mymetadata.json`

What do you think?

**Comment by sergey-akhalkov** [comment]
Closing this due to https://github.com/Microsoft/code-push/issues/273
