### ISSUE TITLE
Always error: main.jsbundle could not be found

### ISSUE THREAD

**Issue by jiyinyiyong** [Microsoft/react-native-code-push#381]
```
Jun 16 17:37:04 yiyongs-iPod-touch dark_rn[410] <Notice>: [CodePush] Downloading package.
Jun 16 17:37:04 yiyongs-iPod-touch securityd[84] <Error>:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Jun 16 17:37:04 yiyongs-iPod-touch securityd[84] <Error>:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Jun 16 17:37:04 yiyongs-iPod-touch securityd[84] <Error>:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Jun 16 17:37:06 yiyongs-iPod-touch dark_rn[410] <Notice>: [CodePush] An unknown error occurred.
Jun 16 17:37:06 yiyongs-iPod-touch dark_rn[410] <Notice>: [CodePush] Update is invalid - A JS bundle file named "main.jsbundle" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
Jun 16 17:37:10 yiyongs-iPod-touch SpringBoard[54] <Warning>: [MPUSystemMediaControls] Disabling lock screen media controls updates for screen turning off.
```

Talked a bit on Discord and checked deployment key and `jsCodeLocation`, found no clue why it is happening.

**Comment by jiyinyiyong** [comment]
I found the bug now in my code. Unexpected. There are **2** deployment keys in the package, the one in `info.plist` is correct, but the one in `CodePush.sync({deploymentKey: ...})` is wrong since it's common code for both platforms.

The error message is really misleading.

**Comment by lostintangent** [comment]
Ah that would explain it. This is why I was asking on Discord if you could check if your key was for your Android app, since this error indicates that the update it's syncing doesn't appear to be a "valid" iOS application. I agree we could improve the message. For the most part, it is attempting to shed light on the fact that you released a JS bundle with a different name than your binary did, which we don't allow. Up until now, that is the primary error case, and to be fair, your scenario is a unique spin on that same issue.

I'd love to understand how we could improve the product/docs for this issue. I just revised our docs and they seem to explain fairly well that the key you pass to sync overwrites the one in your plist. Were you expecting both keys to be used, and possibly have their content merged? How were you actually releasing the updates of the shared code? When you showed the screenshots of your release command, it definitely looked like a "valid" release, so I'm guessing you shared the screenshot of your iOS app deployment and we never discussed the shared code deployment?

**Comment by jiyinyiyong** [comment]
Some factors here, English is not my first language so picking informations from a long document made things tougher, and second I have no experiences on developing Native apps so some terminologies made en confused even though I've been writing React for the Web for long. I just made more mistakes than you thought.

> Were you expecting both keys to be used, and possibly have their content merged?

I followed the guide but not sure about how to fill in the code in JavaScript. What I did after that was reading several examples by searching "codepush.sync" on GitHub and reused code by filling in my key. I was not very sure about the key at first no mention to found I actually have two keys in the project. I noticed this problem in the morning and my workmate explained to me how CodePush is using plist. Then I found I was wrong.

> How were you actually releasing the updates of the shared code?

Still struggling on this since this is my first Native app.

> When you showed the screenshots of your release command, it definitely looked like a "valid" release, so I'm guessing you shared the screenshot of your iOS app deployment and we never discussed the shared code deployment?

At first I tried with Android and it worked after you told me to find logs. As I got errors in trying iOS and I actually did put a new deployment key in `info.plist` by hand, but did not realise my true mistake. I thought it was a problem in trying iOS.

I might have Googled tens of problems in the past weeks. It's always harder to correct my mistakes without right messages.

**Comment by lostintangent** [comment]
Makes sense. Thanks for that detail! I'll send a PR with an improved error message when a get into the office and will ping you feedback. Sorry again for the confusion. I really want our diagnostic logs to be really helpful, so I'll try to take advantage of this awesome feedback :)

**Comment by jiyinyiyong** [comment]
And thanks for your guide in Discord~

**Comment by lostintangent** [comment]
This error message has been improved to call out the need to verify your configured deployment. Apologies again for the confusion. Let us know if you have any further feedback or questions. Thanks!
