### ISSUE TITLE
checkForUpdate returns true even if app is up to date

### ISSUE THREAD

**Issue by nazywamsiepawel** [Microsoft/react-native-code-push#449]
Hey,

I use checkForUpdate to display a prompt for the user to update the application.
```
checkForUpdate(){
    CodePush.checkForUpdate()
      .then((update) => {
        if (!update) {
          console.log("The app is up to date!");
        } else {
          AlertIOS.prompt(
            'Update available',
            'Hey there! New version of the app is available. Wanna update?',
            [
              {
                text: 'Not now', onPress: () => {

              }, style: 'cancel'
              },
              {
                text: 'Yes!', onPress: () => {
                this.sync()
              }
              },
            ],
            null
          );
        }
      });
  }
```
Sync is the same function as in the example app :

```
async sync() {
    let self = this;
    try {
      return await CodePush.sync(
        {
          installMode: CodePush.InstallMode.IMMEDIATE,
        },
        (syncStatus) => {

          switch(syncStatus) {
            case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
              self.setState({
                syncMessage: "Checking for update."
              });
              break;
            case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
              self.setState({
                syncMessage: "Downloading package."
              });
              break;
            case CodePush.SyncStatus.AWAITING_USER_ACTION:
              self.setState({
                syncMessage: "Awaiting user action."
              });
              break;
            case CodePush.SyncStatus.INSTALLING_UPDATE:
              self.setState({
                syncMessage: "Installing update."
              });
              break;
            case CodePush.SyncStatus.UP_TO_DATE:
              self.setState({
                syncMessage: "App up to date.",
                progress: false
              });
              break;
            case CodePush.SyncStatus.UPDATE_IGNORED:
              self.setState({
                syncMessage: "Update cancelled by user.",
                progress: false
              });
              break;
            case CodePush.SyncStatus.UPDATE_INSTALLED:
              self.setState({
                syncMessage: "Update installed.",
                progress: false
              });
              break;
            case CodePush.SyncStatus.UNKNOWN_ERROR:
              self.setState({
                syncMessage: "An unknown error occurred.",
                progress: false
              });
              break;
          }
        },
        (progress) => {
          self.setState({
            progress: progress
          });
        }
      );
    } catch (error) {
      CodePush.log(error);
    }
  }
```

The problem goes as follows :

- `checkForUpdate` is triggered, user updates the app. Everything goes great, the app reloads and `updated` returns null. Everything is up to date.

- if I kill the app and go back to it `checkForUpdate` is triggered. it returns an object with the build information which goes through the conditional statement and attempts to update the app. The app was already up to date earlier so I end up with `CodePush.SyncStatus.UP_TO_DATE`. 

In the second case, shouldn't `checkForUpdate` return null? Is that a bug or predicted behavior? If the latter, how do I check if the app is up to date without triggering the entire `CodePush.sync` process (assuming the case that app was closed and reopened again)?

Thanks!

**Comment by geof90** [comment]
Hi @nazywamsiepawel,

From the code snippet you shared, I think the reason why you are seeing this is that you are not calling [`codePush.notifyAppReady()`](https://github.com/Microsoft/react-native-code-push#codepushnotifyappready). After you killed the app and relaunched it, because `notifyAppReady()` was not called in the previous run of the latest update that was downloaded previously, our plugin triggers a rollback. As such, when you `checkForUpdate()` again, you actually see the update, but with the [`failedInstall`](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L84) flag set to `true` (because we previously failed to install and run it successfully).

The beauty of `sync` is that it takes cares of all of this for you ([calling `notifyAppReady`](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L319), [checking the `failedInstall` flag](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L339), etc. I'm interested why you decided not to use it directly. If it's just because you want to show a custom prompt, you might want to look at the [list of options that we provide in `updateDialog`](https://github.com/Microsoft/react-native-code-push#codepushsync). I think you can easily achieve the same behaviour you are currently looking to implement by passing the right `SyncOptions` to the call to `codePush.sync()`.

**Comment by silhouettes** [comment]
@nazywamsiepawel, did you still need help with this?

**Comment by geof90** [comment]
I'm going to close this for now, feel free to reopen if you still need help.
