### ISSUE TITLE
Timing the reload process

### ISSUE THREAD

**Issue by nevir** [Microsoft/react-native-code-push#46]
For cases when I'm updating an already-started instance of the app, is there a way to know how long that update took? (from `package.apply` to `CodePush.notifyApplicationReady` ideally)

Might be handy to expose that as the resolved value of `CodePush.notifyApplicationReady`

**Comment by lostintangent** [comment]
That's a pretty awesome idea actually. Would you want to use that for in the wild perf monitoring?

**Comment by nevir** [comment]
Potentially! It would definitely be nice to know how long it takes to reload on various devices. Would help inform when it's a good time to trigger an update

**Comment by lostintangent** [comment]
We're actually looking at removing the need to specify a `rollbackTimeout` as well as call `notifyApplicationReady` in order to have rollback protection, so I'm going to close this for now until we settle on that and can then discuss whether we should also try to accommodate timing the app start process.

**Comment by nevir** [comment]
:+1:
