### ISSUE TITLE
TroubleShooting -> there is always an update for the js even after a fresh install

### ISSUE THREAD

**Issue by eladgel** [Microsoft/react-native-code-push#479]
I experience the following:

While installing a fresh version from xcode, codepush calls the sync method and
finds that there is always an update to download

This is how I work with codepush
`import codePush from "react-native-code-push";

class MyApp extends Component {
}

MyApp = codePush(MyApp);`

This is how I release
`code-push release-react AppName ios --deploymentName Development --targetBinaryVersion 0.5.1`

My version in build settings is also 0.5.1

What am I missing here?

**Comment by geof90** [comment]
If there is an update targeting 0.5.1, the CodePush plugin will install it. During development, if you want to clear away all the updates so that CodePush won't see any updates, you can do `code-push deployment clear AppName deploymentName`

**Comment by eladgel** [comment]
What I don't understand is why if my code source on my computer is **newer** then the version on codepush, there is still an update pending from code push, It has an older js code bundle, then the one I have on my device(which was not downloaded from codepush since its a fresh install)

**Comment by geof90** [comment]
Right now CodePush doesn't send timestamps to the server for the server to determine if it should return an update or not, because we don't have a "build timestamp" we can use. However, the SDK does compare local bundles. For example, during development, in debug mode you installed the app to the device/simulator, then u sent a CodePush update to it. Next, you made some changes, and deployed a new version of the app to the device/simulator, WITHOUT first deleting the previous app on the simulator/device. The new binary bits should override the installed CodePush version, and because the CodePush version still exists on disk, it will no longer install new updates. Is this not the behaviour you are seeing?

**Comment by eladgel** [comment]
I will need to check that:

1. Fresh Install on device v0(no prior versions)
2. Release a codepush new bundle for v0
3. Install on device v1 - see if there is a codepush update to it

The behaviour I'm talking about is a fresh install on the device
1. Release a codepush new bundle for v20
2. Fresh Install on device v20(no prior versions)-> update gets called

**Comment by geof90** [comment]
Yes for that scenario you are talking about, the device will get the update.

**Comment by eladgel** [comment]
So if I work on production now my Codepush releases should always be ahead of appstore releases

**Comment by geof90** [comment]
In production, we expect the store versions to always be ahead. Let's say you release 1.0.0 to the store. Next, you find a bug, you release v1 to CodePush targeting 1.0.0. Now all users who download 1.0.0 from the store will get the fix.

Few weeks later, you find that you need to release a new version to the store (maybe you installed a new react native plugin that modified Obj-c code). You publish it as 1.0.1. Now, all users who update their app to 1.0.1 or download it fresh from the store will NOT get CodePush update v1, because it targets 1.0.0.

**Comment by eladgel** [comment]
Just tested this-> 

Published version 1 to Development
![image](https://cloud.githubusercontent.com/assets/412137/17833443/28d0efba-6726-11e6-8aeb-f67af3ce0bf9.png)

Installed version 1.5 on my device
![image](https://cloud.githubusercontent.com/assets/412137/17833447/396adbce-6726-11e6-8474-4ef585f3baf4.png)

Update of binary was called
This is how I published the new version

> code-push release-react MYAppName ios --deploymentName Development --targetBinaryVersion 1
