### ISSUE TITLE
[Question] CodePush behavior

### ISSUE THREAD

**Issue by kenwheeler** [Microsoft/react-native-code-push#483]
I'm trying to understand the default behavior of CodePush. 

Does the app:

1. Load the CodePush bundle
2. If there is an error, fall back to the local bundle?

cc @geof90

**Comment by geof90** [comment]
It depends on the type of error:

1. Error from "loading" the JSBundle (first tick), up to the point the root component is mounted (componentDidMount) in which you call `codePush.sync` or [`codePush.notifyAppReady`](https://github.com/Microsoft/react-native-code-push#codepushnotifyappready). After CodePush installs an update, if you boot up the new version of the app and the app crashes immediately, the next time you boot up the app, it will rollback to the previous installed version (could be another previously installed CodePush version, or the version in the binary if there isn't one).

2. Subsequent errors, for example, user presses a button which triggers a function handler which executes an undefined property access. Such errors will cause a crash, but will not trigger a CodePush rollback, because crashes can happen any point of time in the app and we don't want to be overly aggressive in rolling back updates. [`codePush.notifyAppReady`](https://github.com/Microsoft/react-native-code-push#codepushnotifyappready) is the mechanism by which an update is "rubber stamped" as a successful update - once this has been called during the runtime of a particular CodePush installed version, it will no longer be rolled back.

**Comment by steffenmllr** [comment]
I also have a question on this. By using `jsCodeLocation = [CodePush bundleURL];` in my `AppDelegate.m` there is no Fallback if - for some reason - the user is offline when starting the app for the first time there is no bundle and no app or?

**Comment by geof90** [comment]
@steffenmllr CodePush downloads the bundle and saves it locally on the device, so the app will still start if the device is offline.

**Comment by steffenmllr** [comment]
@geof90 when does the download start? When downloading the app from the app store or on first start?

**Comment by geof90** [comment]
It happens when the app calls codePush.sync().

**Comment by steffenmllr** [comment]
Ok so just to get this right - sorry for asking again:

When I build the app and publish it to the app store - is there a version bundled within the app or do I also need to download the Initial version ?

**Comment by geof90** [comment]
Oh, when you build the app in release mode, there is a shell command that is executed that generates the offline bundle packaged into the IPA/apk. That shell command is part of your build when u created the project using react native's CLI, it has nothing to do with CodePush

**Comment by silhouettes** [comment]
@kenwheeler, @steffenmllr, was there anything else you'd like to know? Feel free to ask if you need more clarification.
