### ISSUE TITLE
CodePush update cause crashes with no reason occasionally.

### ISSUE THREAD

**Issue by colus001** [Microsoft/react-native-code-push#486]
### Scenario

- The update only included `.js` and images such as `.png` 

### Symptoms

- Sometimes it works, sometimes it fails without any information

### Request

- It should works fine
- Otherwise, it should show why this happened such as error log,

---

It is very frustrating to see when updates failed and rollback with no reason. It's very unreliable since we don't know why and when this happens.

**Comment by silhouettes** [comment]
Hi @colus001, the only reason an app will ever rollback is if `CodePush.notifyAppReady()` was not called on the first run of the app. If you wrap your root component as in the [getting started](https://github.com/Microsoft/react-native-code-push#plugin-usage), or you call `CodePush.sync()` on `componentDidMount()`, this should be called behind the scenes for you. Have you done one of these two things?

If you have set up CodePush correctly, the only reason `CodePush.notifyAppReady()` would not be called is because you released an update that crashes before it can be called, for example if you release an Android update to an iOS deployment, or there is some exception as your app boots up.

Judging by your description, it sounds like CodePush is rolling back your app gracefully, and any crash would be originating from your app and not CodePush itself. As CodePush is not a crash reporting service, we do not provide you with information about *why* your app crashed, and it is up to you to use your own crash reporting service, which you'd need regardless of whether you used CodePush.

To be clear, we do offer multiple ways of diagnosing what is happening with your app:

 * The `code-push deployment history` command shows you how many installs, rollbacks, and active users you have on each version of your app.
 * We do actually emit logs as you requested. You can see this by running your app while it is connected to your machine, and using a log viewer or running `code-push debug` on a terminal.
 * We are working on integration scenarios with other crash reporting services.

Does this help?

**Comment by colus001** [comment]
@silhouettes 

Actually it's working most of the time. Normally it works, but sometimes it crashes with no specific reason. Occasionally when I clean `npm_modules` and reinstall packages, it works.

Usually we don't do much except fixing bugs. This time we tried to update `components` and assets such as `images` with `code-push` expecting to do this kind of thing more often in the future. Since it broke our build yesterday, I'm not sure if we can use `code-push` this way. 

Anyways, have any specific milestone to integrate crash report? Maybe we did something wrong, but being unable to debug it is quite painful.

**Comment by silhouettes** [comment]
@colus001 - to re-iterate, have you tried any of the things I mentioned to help you out?

1. How are you calling CodePush? Did you wrap your root component, did you call `CodePush.sync()` in your `componentDidMount()`, or did you do neither (that would be a problem)?
1. What does `code-push deployment history` show?
1. Have you tried to look at the logs emitted from the app and from CodePush, for example by running `code-push debug` while the app is connected to your machine?
1. Have you tried any kind of general-purpose debugging? As mentioned before, we've done everything we can to let you know that the app rolled back, that the reason is that `CodePush.notifyAppReady()` was not called, and then if it's a crash it's up to you to figure out what it was. For example, if it is indeed a crash as you claim, do you have a stack trace?
1. Another possibility - is it possible that you're releasing script assets that depend on a native change?

**Comment by geof90** [comment]
@colus001 Have you considered adding a crash reporting tool (e.g. Sentry, Crashlytics) to your app so that we wouldn't be just fighting blind against such errors?

**Comment by silhouettes** [comment]
I'm going to close this for now, but please comment again if you need further help!
