### ISSUE TITLE
Play Store rejecting app due to violating Device and Network Abuse policy

### ISSUE THREAD

**Issue by Jarred-Sumner** [Microsoft/react-native-code-push#498]
It appears that the Play Store is not allowing my app in the Play Store when `codePush.sync()` is called shortly after the app loads.

Here is the email they sent after I submitted an update:
![image](https://cloud.githubusercontent.com/assets/709451/18032321/6b66283c-6cb6-11e6-93c1-d2279a95586a.png)

I can't say this with 100% certainty, as the Play Store did not specifically say "Apps using Code Push are not allowed in the Play Store". 

However:
- When I reached out to someone who works there, they said that the app was rejected because they detected malware in the app. There is no malware in this app, but maybe something that (1) automatically downloads a bunch of code on app load and (2) saves it for execution next time could look like malware?
- Twice now app updates were rejected under the Device and Network Abuse policy. Removing the call to `codePush.sync()` solved that particular reason for rejection both times.

This means I cannot use Code Push on Android. Is there any way to use Code Push and get the app updates through?

**Comment by geof90** [comment]
We haven't seen apps using CodePush get rejected by Google before, so this is a first for us, but we have seen similar things happen on the iOS App Store. However, we also have many, many customers who are using CodePush in production apps that are live in both stores, so like you said, I don't think it's a case of the Play Store forbidding the use of CodePush or anything like that. Here are some questions I have that could give us a better idea of why the app got rejected:

1. When a user downloads your app from the Play Store right after it goes live, does it immediately download an update from CodePush? Presumably, an app that immediately downloads a lot of data the moment it gets installed would look fishy. I would instead hold off on publishing another version of the app to CodePush until the app is already live.

2. Are you using the `updateDialog` option in `codePush.sync`? This is highly unlikely, but we had users tell us that the iOS App store rejected apps that showed the update dialog before an update is installed because it was confusing and looked too similar to the OS's update dialog. I'm not sure if this would apply to Android at all.

3. I know that Niantic is against users using software that call Niantic's private APIs to gain information about Pokemon in different locations. Perhaps the Google Play Store is placing additional attention on such apps and having more stringent checks? Everytime your app get's rejected, have you ever tried resubmitting but not removing CodePush? Does the app still get rejected in those cases?

**Comment by Jarred-Sumner** [comment]
> 1. When a user downloads your app from the Play Store right after it goes live, does it immediately download an update from CodePush? Presumably, an app that immediately downloads a lot of data the moment it gets installed would look fishy. I would instead hold off on publishing another version of the app to CodePush until the app is already live.

Yes, it immediately downloads the update. I could see how that could look fishy. What is the best practice here? To wait `$interval` before checking for updates?

> Are you using the `updateDialog` option in `codePush.sync`? This is highly unlikely, but we had users tell us that the iOS App store rejected apps that showed the update dialog before an update is installed because it was confusing and looked too similar to the OS's update dialog. I'm not sure if this would apply to Android at all.

I'm not using the `updateDialog` option. Originally, I was using AppHub but switched to CodePush since this is free and they don't support Android. In one iOS update when I was using Apphub, I had their equivalent of that option enabled and Apple rejected the app update.

> 3. I know that Niantic is against users using software that call Niantic's private APIs to gain information about Pokemon in different locations. Perhaps the Google Play Store is placing additional attention on such apps and having more stringent checks? Everytime your app get's rejected, have you ever tried resubmitting but not removing CodePush? Does the app still get rejected in those cases?

Pokecrew is not using Niantic's private APIs. It's a crowdsourced map, which means some of the sightings are outdated or irrelevant, but it does make it a little bit tougher to shut down (although not impossible). I do believe Google Play Store is placing additional scrutiny on this app, as it has been rejected numerous times for various reasons (and they're not consistent about things like the app title in the store listing) -- however for this specific reason, of violating the Device and Network Abuse policy, it has only been rejected when calling `codePush.sync()` on `componentDidMount` in one of the components mounted on app load.

**Comment by geof90** [comment]
`Yes, it immediately downloads the update. I could see how that could look fishy. What is the best practice here? To wait $interval before checking for updates?`

I don't think you need to wait for an interval to call `sync`. What i meant was, only when the app is accepted, and it goes live to all users on the Play Store, only then start publishing updates to CodePush, so that when the reviewers first look at it, they won't ask "why does a fresh version need to download so many additional code updates?", but instead see the call to `codePush.sync` that says the app is up to date and doesn't download anything. On the other hand if an app has been around in the store for at least a day, then publishing updates to it seems more acceptable.

**Comment by Jarred-Sumner** [comment]
Gotcha. That makes sense.  I wasn't sure how Code Push worked -- and was concerned that it'd always pull from the latest version of the code (rather than relying on the on-disk version if it was newer). When I pushed to the Play Store, I immediately pushed a Code Push update to ensure the Play Store version would be correct.

**Comment by geof90** [comment]
> When I pushed to the Play Store, I immediately pushed a Code Push update to ensure the Play Store version would be correct.

This is a seperate issue, but technically, if you added the [`codepush.gradle` build step (see step 3)](https://github.com/Microsoft/react-native-code-push#plugin-installation-android---manual), it should not download the latest version from CodePush if its contents and hash matches the one in the on-disk version exactly. If that doesn't work, it would suggest there is a bug with our hash generation.

**Comment by Jarred-Sumner** [comment]
> if you added the codepush.gradle build step (see step 3), it should not download the latest version from CodePush if its contents and hash matches the one in the on-disk version exactly.

I didn't add that! My bad.
