### ISSUE TITLE
"codepush.gradle" may have not been added to the build definition.

### ISSUE THREAD

**Issue by SimchaShats** [Microsoft/react-native-code-push#510]
Hi when I'm  running in debug mode it works ok, but in release mode I 'm getting next error: 
`Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.`

I added all necessary dependencies like in my build.gradle: 
`apply from: "../../node_modules/react-native/react.gradle"`
`apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"`

then

`buildTypes {
        release {
            buildConfigField "String", "CODEPUSH_KEY", '""'
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '""'
            signingConfig signingConfigs.config
        }
    }`

`compile project(':react-native-code-push')`

and still getting this error I assume that in dir: `assets` there is should be some json file like CodePushCache.json after assemblyRelease, but I don't see it... What I'm doing wrong?

**Comment by geof90** [comment]
I could not reproduce this. How did you test the release build? `react-native run-android --variant=release`?

**Comment by SimchaShats** [comment]
I'm using ./gradlew assembleRelease or tried also "generate signed apk" from android studio, and copy apk to device, I checked assets directory and didn't find this file... But I generated a lot of apk I don't remember all ways how I did it, in of them I saw this file... But I don't know how generated this particular apk! :(

**Comment by SimchaShats** [comment]
Ah I think I found the error... I added sign.config to build.gradle and ran `./gradlew assembleRelease` in regular console without settings of Android Studio and it's created CodePushHash.json file. Sorry for issue.

**Comment by NULLPointerGuy** [comment]
Hi @SimchaShats 
How did you solve the error? 
Even  I'am experiencing the same error..my build.gradle looks something like this

`apply from: "../node_modules/react-native/react.gradle"
apply from: "../node_modules/react-native-code-push/android/codepush.gradle"

signingConfigs {
        release {
            storeFile file("../myreleasekey")
            storePassword "*******"
            keyAlias "alias"
            keyPassword "*******"
        }
    }`
debug{
    //similar debug configs.
}
release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), file('proguard-project.txt')
            signingConfig signingConfigs.release
     }

 compile project(':react-native-code-push')

**Comment by SimchaShats** [comment]
@NullPointerGuy Hi it was long time ago so I don't remember really, I think I just tried to use assembleRelease from console and it worked, but not sure... Like @geof90 wrote

**Comment by NULLPointerGuy** [comment]
@SimchaShats ok..by any chance do you still happen to have that gradle file? just wanted to refer to it..
Thanks..

**Comment by SimchaShats** [comment]
@NULLPointerGuy,Yep ofcours, attached this file...
[build.gradle.zip](https://github.com/Microsoft/react-native-code-push/files/1003301/build.gradle.zip)

**Comment by oussaki** [comment]
am facing the same issue. 

cc: @geof90 

09-07 18:03:59.604 11965 12152 D ReactNative: [CodePush] Restarting app
09-07 18:04:09.776 12177 12177 D ReactNative: [CodePush] Update did not finish loading the last time, rolling back to a previous version.
09-07 18:04:09.790 12177 12177 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
09-07 18:04:09.941 12177 12317 D ReactNative: [CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.
09-07 18:04:10.388 12177 12323 I ReactNativeJS: Running "MReactNativeApp" with {"rootTag":1}
09-07 18:04:10.526 12177 12323 I ReactNativeJS: [CodePush] Sync already in progress.
09-07 18:04:10.535 12177 12323 I ReactNativeJS: [CodePush] Checking for update.
09-07 18:04:10.539 12177 12323 I ReactNativeJS: [CodePush] Reporting CodePush update rollback (v13)
09-07 18:04:12.923 12177 12323 I ReactNativeJS: [CodePush] An update is available, but it is being ignored due to having been previously rolled back.
09-07 18:04:12.930 12177 12323 I ReactNativeJS: [CodePush] App is up to date.

**Comment by SeveHo** [comment]
@oussaki were you able to resolve the issue?

**Comment by elouisramsey** [comment]
@oussaki were you able to resolve this issue?
