### ISSUE TITLE
Questions regarding rollback feature when app crashes.

### ISSUE THREAD

**Issue by tsambora** [Microsoft/react-native-code-push#511]
Is there any configuration or some constraints (code sequencing, for example) to make the rollback feature works?

I do the following in componentDidMount:
```
codePush.notifyApplicationReady();
codePush.checkForUpdate.()
    .then((update) => {some installation code})
```

When the erroneous update from the command above is installed the app crashes. Then I restarted the app it didn't rollback so the app crashes again. So what can we do to make the rollback works?

Thanks before.

**Comment by tsambora** [comment]
FYI i'm using the BuildConfig.DEBUG in my app MainActivity just in case this has something to do with the rollback mechanism.

**Comment by geof90** [comment]
It seems like the crash is happening AFTER `notifyApplicationReady`, thats why there is no longer rollback protection because `notifyApplicationReady` is what "rubber stamps" an update as successful.

My guess is that your installation code may be causing a crash, maybe there is an undefined property access in trying to install an update when there is none. Could you share your installation code?

Also, in general we discourage using the advanced API (notifyApplicationReady, checkForUpdate, install) directly, but instead recommend using either `codePush.sync()` or the default `codePush` decorator, as these APIs are more convenient, less error prone, and also customizable for most use cases. It would be great if you could share the reason, if any, why those APIs do not fit your use case, and we can see if we can add additional feature extensions to those APIs.

**Comment by tsambora** [comment]
Ah yes. The crash indeed happened after the notifyApplicationReady. My question is answered then, thanks. Now i'll just have to adjust where the notifyApplicationReady is placed.

Now regarding my installation code, this is my complete code:
```
codePush.notifyApplicationReady();
codePush.checkForUpdate()
    .then((update) => {
        if (!update) {
            console.log("The app is up to date!");
        } else {
            if (update.isMandatory) {
                codePush.sync({updateDialog: null, installMode: codePush.InstallMode.IMMEDIATE});
            } else {
                codePush.sync({updateDialog: null, installMode: codePush.InstallMode.ON_NEXT_RESTART});
            }
      }
});
```

I'm not sure if i do this right but what i'm trying to do is to download and then immediately apply the update if it's mandatory and download but apply it on restart if it's not. I know that notifyApplicationReady is natively called in the syncInternal mode but for some reason it's not called if i put the sync in componentDidMount so i put it before the checkForUpdate method. Would you help giving me the best practice to do that?

**Comment by geof90** [comment]
`sync` already calls `checkForUpdate` internally, you shouldn't need to call it directly.

To achieve what you want, you could simply make use of [`mandatoryInstallMode`](https://github.com/microsoft/react-native-code-push#codepushoptions) and do the following:
```
codePush.sync({
    updateDialog: null, 
    mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
    installMode: codePush.InstallMode.ON_NEXT_RESTART,
});
```
By the way, the default `updateDialog` is already `null`, the default `mandatoryInstallMode` is already `IMMEDIATE`, and the default `installMode` is `ON_NEXT_RESTART`, so the one line, no frills
```
codePush.sync();
```
would already result in the exact same behavior you want.

> I know that notifyApplicationReady is natively called in the syncInternal mode but for some reason it's not called if i put the sync in componentDidMount

That shouldn't be true. What behavior are you seeing that made you come to that conclusion?

**Comment by silhouettes** [comment]
@tsambora, did you still need help with this?

**Comment by tsambora** [comment]
@silhouettes no, all clear. I'm gonna simplify my code now. Thank you very much for your help.
