### ISSUE TITLE
Any plan of support updating assets?

### ISSUE THREAD

**Issue by oney** [Microsoft/react-native-code-push#52]
Do you have any plan of support updating assets like images?
If you don't want to host image in CodePush, maybe CodePush can let developers upload a JSON file contain images with url. Like
```json
{
  "love": {
    "verson": 2,
    "url": "https://mydomain.s3.amazonaws.com/assets/love.png",
    "mandatory": true
  },
  "hate": {
    "verson": 1,
    "url": "https://mydomain.s3.amazonaws.com/assets/hate.png",
    "mandatory": false
  }
}
```
And, in the client SDK, it makes sure all assets are updated. If version is not the same, the asset should be updated. If the asset is marked as mandatory, it should be downloaded before reloading the app.
Basically, images are saved to Documents directory(on iOS), and load it using `source={{uri: '~/Documents/some-image.png'}}`

**Comment by lostintangent** [comment]
We definitely plan to support assets as well. This is high on our list along with finishing the Android POC. The server and CLI already support releasing multi-file packages, so we just need to update the RN client to support downloading a zip of files instead of simple a JS bundle as well as understanding the diff manifest the server sends down so that we could support incremental updates (e.g. you update or add a single image).

**Comment by oney** [comment]
:+1: :+1: :+1:
