### ISSUE TITLE
(improper rollback)it seems if restart immediately after upgrade, and don't invoke any code-push api on startup, it would be deem as failure then rollback on next app's startup

### ISSUE THREAD

**Issue by sopaco** [Microsoft/react-native-code-push#559]
It seems if restart immediately after upgrade, and don't invoke any code-push api on startup, it would be deem as failure then rollback on next app's startup.

(code-push-react version=1.14.6-beta;cli version=1.12.5-beta)

**Comment by silhouettes** [comment]
Hi @sopaco, our rollback mechanism relies on CodePush being 'notified' that an update is successful. This helps us catch crashes, as well as situations where the bundle simply does not load. If you wrap your root component as advised in the [getting started](https://github.com/Microsoft/react-native-code-push#plugin-usage), we will call `CodePush.notifyAppReady()` automatically for you in your `componentDidMount()` so that an update is 'rubber stamped' as successful, and your updates should work as expected. Does this help?

**Comment by sopaco** [comment]
@silhouettes 
It seems I should manually invoke `notifyAppReady` in such code?
```js
codePush.sync({
                updateDialog: false,
                installMode: codePush.InstallMode.IMMEDIATE,
            }, syncStatus => {
                switch (syncStatus) {
                        case codePush.SyncStatus.UPDATE_INSTALLED:
                                codePush.notifyAppReady();
                                this.showToast('新版已安装')
                                this.setState({upgrade_tip_inline: '已更新'})
                                break;
}})
```

**Comment by silhouettes** [comment]
@sopaco - you should do this:

```
let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };

class MyApp extends Component {
}

MyApp = codePush(codePushOptions)(MyApp);
```

The wrapper component will call `codePush.notifyAppReady()` inside `componentDidMount()`, which is recommended. You can still manually call `sync()` wherever you like.

I'm going to close this for now, but please comment if you need further help!

**Comment by sopaco** [comment]
aha, In face in the version of ios, We use such wrapper to make upgrade on startup, but in the version of android ,if we upgrade via code-push's wrapper on startup, all other await operations was blocked until upgrade complete(the problem only occurs in Android)..., so we manually call sync now.
