### ISSUE TITLE
npm can not find  v1.15.0

### ISSUE THREAD

**Issue by muyuballs** [Microsoft/react-native-code-push#563]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?
* Repro steps and/or stack trace:

(The more info the faster we will be able to address it!)

**Comment by silhouettes** [comment]
Hi @muyuballs, all of our releases are marked with the `-beta` tag, so running `npm install react-native-code-push@1.15.0-beta` should work. As it's the latest version, `npm install react-native-code-push` and `npm install react-native-code-push@latest` should also work.

By the way, are you filing this because you saw that version in the `Supported Versions` section of the docs? That might have been because the docs were updated a day or so before `1.15.0-beta` was published, in which case I apologize for the confusion!
