### ISSUE TITLE
NSAllowsArbitraryLoads : True, no HTTPS?

### ISSUE THREAD

**Issue by sulliwane** [Microsoft/react-native-code-push#57]
Hello,

after adding code-push to my xcode, and diff with git I see this:
```
<key>NSAppTransportSecurity</key>
+	<dict>
+		<key>NSAllowsArbitraryLoads</key>
+		<true/>
+	</dict>
```

I guess it was added by code-push project? It means that the connection with code-push server is not secured right (SSL)? 

thanks!

**Comment by lostintangent** [comment]
Hmm, the CodePush plugin doesnt do anything to modify your plist file. I'm not sure what would have caused that, but it certainly isn't intentional on our part.

Additionally, the connection with CodePush uses HTTPS, so that setting shouldn't be neccessary. Try removing it and testing out the CodePush E2E. You shouldn't have any problems, but let us know if you do. Thanks!

**Comment by sulliwane** [comment]
Sorry my bad! no relations at all with code-push, it was there before.

**Comment by lostintangent** [comment]
That's a relief :) thanks for verifying that for me.
