### ISSUE TITLE
Required dispatch_sync to load constants for CodePush. This may lead to deadlocks

### ISSUE THREAD

**Issue by ptomasroos** [Microsoft/react-native-code-push#632]
* react-native-code-push version: ^1.16.0-beta
* react-native version: 0.39
* iOS/Android/Windows version: ios 10.1
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator
* Repro steps and/or stack trace: just run the app with react-native-code-push integrated

Should one be concerned about the implemtation strategy ? Or is this just a friendly notice that in general using dispatch_sync is a bad idea?

I'm guessing its used in order to make sure new updates are appended before being loaded.
I will happily create a PR to improve the docs so people are not afraid of this warning when it arises.

**Comment by matrosov-nikita** [comment]
Hi, @ptomasroos.
It is problem of react-native, it seems that it's expected behaviour and it also affects other plugins.
Here are some discussions about this issue: https://github.com/facebook/react-native/issues/10312, https://github.com/idehub/react-native-google-analytics-bridge/issues/70, and a [comment](https://github.com/facebook/react-native/issues/10312#issuecomment-252922377) from one of react-native developers which sheds some light on this.
Base on this, i think you could safely ignore this warning and your app will continue work as expected.

**Comment by ptomasroos** [comment]
Thanks for the feedback!

**Comment by fungilation** [comment]
Are you sure this is safe? I'm seeing regression in this. I hit this warning randomly, but repeatedly and often enough in DEV mode, with yellowbox of this warning as I described in https://github.com/facebook/react-native/issues/16376#issuecomment-485223189

This maybe a RN issue, but I don't see this warning from any other component except with CodePush, as every time I see this yellowbox warning, it's always with "CodePush" in the warning text.

This is new as of RN 0.59.5. I have never seen this before upgrading to it. My app been on RN 0.57.8 and up to that, I haven't hit this warning.

FYI and whether this signals larger concerns.
