### ISSUE TITLE
'D.getCurrentPackage' is undefined

### ISSUE THREAD

**Issue by triage** [Microsoft/react-native-code-push#633]
We were able to release a new jsbundle via `code-push release`, but it seems the apps are not receiving the update.

2016-12-06 16:20:32.046 [info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
2016-12-06 16:20:32.048 [info][tid:com.facebook.react.JavaScript] [CodePush] An unknown error occurred.
2016-12-06 16:20:32.048 [info][tid:com.facebook.react.JavaScript] [CodePush] D.getCurrentPackage is not a function. (In 'D.getCurrentPackage()', 'D.getCurrentPackage' is undefined)

* react-native-code-push version:
1.14.6-beta

* react-native version:
0.34.1

* iOS/Android/Windows version:
iOS

* Does this reproduce on a debug build or release build?
both

* Does this reproduce on a simulator, or only on a physical device?
both

* Repro steps and/or stack trace:
normal codepush release + sync

**Comment by silhouettes** [comment]
Is there a reason you used the `release` command instead of `release-react`?

Also, I don't believe that React Native 0.34.1 is supported by CodePush 1.14.6-beta - if you install a version from this list of [supported versions](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms), does that resolve the problem?

**Comment by panarasi** [comment]
@triage Was wondering if this issue is fixed for you. Closing this issue since this is a little old. Please ping us if you are still having this issue and we would be happy to help.
