### ISSUE TITLE
Chnages not shown on app store's downloded file

### ISSUE THREAD

**Issue by uc-asa** [Microsoft/react-native-code-push#640]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.16.0-beta
* react-native version: 0.29.0
* iOS/Android/Windows version: iphone 6 plus
* Does this reproduce on a debug build or release build? Release mode
* Does this reproduce on a simulator, or only on a physical device? Yes I produce on simulator but in physical device not produce which was downloaded from app store
* Repro steps and/or stack trace: No idea

Hello Team,

I'm using code push but it works with simulator but not affected on app store file plz provide steps by which we can use this.

(The more info the faster we will be able to address it!)

**Comment by panarasi** [comment]
@uc-asa Sorry for the late response. I am checking in to see if this is still an issue for you? Were you able to get this fixed ? Since this issue seems specific to your case, I would suggest you ping us on Discord where we can chat and help you with a solution. 

Closing this bug for now since this is pretty old. If you still have the issue, please ping us and we would be glad to help.
