### ISSUE TITLE
Updating hybrid apps

### ISSUE THREAD

**Issue by emielvanliere** [Microsoft/react-native-code-push#663]
We're developing a hybrid native/react-native app: most of our app is native and a few screens are in react-native. As I understand from the documentation, it is currently not possible to update the react-native bundle from within the native app. E.g. the react-native part needs to loaded in order to check for and install updates.

Is this correct or is there a way to update the bundle from the native code?

thanks!

**Comment by sergey-akhalkov** [comment]
@emielvanliere - hi! 
Yes, you are right, we have to load react-native part due to `react-native-code-push/CodePush.js` file contains realization of CodePush module and its methods we need to call.

**Comment by panarasi** [comment]
@emielvanliere Were you able to solve this problem ? As @sergey-akhalkov said, the logic to update the bundle currently lives in the [CodePush.js](https://github.com/Microsoft/react-native-code-push/blob/adf2f76db7a2a71cbb2d7813f50f433ed32e696f/CodePush.js) file. More specifically, the server side checks are actually happening in the [Acquisition SDK](https://github.com/Microsoft/code-push/blob/dbd9f24964ad0b319362a1d485288c0a2a04416c/sdk/script/acquisition-sdk.ts#L97). 

Hence, if you want to update the bundle from the native app, all of this logic would have to be re-implemented in the native code. All the code for unzipping and storing the bundle happens in the native code.

Is there a reason you cannot let the updates happen in react-native ? 

At this point, we do not plan to expose that method in the native code, since that logic is share in Cordova and React Native plugins. Please let us know if there is anything we could do to help.

Closing this bug since there is no code change required. Let us know if this resolution does not work for you and we could explore other solutions.

**Comment by emielvanliere** [comment]
Hi @panarasi - yes I was able to find a workaround. What I'm doing now is I start the react-native part of the app but don't display it yet. When booted, RN will check codepush for updates and when it's finished it will call back to the native app which will then display the RN view.
