### ISSUE TITLE
Does Codepush require an internet connection?

### ISSUE THREAD

**Issue by kevando** [Microsoft/react-native-code-push#664]
This might be a dumb question, but it's not obvious to me from the documentation.

I see the value of Codepush, but my app is designed to work offline and I get the sense that my js code is hosted on a server and I'm concerned it will not function properly without an internet connection.

**Comment by vonovak** [comment]
yes, code push does require internet to get its updates, but if the app doesn't connect to the internet it will just run the javascript bundle it has available on the device

**Comment by kevando** [comment]
Sweet! I look forward to trying this out. Looks promising, thanks for all the work

**Comment by aziz-boudi4** [comment]
@vonovak What the user has a bad/slow internet connection, what is the best practice in this scenario?

Our users get stuck in the downloading phase when they have a bad connection, any advice on how to deal with that?

**Comment by Rob117** [comment]
@aziz-boudi4 
Do you mean post-download from the App Store, or on the very first time the app boots up?

If it's just after using the app at least once, I would recommend performing all of your downloads in the background if it fits your use case. Users that have slower connections won't notice, and once the update is complete you can trigger a restart.

Other than that, something else you can do is show a sync icon, and if the update takes longer than x seconds time it out and tell them that the update failed due to poor connection quality and will try again on next reboot. For a better user experience, you could even use network status to check if they are on wifi and only update then, etc.

Of course, if the connection is always bad, that makes the situation pretty untenable and this may not be the best technology for you.
