### ISSUE TITLE
npm version different from github .zip

### ISSUE THREAD

**Issue by jonaswindey** [Microsoft/react-native-code-push#69]
If you install the version from npm with `npm i --save react-native-code-push`, it installs 1.2.1-beta but that still has `+ (NSURL *)getBundleUrl;`in CodePush.h

If you download the zip file directly from GitHub, it's the same 1.2.1-beta version in package.json but CodePush.h contains the correct `+ (NSURL *)bundleURL;` signature.

**Comment by lostintangent** [comment]
I'm waiting until tomorrow when we merge the Android support into master before releasing an update to NPM. I just checked in the rename from getBundleUrl to bundleURL, so that is one discrepency between the readme/master source and what is one NPM. If you want to use the version on GitHub, that should work great for you, otherwise, I'll update NPM tomorrow and you could use getBundleUrl in the meantime.

Sorry about the disconnect between the readme/website/NPM. We got a little out of sorts this week and will be much more organized moving forward.

**Comment by jonaswindey** [comment]
So stress, I guess I was just unlucky about my timing yesterday to start using this project ;)
