### ISSUE TITLE
cannot check the correct version when I apply multi test environment

### ISSUE THREAD

**Issue by L-Jovi** [Microsoft/react-native-code-push#728]
hi, thanks for your smart project, I encounter some strange issue when I build multi test environment.

* react-native-code-push: "^1.16.0-beta"
* react-native version: "0.37.0"
* iOS/Android/Windows version: iOS 10

---

I have 2 test env, Staging and Production,
our inner developers could test the Staging env by click the hidden button 6 times,
and outer user could receive Production when they open app.

now my hotfix flow as below step

1. upload Staging-0 version, our inner team could test it.

2. I promote Staging to Production version, and mark it as Production-0,
so all user could receive it, if our team already apply Staging-0 version, they don't receive the Production anymore (it's normal util now)

3. I change some code, and upload Staging-1 version, our inner team could also receive and apply it.

4. and then, if I apply the Staging-1 version, we could also receive Production-0 notification by open app again, I mean we could downgrade from Staging-1 to Production-0, but I don't think it correct.

at step 4, why we also receive Prodution-0 version notification, in my opinion, it's correct when I promote Staging to Production, and upload new Staging, and shouldn't receive any Production notification before.

how could I fix it?

thanks for your time,

regards.

**Comment by sergey-akhalkov** [comment]
Hi @L-Jovi, thank you for the question. 
Could you please confirm if you are using `info.plist` file to store production deployment key by default and using `codePush.sync({ deploymentKey: STAGING_KEY });` code to override default value by clicking the hidden button 6 times?
If so, please note that the deployment key specified via `codePush.sync({ deploymentKey: STAGING_KEY });` does not persist beyond the given call, and needs to be specified as an option each time it is used. It means that  after app restarts - production deployment key is in use again, so it is expected behavior that you've received Production-0 notification by open the app again.
To fix the issue you could probably use the following approach (or smth similar)":
1. The hidden button is being clicked 6 times, so the app should work in Staging mode from this moment across all app restarts.
```javascript
await AsyncStorage.setItem('isStaging', 'true');
```
2. Check if app works in Staging mode or not to choose what deployment `key` should be used, then launch CodePush sync:
```javascript
if (isStaging) {
    codePush.sync({ deploymentKey: STAGING_KEY });
} else {
    codePush.sync({ deploymentKey: PROD_KEY });
}
```
3. The hidden button is being clicked 6 times again, so the app should work in Production mode from this moment across all app restarts.
```javascript
await AsyncStorage.setItem('isStaging', 'false');
```
Please let me know if it helps or if you have any questions.

**Comment by L-Jovi** [comment]
@sergey-akhalkov  thanks for your reply :)

##about the config

> Could you please confirm if you are using info.plist file to store production deployment key by default and using codePush.sync({ deploymentKey: STAGING_KEY });

yes, I refer to the [README](https://github.com/Microsoft/react-native-code-push#multi-deployment-testing) and config the `$(CODEPUSH_KEY)` in __Info.plist__

##about the key specified as an option each time it is used

> code to override default value by clicking the hidden button 6 times?

> If so, please note that the deployment key specified via codePush.sync({ deploymentKey: STAGING_KEY }); does not persist beyond the given call, and needs to be specified as an option each time it is used. It means that after app restarts - production deployment key is in use again,

yes, I config my Production and Staging key in my js file as json format, and read them everytime when `codepush.sync` called.

##about the approach to fix issue

> 3. The hidden button is being clicked 6 times again, so the app should work in Production mode from this moment across all app restarts.

I just not very clear above step, I have 2 test env,
the hidden button which could be clicked 6 times only trigger Staging hotfix by our inner team,
and open app could directly trigger Production hotfix by all user (our inner team + outer user)

I'm not sure why click hidden button could trigger the Production hotfix, I execute the hotfix logic in separated user interaction.

actually I'm not ensure that I understand code-push logic right, in my opinion, code-push could "remember" the version at liner timeline(forgive my poor english, I dont know more appropriate word..)

I mean that if I push Staging-0 -> promote to Production - 0 -> push Staging-1, the code-push will know that the Staging-1 is newest version, so it will get `null` response from `checkForUpdate` the Production.

so if I understand right, I think my hotfix logic may make sense, I just don't understand clearly why the code-push still `checkForUpdate` Production available after our inner team already apply the newest Staging-1 version, I think it should response null is right.

sorry for the trouble,

thanks again for your patience.

regards.

**Comment by sergey-akhalkov** [comment]
@L-Jovi, `Staging` and `Production` deployments are actually two different "branches". At every single moment of the time `react-native-code-push` works with only one deployment and does not know anything about other deployments. This means that in case of using `Staging` deployment key your app will download updates from `Staging` "branch". Then, if you start using `Production` deployment key, CodePush will "forget" about `Staging` brunch and will try to download and apply the latest available CodePush update from `Production` "branch".

>and then, if I apply the Staging-1 version, we could also receive Production-0 notification by open app again, I mean we could downgrade from Staging-1 to Production-0, but I don't think it correct

You've received `Production-0` notification due to the app had reloaded and started using `Production` deployment key (specified by default in `info.plist` file). That's why I suggest you to save current deployment name in AsyncStorage to use it across all app restarts, so `Staging` deployment key will not be overridden by `Production` on next app restart.

Please let me know if you have any questions.

**Comment by L-Jovi** [comment]
@sergey-akhalkov   awesome, I eventually understand your mean, thanks for your patience :)
