### ISSUE TITLE
Different download stats of the app apk in codepush deployment history compared to the download stats of google play store

### ISSUE THREAD

**Issue by rahulmishra-goibibo** [Microsoft/react-native-code-push#736]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by rahulmishra-goibibo** [comment]
Hi, 

After pushing my app to the codepush server and then to the google play store i am getting a huge difference in total number of installs of the app by the users in codepush deployment history and google playstore. It's almost in the ratio 1:2 favouring the playstore. Can anybody guide me as why this could happen

**Comment by sergey-akhalkov** [comment]
Hi @rahulmishra-goibibo, sorry for late reply. Do you still experiencing the issue?
Do I get it right if you've released CodePush update for previous version of your app, let's say `1.1.1`, then you've increased app version to `1.1.2` and released you app to play store?
If so, I could propose, that some amount of your app users have installed CodePush update due to using old version `1.1.1` of your app. And users are using new version `1.1.2` won't install CodePush update due to it has been released for old version of the app.

Please let me know if you have any questions.

**Comment by rahulmishra-goibibo** [comment]
Hi @sergey-akhalkov Thanks for the reply. But the above scenario does not apply to me. This was the first time that i had pushed an update for my app with codepush. And going by your example i released the version 1.1.1(with codepush) and after that i have neither increased the version nor updated it yet. Although currently the difference is not much, to be precise it's almost showing 6 thousands downloads for this version(with codepush i.e. 1.1.1) in play store and a few hundreds less in the codepush console (almost 5.5 thousands total downloads). While there may not be that big a difference now, still i am wondering what could possibly be the reason for this ?

**Comment by sergey-akhalkov** [comment]
@rahulmishra-goibibo, CodePush SDK reports to the CodePush server if update was installed successfully on `componentDidMount` event. We also have implemented retry logic in case there is an error occurred while trying report deployment status (lost interned connection for example).
I could assume, that this mismatch have place due to there is a little difference between number of downloaded apps and number of active users who are using your app. Does it makes sense?

**Comment by rahulmishra-goibibo** [comment]
@sergey-akhalkov Yes. Thank you for the clarification. Much appreciated

**Comment by sergey-akhalkov** [comment]
@rahulmishra-goibibo, thank you for the response. 
Closing this, please feel free to reopen if needed.
