### ISSUE TITLE
how to adapt react-native verison 0.43.0-rc2

### ISSUE THREAD

**Issue by kevinTutu** [Microsoft/react-native-code-push#755]
hello,everyone:
     when I plan to upgrade the react-native version to 0.43.0,but the CodePushNativeModule.java file report an error,the ReactChroeographer.class can not be found.And I seek the file in the react package，indeed，they delete the file in the version 0.43.0-rc.2. How can I fix this problem, thanks.

**Comment by sergey-akhalkov** [comment]
Hello @kevinTutu, here is PR fixing the issue https://github.com/Microsoft/react-native-code-push/pull/735, please let me know if it helps or if you see any issues.

**Comment by kevinTutu** [comment]
um,it not fit me , the CodePushNativeModule.java is error, when 'import com.facebook.react.uimanager.ReactChoreographer' has a problem

**Comment by sergey-akhalkov** [comment]
@kevinTutu, could you please clarify - you have tried to apply [PR fixing the issue](https://github.com/Microsoft/react-native-code-push/issues/755#issuecomment-286381953) and the issue is steel reproduces?

Here you could see that React Native team has changed `ReactChoreographer` class location: https://github.com/Microsoft/react-native-code-push/pull/735/files#diff-99865b122cb5308ab005ac99ccb55da0L22

**Comment by kevinTutu** [comment]
oh..it's my fault,thanks a lot
