### ISSUE TITLE
After update android sdk and gradle ,can not build apk

### ISSUE THREAD

**Issue by chang-chaunce** [Microsoft/react-native-code-push#768]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

After update android sdk and gradle ,can not build apk. And i can't downgrade the sdk and gradle.If downgrade ,android studio will prompt  Minimum required is 25.0.0.

distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

ext {
  // Sdk and tools
  minSdkVersion = 16
  targetSdkVersion = 23
  compileSdkVersion = 24
  buildToolsVersion = '25.0.0'

  // App dependencies
  supportLibraryVersion = '25.2.0'
}

### Additional Information

* react-native-code-push version:latest
* react-native version:0.39
* iOS/Android/Windows version: android 
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

jenkins error:

10:04:11 FAILURE: Build failed with an exception.
10:04:11 
10:04:11 * What went wrong:
10:04:11 A problem occurred configuring project ':app'.
10:04:11 > Failed to notify project evaluation listener.
10:04:11    > Could not resolve all dependencies for configuration ':app:_zmlearnDebugApk'.
10:04:11       > A problem occurred configuring project ':react-native-code-push'.
10:04:11          > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-code-push'. Minimum required is 25.0.0
10:04:11    > Must apply 'com.android.application' first!
10:04:11 
10:04:11 * Try:
10:04:11 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
10:04:11 
10:04:11 BUILD FAILED

**Comment by sergey-akhalkov** [comment]
Hi @chang-chaunce, you've probably faced with this issue due to breaking changes that have been introduced by [Android plugin for Gradle, revision 2.3.0](https://developer.android.com/studio/releases/gradle-plugin.html)
To fix the issue please try to downgrade your version of `Android plugin for Gradle` to `2.2.3` [here](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/android/build.gradle#L8) and change `buildToolsVersion` value to `23.0.1` due to it's officially supported by React Native and CodePush.

**Comment by chang-chaunce** [comment]
@sergey-akhalkov  Thank you，you're right, I have fixed it.
