### ISSUE TITLE
Code pushing code for libs using react-native link (newb question)

### ISSUE THREAD

**Issue by jasan-s** [Microsoft/react-native-code-push#850]
I am just starting out with code push and am unclear of the following. 
Some of the libs i'm using at the moment use native modules thus I used react-native link.  If I were to change JS within my components that use these linked libraries, would the update be pushed to code push and my clients be able to receive it. ANd just the underlying native module code being linked cannot be changed and also if I'm adding another feature that requires a lib that uses link cannot be pushed.

**Comment by sergey-akhalkov** [comment]
Hi @jasan-s, thanks for reaching us. 
CodePush allows you to push client side assets only such us js bundle, images and etc. 
CodePush doesn't allow to update native-side code (Java, Objective-C), so it is probably not possible to push new lib with CodePush due to that lib may use native-side code. But I don't sure about libs that doesn't use native-side code, they probably can work.
Please let me know if you have any questions or see any issues.

**Comment by sergey-akhalkov** [comment]
@jasan-s, just a friendly ping.
