### ISSUE TITLE
My app has two jsbundle (two react native app), can code push manage two apps？

### ISSUE THREAD

**Issue by yellowChao** [microsoft/react-native-code-push#851]
my app have two jsbundle（two react native app），code push can manager two app？

**Comment by max-mironov** [comment]
Hey @yellowChao, thank you for your question. I believe that it is not possible due to we do not have logic to handle multiple packages in [bundleUrlForResourceMethod](https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePush.h#L27) . Please let us know if you have any thoughts or considerations about this.

**Comment by JuanbingTeam** [comment]
Hi @max-mironov 

#653 same issue here.

In my project, I can use CodePush to handle multiple bundles. 
Each RN entrance can config its own code push [code push app Id, bundle file name].
But the CodePushHash file is the real problem....Whole project can only have one CodePushHash file(Multiple res files with same name will only keep one).

**Comment by yellowChao** [comment]
when i read the source code (iOS),  code push update a new jsbundle file，just save a same file path，but i load another jsbundle , code push think this jsbundle already update, just load last time update jsbundel file。so yours can add logic to splite. 3q

**Comment by max-mironov** [comment]
@yellowChao, @JuanbingTeam  thank you so much for referencing the issue. So I'm afraid this is not something that code push supports "out of box". Currently we are working on CodeSigning feature and I'm not sure that we can handle this and investigate properly in the nearest time. However if you have time and could manage this you could add the corresponding PR. You help here would be much appreciated.
Please let us know if you have other thoughts or considerations about this.

**Comment by pniko** [comment]
Hi @yellowChao, we aren't currently planning to support this. If it is something more users request we will re-open and investigate further, but right now our existing backlog won't permit it.

**Comment by pniko** [comment]
Reopening this @yellowChao because we are now revisiting this issue and will support it in the near future.

**Comment by sergey-akhalkov** [comment]
Hi guys, I was able to configure with CodePush an android brownfield app that has 2 RN apps.
Here is the repo with demo: https://github.com/sergey-akhalkov/codepush2apps

Keynotes:
1. We have android brownfield app that has 2 RN apps.
2. [This folder](https://github.com/sergey-akhalkov/codepush2apps/tree/master/android/app/src/main/java/com/example/codepush2apps/codepush2apps) contains configured native code, please pay attention to the following lines of code:
[first](https://github.com/sergey-akhalkov/codepush2apps/blob/fd7b9666db27efa6022ecbd3524b183af8b71105/android/app/src/main/java/com/example/codepush2apps/codepush2apps/MyRNApp1.java#L40): `setJSBundleFile(CodePush.getJSBundleFile("CodePush/MyRNApp1/index1.android.bundle"))`
[second](
https://github.com/sergey-akhalkov/codepush2apps/blob/fd7b9666db27efa6022ecbd3524b183af8b71105/android/app/src/main/java/com/example/codepush2apps/codepush2apps/MyRNApp2.java#L40): `.setJSBundleFile(CodePush.getJSBundleFile("CodePush/MyRNApp2/index2.android.bundle"))`
3. `index1.js` and `index2.js` are entry points for both RN apps.
4. Use commands from [bundle-commands.txt](https://github.com/sergey-akhalkov/codepush2apps/blob/master/bundle-commands.txt) file to make initial RN bundles. 
Generated bundles are [here](https://github.com/sergey-akhalkov/codepush2apps/tree/master/android/app/src/main/assets/CodePush).
5. To make a CodePush update you should use `CodePush` dir as parent for you RN apps dirs, the example is [here ](https://github.com/sergey-akhalkov/codepush2apps/tree/master/CodePush). To generate update contents use commands from the [codepush-commands.txt](https://github.com/sergey-akhalkov/codepush2apps/blob/master/codepush-commands.txt) file.

Summary: single CodePush package/update contents bundles for both RN apps. This approach allows to update both apps at ones and we need not reimplement CodePush core in this case. We cannot use separate deployment for each RN app due to it requires significant changes in the CodePush core. It's also important to note that *rollback feature will not work correctly* in this case because an update can be registered as successful when first RN app will report that it works as expected, but the second RN app in the same moment can have a critical issue.

Screencast (update welcome string _Welcome to MY RN APP 111!_ -> _Welcome to MY RN APP 111! **v1**_):
![codepush2apps](https://user-images.githubusercontent.com/4928157/35284740-a12ffd08-006c-11e8-98fc-a188081187c7.gif)

**Comment by haven2world** [comment]
@yellowChao hi,i don't know whether you still need it. [my soluation on the segmentfault](https://segmentfault.com/a/1190000014585725?_ea=3677650)

**Comment by bird-xiong** [comment]
hope to support this soon

**Comment by vividh** [comment]
Any update / ETA on the official support for this feature? I have run into a use case where my RN app has a main and side-loaded bundle, and would be great to have codepush support for both.

**Comment by ashwini-ksingh** [comment]
Is this officially supported by CodePush?

**Comment by cherishedtoken** [comment]
I would like this feature too.

**Comment by The-Pascal** [comment]
I faced the same problem with CodePush, that it is able to manage one js bundle only, so I dug out and made some changes to the native Android code of CodePush.

So, now with these changes, CodePush can manage multiple JS bundles in the same application.

I have published an article on the same - https://medium.com/@chaharchandresh/multiple-codepush-in-same-application-5e3f57a9ae0b

And also published an npm library for it- https://www.npmjs.com/package/@the-pascal/react-native-code-push

Please feel free to use it and provide any suggestions you might have.

**Comment by guoguolong** [comment]
> I faced the same problem with CodePush, that it is able to manage one js bundle only, so I dug out and made some changes to the native Android code of CodePush.
> 
> So, now with these changes, CodePush can manage multiple JS bundles in the same application.
> 
> I have published an article on the same - https://medium.com/@chaharchandresh/multiple-codepush-in-same-application-5e3f57a9ae0b
> 
> And also published an npm library for it- https://www.npmjs.com/package/@the-pascal/react-native-code-push
> 
> Please feel free to use it and provide any suggestions you might have.

Does IOS support multiple bundles from codepush server?

**Comment by The-Pascal** [comment]
> Does IOS support multiple bundles from codepush server?

I haven't explored IOS yet, but I believe the same concept can be used
