### ISSUE TITLE
Configuration with name 'default' not found

### ISSUE THREAD

**Issue by weijianfeng** [Microsoft/react-native-code-push#855]
In Android Platform, when I install the plugin manually and sync. the following error occured:
'Configuration with name 'default' not found'

**Comment by max-mironov** [comment]
Hi @weijianfeng , this looks like the package probably is not linked. It would be great if we have more information to figure out what's the root cause. Can you please describe step by step what you have done, what you project structure looks like in Android Studio and what does your settings.gralde/build.gradle looks like?

Also can you please have a quick look at the following q's at SO to see if suggested answers could help?
https://stackoverflow.com/questions/22743582/error-configuration-with-name-default-not-found-in-android-studio
https://stackoverflow.com/questions/17188489/android-studio-gradle-configuration-with-name-default-not-found

**Comment by weijianfeng** [comment]
I have solved the problem.  
When changing settings.gradle I use the following steps to install plugin into the project instead of the steps in document.
File -> Module -> Import Gradle Project -> then  select the code push project in node_modules.
After the steps, the settings.gradle is changed.

Other steps are the same as that in document.

**Comment by max-mironov** [comment]
@weijianfeng - got it, thanks for quick turn around!
