### ISSUE TITLE
Is there a method to get remote binary version?

### ISSUE THREAD

**Issue by booker-laputa** [Microsoft/react-native-code-push#874]
### Description
When I want to get the targeting binary version of the latest bundle, I try to use checkForUpdate to get the RemotePackage but it return null.

### Reproduction
1. Install v1.0 app, publish v100 bundle
2. Create v2.0 app and publish v101 bundle targeting v2.0 binary
3. CheckForUpdate in v1.0 app, it returns null

### Additional Information

* react-native-code-push version: 1.11.2-beta
* react-native version: 0.44
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment]
@booker-laputa, please take a look at [target binary version parameter ](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) and let me know if you have any questions.

**Comment by booker-laputa** [comment]
@sergey-akhalkov I have tried.

The ideal case for me is to retrieve the latest bundle targeting binary version on all devices.
However, if I am on older binary version, I can only get the information of latest bundle targeting the the older version. 

Example:
a. Label v1 Targeting 1.0
b. Label v2 Targeting 2.0

If I am on 1.0 device, when I checkForUpdate, it will return Label v1.
I want to get the RemotePackage of update (b) no matter what binary version I am on

**Comment by sergey-akhalkov** [comment]
Hi @booker-laputa, thanks for the clarification. Unfortunately, there is no method to receive update(b) (that has been released for app 2.0) for app 1.0, due to `checkForUpdates ` relies on current binary version of your app while checking for updates. 
To avoid this limitation you can release an update that will have `targetBinaryVersion='*'`, so all your apps would be able to receive the latest update info, but you need to take control over installation process, due to update released for app 2.0 may have breaking changes and you won't install it on 1.0

Please let me know if you have any questions.

**Comment by booker-laputa** [comment]
Thanks for your answer.

I have to give up using CodePush for binary check.

However, I think CodePush should have the method to show all current information, like binary version and bundle label.

**Comment by sergey-akhalkov** [comment]
@booker-laputa, CodePush CLI has [history command](https://github.com/Microsoft/code-push/tree/master/cli#viewing-release-history), but I don't sure if it is what you are looking for due to you need this info on user's devices.

Closing this for now, please feel to reopen if needed or if you have any questions.
