### ISSUE TITLE
Bad link in API Reference docs

### ISSUE THREAD

**Issue by bigsassy** [Microsoft/react-native-code-push#896]
The docs in the API reference under the CodePushOptions -> updateDialog section states the following:

> Before enabling this option within an App Store-distributed app, please refer to this note.

Where `this note` is an anchor tag pointing to the ID `#user-content-apple-note`.  That ID doesn't exist on the page, so instead of linking to this seemingly important information it does nothing.

Does anybody know what information was supposed to be in `this note`, and can we get a pull request to properly add it to the documentation here?

**Comment by max-mironov** [comment]
Hey @bigsassy, thanks to pointing at this, I've [updated docs](https://github.com/Microsoft/react-native-code-push/pull/900) to point to correct link (probably was broken when we split docs to several parts).

**Comment by max-mironov** [comment]
I'll close the issue for now as PR has been merged.

**Comment by bigsassy** [comment]
Thanks, Max.  I looked at the link, but I don't actually see where it says having an update prompt is a no-no.  Did I just miss it?

**Comment by max-mironov** [comment]
@bigsassy so we are not saying that it is totally prohibited, we just wanted to aware that  it is against Apple's policy for an app to display an update prompt (so the app may be blocked by AppleStore somehow because of that). 
So we could only _recommend_  not to use it, but the final decision is always up to you.

**Comment by bigsassy** [comment]
Ok, thanks 👍
