### ISSUE TITLE
can not build after npm install this plugin

### ISSUE THREAD

**Issue by Kariko** [Microsoft/react-native-code-push#969]
![image](https://user-images.githubusercontent.com/14925329/29406114-aa6c5dc0-8372-11e7-8c0c-86e722426c87.png)

i have configured the files in Android as the readme.md do

**Comment by max-mironov** [comment]
Hi there @Kariko and thank you for your question. 

At that moment could you please provide us what version of `react-native` and `reac-native-code-push plugin` you are on?

**Comment by Kariko** [comment]
@max-mironov 
 "react-native": "0.46.0",
"react-native-code-push": "^5.0.0-beta",

**Comment by max-mironov** [comment]
@Kariko - got it and thanks!
Unfortunately RN 0.46.0 is not compatible with RNCP 5.0.0 and higher due to breaking changes introduced in latest react-native release.
You should use RNCP ^4.0.0 this way. Please checkout our compatibility table [here ](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms) and let us know if it helps.

**Comment by Kariko** [comment]
@max-mironov  
oh...thanks!I didn't pay attention to it ...
