### ISSUE TITLE
How is handled ios/android bundle difference? 

### ISSUE THREAD

**Issue by sulliwane** [Microsoft/react-native-code-push#97]
I'm trying code-push on android, and right now I upload to the same deployment key (and set same deployment key in plist.info/mainactivity.java), and so I put a description everytime I upload the main.jsbundle to code-push server to differentiate which is android which is ios version.

Is it the right way to do it? Or should I create one deployment target per platform (ex: production_android and production_ios).

Thanks.

**Comment by lostintangent** [comment]
Hey @sulliwane, we recommend that you actually create a seperate app for each platform. For example, many of our users create apps called "{AppName}-ios" and "{AppName}-android", and manage them seperate my that way.

You could achieve the same thing with seperate deployments under a single app as well, so it just depends on which strategy you prefer.

The important thing is that you have a different deployment for each, since you want to be able to release updates to each without impacting the other.

**Comment by sulliwane** [comment]
thanks, I will use two different deployments I think as it makes more sense to me.
