### ISSUE TITLE
Ignore optional code update

### ISSUE THREAD

**Issue by zheng-liu-seattle** [Microsoft/react-native-code-push#971]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Config the app to support code push, release
2. from CLI, code-push release-react with optional update (without --m)
3. App shows the dialog to ask if want to update
4. Click ignore..
5. Re-launch app, the app update dialog still show.

### Expected Behavior
With clicking ignore, should not show the same update again

### Actual Behavior
Every time launch, the update dialog shows even clicked ignore.
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hi @zheng-liu-seattle and thanks for reporting!

That doesn't look like an issue for me because I don't see anywhere in docs that we should ignore updates that were declined by user through update dialog.

We indeed have logic to [ignore failed updates](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L362) and that make sense not to install failed update twice.

For Update Dialog we [simply report](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L406) `UPDATE_IGNORED`status and that's it. 
I believe that we should not preserve the state of update being ignored as some users might really need that to be asked every time (but in fact we do not advise to use `UpdateDialog` at all because of [that note](https://github.com/Microsoft/react-native-code-push#store-guideline-compliance)).

If you have any other thoughts we are all ears though!

**Comment by zheng-liu-seattle** [comment]
Thank you @max-mironov for the advise, we decided to not use `UpdateDialog`.
